export default {
  $id: 'https://epa.gov/wqx/ActivityMediaSubdivision.json',
  title: 'Activity Media Subdivision',
  description: '',
  type: 'string',
  enum: [
    'Air moisture',
    'Ambient Air',
    'Artificial',
    'Borehole cuttings',
    'Borrow Soil, Waste Rock, and Protore material',
    'Bottom material',
    'Bulk Deposition',
    'Canopy water',
    'Const. Material',
    'Core material',
    'Deionized Water',
    'Domestic Sewage',
    'Drinking Water',
    'Dry Fall Material',
    'Effluent',
    'Elutriate',
    'Fecal material',
    'Filter Residue',
    'Finished Water',
    'Foam',
    'Geologic gases',
    'Groundwater',
    'Hyporheic zone',
    'Indoor Air',
    'Industrial Effluent',
    'Industrial Waste',
    'Interstitial Water',
    'Lake Sediment',
    'Landfill effluent',
    'Leachate',
    'Manure, green',
    'Manure, liquid',
    'Manure, solid',
    'Mine Tailings Pond',
    'Mixing Zone',
    'Mixing Zone, Zone of Initial Dilution',
    'Municipal Sewage Effluent',
    'Municipal Waste',
    'Ocean Water',
    'Oil/Oily Sludge',
    'Plant water',
    'Pore water',
    'Produced water',
    'Rainwater',
    'Rock/Cobbles/Gravel',
    'Septic Effluent',
    'Sieved Sediment',
    'Sludge',
    'Snowmelt',
    'Soil Gas',
    'Soil moisture',
    'Solids',
    'Stack Gases',
    'Stormwater',
    'Subsurface Soil/Sediment',
    'Surface Soil/Sediment',
    'Surface Water',
    'Surface Water Sediment',
    'Treated water supply',
    'USGS Standard Reference Sample',
    'UnSieved Sediment',
    'Unknown',
    'Untreated water supply',
    'Waste Gas',
    'Wastewater Treatment Plant Effluent',
    'Wastewater Treatment Plant Influent',
    'Water-Vadose Zone',
    'Wet Fall Material',
    'Wipe'
  ],
  maxLength: 45
}
