export default {
  "title": "Characteristic Group",
  "description": "",
  "type": "string",
  "enum": [
    "Biological",
    "Habitat",
    "Information",
    "Inorganics, Major, Metals",
    "Inorganics, Major, Non-metals",
    "Inorganics, Minor, Metals",
    "Inorganics, Minor, Non-metals",
    "Microbiological",
    "Not Assigned",
    "Nutrient",
    "Organics, Other",
    "Organics, PCBs",
    "Organics, Pesticide",
    "PFAS,Perfluorinated Alkyl Substance",
    "PFOA, Perfluorooctanoic Acid",
    "PFOS, Perfluorooctane Sulfonate",
    "Physical",
    "Population/Community",
    "Radiochemical",
    "Sediment",
    "Stable Isotopes",
    "Toxicity"
  ],
  "maxLength": 35
}