export default {
  $id: 'https://epa.gov/wqx/CharacteristicGroup',
  title: 'Characteristic Group',
  description: '',
  type: 'string',
  enum: [
    'Algae EDH',
    'Aquatic plants EDH',
    'Biological',
    'Biological, Counts',
    'Biological, Fish',
    'Cyanotoxins, Phytotoxins',
    'Habitat',
    'Information',
    'Inorganics, Major, Metals',
    'Inorganics, Major, Non-metals',
    'Inorganics, Minor, Metals',
    'Inorganics, Minor, Non-metals',
    'Microbiological',
    'Not Assigned',
    'Nutrient',
    'Organics, BDEs',
    'Organics, Other',
    'Organics, PCBs',
    'Organics, Pesticide',
    'PFAS,Perfluorinated Alkyl Substance',
    'PFOA, Perfluorooctanoic Acid',
    'PFOS, Perfluorooctane Sulfonate',
    'Periphyton',
    'Physical',
    'Physical, Habitat',
    'Phytoplankton, Cyanobacteria, Photosynthetic Pigments',
    'Population/Community',
    'Productivity',
    'Radiochemical',
    'Sediment',
    'Stable Isotopes',
    'Toxicity'
  ],
  maxLength: 53
}
