export default {
  $id: 'https://epa.gov/wqx/DetectionQuantitationLimitType',
  title: 'Detection Quantitation Limit Type',
  description: '',
  type: 'string',
  enum: [
    'Blank-adjusted method detect limit',
    'Blank-adjusted reporting limit',
    'Censoring level',
    'Contract Detection Limit',
    'Contract Quantitation Limit',
    'Daily detection limit',
    'Detection Limit',
    'Detection limit by DQCALC',
    'Drinking Water Maximum',
    'Estimated Detection Level',
    'Estimated Quantitation Limit',
    'Field Holding Time Limit',
    'Instrument Detection Level',
    'Interim Reporting Level',
    'Laboratory Holding Time Limit',
    'Laboratory Reporting Level',
    'Long Term Method Detection Level',
    'Lower 95% Confidence Limit',
    'Lower Quantitation Limit',
    'Lower Reporting Limit',
    'Lower limit of detection',
    'Measurement Uncertainty',
    'Method Detection Level',
    'Minimum Reporting Level',
    'Practical Quantitation Limit',
    'Reporting limit',
    'Reporting limit by DQCALC',
    'Required detection limit',
    'Sample Detection Limit',
    'Sample-Specific Quantitation Limit',
    'Sample-specific critical level',
    'Sample-specific min detect conc',
    'Specified in workplan',
    'Statistical Uncertainty',
    'Systematic Uncertainty',
    'Taxonomic Loss Threshold',
    'Upper 95% Confidence Limit',
    'Upper Calibration Limit',
    'Upper Quantitation Limit',
    'Upper Reporting Limit',
    'Water Quality Standard or Criteria'
  ],
  maxLength: 34
}
