export default {
  $id: 'https://epa.gov/wqx/HorizontalCollectionMethod',
  title: 'Horizontal Collection Method',
  description: '',
  type: 'string',
  enum: [
    'Address Matching-Block Face',
    'Address Matching-Digitized',
    'Address Matching-House Number',
    'Address Matching-Nearest Intersection',
    'Address Matching-Other',
    'Address Matching-Primary Name',
    'Address Matching-Street Centerline',
    'Census Block-1990-Centroid',
    'Census Block/Group-1990-Centroid',
    'Census Block/Tract-1990-Centroid',
    'Census-Other',
    'Classical Surveying Techniques',
    'GPS Carrier Phase Kinematic Relative Position',
    'GPS Carrier Phase Static Relative Position',
    'GPS Code (Pseudo Range) Differential',
    'GPS Code (Pseudo Range) Precise Position',
    'GPS Code (Pseudo Range) Standard Position (SA Off)',
    'GPS Code (Pseudo Range) Standard Position (SA On)',
    'GPS with Wide Area Augmentation System',
    'GPS, With Canadian Active Control System',
    'GPS-Unspecified',
    'Interpolation-Digital Map Source',
    'Interpolation-Digital Map Source (Tiger)',
    'Interpolation-MSS',
    'Interpolation-Map',
    'Interpolation-Other',
    'Interpolation-Photo',
    'Interpolation-Satellite',
    'Interpolation-Spot',
    'Interpolation-TM',
    'Loran C',
    'Public Land Survey-Eighth Section',
    'Public Land Survey-Footing',
    'Public Land Survey-Quarter Section',
    'Public Land Survey-Section',
    'Public Land Survey-Sixteenth Section',
    'Unknown',
    'Zip Code-Centroid',
    'Zip+2 Centroid',
    'Zip+4 Centroid'
  ],
  maxLength: 50
}
