export default {
  $id: 'https://epa.gov/wqx/HydrologicEvent.json',
  title: 'Hydrologic Event',
  description: '',
  type: 'string',
  enum: [
    'Affected by fire',
    'Algal bloom',
    'Backwater',
    'Dambreak',
    'Drought',
    'Earthquake',
    'Flood',
    'Glacial lake outbreak',
    'Hurricane',
    'Mudflow',
    'Not Determined (historical)',
    'Not applicable',
    'Regulated flow',
    'Routine sample',
    'Snowmelt',
    'Spill',
    'Spring breakup',
    'Storm',
    'Tidal action',
    'Under ice cover',
    'Volcanic action'
  ],
  maxLength: 27
}
