export default {
  "$id": "https://epa.gov/wqx/ResultTemperatureBasis.json",
  "title": "Result Temperature Basis",
  "description": "",
  "type": "string",
  "enum": [
    "05 Deg C",
    "10 Deg C",
    "100 Deg C",
    "103 Deg C",
    "104 Deg C",
    "105 Deg C",
    "110 Deg C",
    "15 Deg C",
    "180 Deg C",
    "20 Deg C",
    "25 Deg C",
    "30 Deg C",
    "35 Deg C",
    "37 Deg C",
    "40 Deg C",
    "41 Deg C",
    "42 Deg C",
    "43 Deg C",
    "44.5 Deg C",
    "45 Deg C",
    "50 Deg C",
    "55 Deg C",
    "60 Deg C",
    "65 Deg C",
    "70 Deg C",
    "75 Deg C",
    "80 Deg C",
    "85 Deg C",
    "90 Deg C",
    "95 Deg C",
    "STP"
  ],
  "maxLength": 10
}