export default {
  $id: 'https://epa.gov/wqx/ResultStatisticalBase',
  title: 'Result Statistical Base',
  description: '',
  type: 'string',
  enum: [
    '1 Pctl',
    '10 Pctl',
    '15 Pctl',
    '2-Sigma CSU',
    '20 Pctl',
    '25 Pctl',
    '30-day Geometric Mean',
    '30DADMean',
    '5 Pctl',
    '50 Pctl',
    '75 Pctl',
    '7DADM',
    '7DADMean',
    '7DADMin',
    '80 Pctl',
    '84 Pctl',
    '85 Pctl',
    '90 Pctl',
    '95 Pctl',
    '99 Pctl',
    'AMS',
    'AMS+',
    'Area-Weighted Mean',
    'BAV',
    'BNT',
    'Coefficient of error',
    'Coefficient of variation',
    'Count',
    'Daily Geometric Mean',
    'Daily Maximum',
    'Daily Mean',
    'Daily Median',
    'Daily Minimum',
    'Delta',
    'Geometric Mean',
    'Hourly Maximum',
    'Hourly Minimum',
    'Instantaneous',
    'Kurtosis',
    'Log Standard Error',
    'MPN',
    'Maximum',
    'Mean',
    'Median',
    'Minimum',
    'Mode',
    'N',
    'Percent Similarity',
    'Percent diff from true',
    'Percent of total',
    'Percent recovery',
    'Precision',
    'Quartile Deviation',
    'RAD Error',
    'Range',
    'Ratio',
    'Relative percent diff',
    'STV',
    'Single Sample Maximum',
    'Skewness',
    'Slope',
    'Standard Deviation',
    'Standard Error',
    'Sum',
    'Variance'
  ],
  maxLength: 24
}
