export default {
  $id: 'https://epa.gov/wqx/SampleTissueAnatomy.json',
  title: 'Sample Tissue Anatomy',
  description: '',
  type: 'string',
  enum: [
    'Abdomen',
    'Adrenal',
    'Arm',
    'Bark',
    'Bile',
    'Blood',
    'Blood Plasma',
    'Blood,Brachial,prim coll site',
    'Blood,Jugular+Metatarsal, pcs',
    'Blood,Jugular,prim coll site',
    'Blood,Metatarsal+Brachial, pcs',
    'Blood,Metatarsal,prim coll sit',
    'Body',
    'Body Wall',
    'Bone Tissue',
    'Bone, Acellular',
    'Bone, Cellular',
    'Bone, Marrow',
    'Brain',
    'Carapace',
    'Connective Tissue',
    'Digestive Gland',
    'Ear',
    'Edible Portion',
    'Egg/Ovum',
    'Eye',
    'Fat/Adipose Tissue',
    'Feather',
    'Feces',
    'Fin',
    'Fish Fillet, Homog., Skin Off',
    'Fish Fillet, Homog., Skin On',
    'Fish Fillet, Left, Skin Off',
    'Fish Fillet, Left, Skin On',
    'Fish Fillet, Right, Skin Off',
    'Fish Fillet, Right, Skin On',
    'Fish Fillet, Whole, Skin Off',
    'Fish Fillet, Whole, Skin On',
    'Fish Fillet, With Belly Flap',
    'Fish Fillet,Scaleless, Skin On',
    'Fish Scales',
    'Flower',
    'Foot',
    'Fore Gut',
    'Fruit',
    'Gall Bladder',
    'Gill Rakers',
    'Gills',
    'Gonads',
    'Gut',
    'Head',
    'Heart',
    'Hepatopancreas',
    'Hind Gut',
    'Intestine',
    'Kidney',
    'Leaf',
    'Liver',
    'Liver, Edible Portion',
    'Lung',
    'Milk',
    'Mixed Parts',
    'Muscle, Somatic',
    'Muscle, Visceral',
    'Muscle/Muscle Tissue',
    'Nerve Tissue',
    'Non-Lethal Fish Tissue Plug',
    'Offal',
    'Otoliths',
    'Ovary',
    'Pancreas',
    'Pistil',
    'Root',
    'Root/Tuber',
    'Saliva',
    'Seed',
    'Skeleton',
    'Skin',
    'Skin-On Fillets/Scales_On',
    'Spleen',
    'Stamen',
    'Stem',
    'Stomach',
    'Tentacles',
    'Testes',
    'Thymus',
    'Tissue+Mantle Cavity Fluid',
    'Tissue, Unspecified',
    'Urine',
    'Whole Bird, Featherless,SkinOf',
    'Whole Bird, Featherless,SkinOn',
    'Whole Bird, Feathers, Skin Off',
    'Whole Bird, Feathers, Skin On',
    'Whole Fish, Homog., Skin Off',
    'Whole Fish, Homog., Skin On',
    'Whole Fish, No Stomach Contents',
    'Whole Fish,Alimentary Tract',
    'Whole Fish,BeheadGutted,SkinOn',
    'Whole Fish,BeheadGuttedSkinOff',
    'Whole Organism',
    'Whole, Not Gut',
    'Wing',
    'Wood'
  ],
  maxLength: 31
}
