export default {
  "$id": "https://epa.gov/wqx/SampleCollectionMethod.json",
  "title": "Sample Collection Method",
  "description": "",
  "type": "string",
  "enum": [
    "AFS Coldwater Fish",
    "AFS NA Freshwater Fishes",
    "AFS Warmwater Fish",
    "ASTM 10500",
    "ASTM 10500.B",
    "ASTM 10500.C",
    "BIORECON FAMILY",
    "BIORECON GENERA",
    "BS0331",
    "BS0332",
    "BS0333",
    "BS0334",
    "BS0335",
    "CABIN 2012",
    "CABIN 2012 (Inverts)",
    "CDPHE Invert Protocols",
    "CDPHE Multihabitat Invert",
    "CDPHE Riffle Invert",
    "DEFT",
    "EPA RBP (Fish)",
    "EPA RBP (Inverts MHAB)",
    "EPA RBP (Inverts SHAB)",
    "EPA RBP Protocol",
    "EPA-841-B-07-009",
    "EPA-841-B-12-009",
    "GADNR Invert 2007 BM",
    "GADNR Invert 2007 CM",
    "GWPD 1-Measuring water levels ",
    "GWPD 17-Conducting",
    "GWPD 2-Identifying ",
    "GWPD 3-Establishing ",
    "Groundwater technical procedures ",
    "Guidance on Systematic Planning ",
    "HBMP 2012 Multihabitat Invert",
    "HBMP Invert Multihabitat",
    "Marion Invert 1999-2001",
    "Method to estimate discharge ",
    "NAWQA Algal DTH 2002 (Wade)",
    "NAWQA Algal QMH 2002 (Wade)",
    "NAWQA Algal RTH 2002 (Wade)",
    "NAWQA Ecological (1993)",
    "NAWQA Fish 2002 (Wade)",
    "NAWQA Habitat Protocols (1998)",
    "NAWQA Invert QMH 2002 (Wade)",
    "NAWQA Invert RTH 2002 (Wade)",
    "NAWQA Light 2002 (Wade)",
    "NAWQA Phytoplankton (APHY)",
    "NRSA Fecal 2009 (Boat)",
    "NRSA Fecal 2009 (Wade)",
    "NRSA Fecal 2013 (Boat)",
    "NRSA Fecal 2013 (Wade)",
    "NRSA Fish (Boat), 2009",
    "NRSA Fish 2009 (Wade)",
    "NRSA Fish 2013 (Boat)",
    "NRSA Fish 2013 (Wade)",
    "NRSA Habitat 2009 (Boat)",
    "NRSA Habitat 2009 (Wade)",
    "NRSA Habitat 2013 (Boat)",
    "NRSA Habitat 2013 (Wade)",
    "NRSA Invert 2009 (Wade)",
    "NRSA Inverts 2009/2013 (Boat)",
    "NRSA Inverts 2013 (Wade)",
    "NRSA Microcystins 2013 (Boat)",
    "NRSA Microcystins 2013 (Wade)",
    "NRSA Periphyton 2009 (Boat)",
    "NRSA Periphyton 2009 (Wade)",
    "NRSA Periphyton 2013 (Boat)",
    "NRSA Periphyton 2013 (Wade)",
    "NRSA Water Quality 2009 (Boat)",
    "NRSA Water Quality 2009 (Wade)",
    "NRSA Water Quality 2013 (Boat)",
    "NRSA Water Quality 2013 (Wade)",
    "OFR 93-104 FISH",
    "OFR 93-406",
    "OFR 93-409",
    "PIBO-EMP 2012 PHAB",
    "PIBO-EMP 2012 PHAB Protocol",
    "PNAMP 2007",
    "PNAMP Invert Analysis",
    "PNAMP Invert Collection",
    "Radiello",
    "SWAMP Bioassessment 2016",
    "SWAMP RWB",
    "TM1-D3 Field Meter Calibration",
    "TM1-D3 Monitor Operation",
    "TM1-D3 Monitor Selection",
    "TM1-D3 Site Selection",
    "TM1-D5 Data Processing",
    "TM1-D5 Instrument Deployment",
    "TM1-D5 Maintenance and Field",
    "TVA BIORECON FAMILY",
    "TWRI BK 9 CH A5.3.2",
    "TWRI BK 9 CH A5.6.1.F",
    "TWRI BK 9 CH A5.6.4.A",
    "TWRI BK 9 CH A5.6.4.B",
    "TWRI Book 9, Ch. A5",
    "TWRI9A",
    "USGS NAWQA 2002 Eco Protocols",
    "USGS TM1-D3",
    "USGS TM1-D5",
    "USGS WRIR 03–4331",
    "WRIR 98-4052 RHAB"
  ],
  "maxLength": 33
}