export default {
  Biological: '<http://hydro.geodab.eu/hydro-ontology/concept/2512>',
  'Biological, Algae': '',
  'Biological, Algae, Cyanobacteria': '',
  'Biological, Algae, Cyanobacteria, Photosynthetic Pigments': '',
  'Biological, Algae, Cyanobacteria, Photosynthetic,Phycocyanin': '',
  'Biological, Algae, Phytoplankton': '',
  'Biological, Algae, Phytoplankton, Aquatic Plants': '',
  'Biological, Algae, Phytoplankton, Cyanobacteria': '',
  'Biological, Algae, Phytoplankton, Cyanobacteria, Periphyton': '',
  'Biological, Algae, Phytoplankton, Photosynthetic Pigments': '',
  'Biological, Algae,Cyanobacteria,Photosynthetic,Phycoerythrin': '',
  'Biological, Algae,Phytoplankton,Cyanobacteria,Photosynthetic': '',
  'Biological, Aquatic Plants': '',
  'Biological, Carbon Production': '',
  'Biological, Counts': '',
  'Biological, Fish': '<http://hydro.geodab.eu/hydro-ontology/concept/3806>',
  'Biological, Fish Habitat, Filamentous Algae':
    '<http://hydro.geodab.eu/hydro-ontology/concept/3806>',
  'Biological, Habitat, Algae, Aquatic Plants': '',
  'Biological, Habitat, Algae, Phytoplankton': '',
  'Biological, Habitat, Aquatic Plants': '',
  'Biological, Habitat, Filamentous Algae': '',
  'Biological, Habitat, Plants': '',
  'Biological, Photosynthetic Pigments': '',
  'Biological, Plants': '',
  'Biological, Primary Production': '',
  'Cyanotoxins, Phytotoxins': '',
  Habitat: '',
  Information: '',
  'Inorganics, Major, Metals':
    '<http://hydro.geodab.eu/hydro-ontology/concept/2268>',
  'Inorganics, Major, Non-metals':
    '<http://hydro.geodab.eu/hydro-ontology/concept/2276>',
  'Inorganics, Minor, Metals':
    '<http://hydro.geodab.eu/hydro-ontology/concept/2300>',
  'Inorganics, Minor, Non-metals':
    '<http://hydro.geodab.eu/hydro-ontology/concept/2360>',
  Microbiological: '<http://hydro.geodab.eu/hydro-ontology/concept/2512>',
  'Not Assigned': 'Not Assigned values for field.',
  Nutrient: '<http://hydro.geodab.eu/hydro-ontology/concept/2381>',
  'Organics, BDEs': '',
  'Organics, Other': '<http://hydro.geodab.eu/hydro-ontology/concept/42>',
  'Organics, PCBs': '<http://hydro.geodab.eu/hydro-ontology/concept/1282>',
  'Organics, Pesticide': '<http://hydro.geodab.eu/hydro-ontology/concept/1833>',
  'PFAS,Perfluorinated Alkyl Substance': '',
  'PFOA, Perfluorooctanoic Acid':
    'renamed from PFOS, Perfluorooctane Sulfonate',
  'PFOS, Perfluorooctane Sulfonate':
    'renamed from PFOA, Perfluorooctanoic Acid',
  Periphyton: '',
  Physical: '',
  'Physical, Habitat': '',
  'Phytoplankton, Cyanobacteria, Photosynthetic Pigments': '',
  'Population/Community':
    '<http://hydro.geodab.eu/hydro-ontology/concept/4824>',
  Productivity: '',
  Radiochemical: '<http://hydro.geodab.eu/hydro-ontology/concept/2428>',
  Sediment: '',
  'Stable Isotopes': '<http://hydro.geodab.eu/hydro-ontology/concept/5001>',
  Toxicity: ''
}
