export default {
  'Aluminum Dish': 'Sample handled or stored in an aluminum dish',
  'Aluminum Foil Wrap': 'Sample secured within wrapper of aluminum foil',
  'BOD Bottle':
    'Sample bottle designed for use in measuring Biological Oxygen Demand (BOD)',
  'Carboy Container': 'Sample container designed for large samples',
  Cubitainer: 'Sample secured in Cubitainer',
  'Galvanized Steel Container': 'Container made of Galvanized Steel',
  'Glass Bottle': 'Sample bottle made of glass',
  'Glass Media Bottle': 'Sample container designed for incubation',
  'Glass Petri Dish': 'Sample container designed for incubation',
  'Glass Tube': 'Sample container designed for blood collection',
  'Glass Vial': 'Sample vial made of glass',
  'Glass Vial w/ Septa':
    'Sample container designed for collection of Volatile Organic Compounds (VOCs)',
  'HDPE Bottle': 'Sample bottle made of High Density Poly Ethylene (HDPE)',
  'HDPE Vial': 'Sample vial made of High Density Poly Ethylene (HDPE)',
  'Nalgene Bottle': 'Sample bottle made of Nalgene',
  'Nalgene Vial': 'Sample vial made of Nalgene',
  'PETG Bottle':
    'Sample bottle made of Polyethylene terephthalate glycol (PETG); Used in Sampling Harmful Algal Blooms-Microcystins can adhere to other types of plastic',
  'Plastic Bag': 'Plastic bag/baggie (e.g. ZipLoc)',
  'Plastic Bottle': 'Bottle made of unspecified plastic',
  'Plastic Dilution Bottle': 'Container designed for auto-dilution of sample',
  'Plastic Syringe':
    'A device used to transfer liquids into or out of a sampling area. It is made up of a hollow needle, which is attached to a tube and a plunger.',
  'Polycarbonate Media Bottle': 'Container designed for sample incubation',
  'Polyethylene Bottle': 'Sample bottle made of Polyethylene',
  'Polyethylene Container': 'Sample container made of Polyethylene',
  'Polyethylene Vial': 'Sample vial made of Polyethylene',
  'Polypropylene Bottle': 'Sample bottle made of Polypropylene',
  'Polypropylene Container': 'Sample container made of Polypropylene',
  'Polypropylene Vial': 'Sample vial made of Polypropylene',
  'Polystyrene Container': 'Sample container made of Polystyrene',
  'Polystyrene Petri Dish': 'Sample placed directly into a Petri Dish',
  SPMD: 'Semipermeable membrane device; also called "fatbag". It\'s a device that mimics parts of aquatic animals that cause bioconcentration.  SPMDs are used to assess contamination in water and air',
  'Stainless Steel Container': 'Container made of Stainless Steel',
  'Teflon Bottle': 'Sample bottle made of Teflon',
  'Teflon Vial': 'Sample vial made of Teflon',
  Unspecified: 'Unspecified'
}
