export default {
  '#/100L': 'Concentration Solution, Number per 100 liters',
  '#/100gal': 'Concentration Solution, Number per 100 gallons',
  '#/100mL': '()Concentration Solution, Number per hundred milliliters',
  '#/10L': 'Concentration Solution, Number per 10 liters',
  '#/500mL': 'Concentration Solution, Number per 500 milliliters',
  '#/L': 'Concentration Solution, Number per liter',
  '#/acre': 'Concentration Solution, Number per acre',
  '#/cm': '()Concentration Solution, Number per centimeter',
  '#/cm2': 'Concentration Solution, Number per square centimeter',
  '#/cm3': 'Concentration Solution, Number per cubic centimeter',
  '#/dL': 'Concentration Solution, Number per deciliter',
  '#/day': 'Concentration Solution, number per day',
  '#/ft2': 'Concentration Solution, Number per square foot',
  '#/g': '()Concentration Solution, Number per gram',
  '#/ha': 'Concentration Solution, Number per hectare',
  '#/hr': 'Concentration Solution, number per hour',
  '#/in2': 'Concentration Solution, Number per square inch',
  '#/km2': 'Concentration Solution, Number per square kilometer',
  '#/m2': '()Concentration Solution, Number per square meter',
  '#/m3': 'Concentration Solution, Number per cubic meter',
  '#/mL': 'Concentration Solution, Number per milliliter',
  '#/mi2': 'Concentration Solution, Number per square mile',
  '#/min': 'Concentration Solution, number per minute',
  '#/mm2': '()Concentration Solution, Number per square millimeter',
  '#/mm2/week':
    '()The number of particles per mm2 (particle density) after a week.',
  '#/sec*^*^*^*':
    'DO NOT USE, Concentration Solution, number (Counts) per second ***retired***use counts/sec',
  '#/um3': '()Concentration Solution, Number per cubic micrometer',
  '#/yd2': 'Concentration Solution, Number per square yard',
  '#col/100mL':
    'Concentration Solution, Number of (bacteria) colonies per 100 milliliters',
  '%': '()Concentration Percentage, Percent',
  '% CaCO3': '()Concentration Percentage, Percent calcium carbonate (CaCO3)',
  '% by vol': '()Concentration Percentage, Percent by volume',
  '% by wt': '()Concentration Percentage, Percent by weight',
  '% cover': '()Concentration Percentage, Percent Cover',
  '% passing': '()Concentration Percentage, Percent passing sieve',
  '% recovery': '()Concentration Percentage, Percent of recovery',
  '% saturatn*^':
    'DO NOT USE, Concentration Percentage, % saturation ***retired***use %',
  '% sediment':
    '()Concentration Percentage, % target/clean sed mix which produces response',
  '% solids': '()Concentration Percentage, Percent of solids',
  '(kg/sec)/m': '()Kilograms per second per meter',
  '0/00': 'Concentration Percentage, Parts per thousand',
  '1000m3/day': '()Flow, 1000 cubic metres per day',
  'ADMI value':
    '()Picklist or Choicelist, American Dye Manufacturers Institute Color Value (5 to 250 units Pt-Co)',
  ATU: 'Turbidity, Attenuation Unit',
  AU: '()Light Intensity, Absorbance unit, Absorbance is directly proportional to concentration and length, is a dimensionless quantity and should, therefore, be unitless',
  'AU/cm':
    '()Light Intensity, Absorbance per centimeters, optical density is measured in ODU, which are equivalent to AU cm​−1​',
  Angst: 'Length Distance, Angstroms',
  BTU: 'Energy, British Thermal Units',
  'BTU/ft3': '()Energy, British Thermal Units per cubic foot',
  BU: 'Turbidity, Backscatter Unit',
  'Bq/L': '()Radiation, Becquerels per litre',
  'Bq/g': '()Radiation, Becquerels per gram',
  'CCE/100mL':
    '()Concentration Solution, Calibrator Cell Equivalents per 100 Milliliters',
  'CE/100mL': '()Concentration Solution, Cell Equivalents per 100 milliliters',
  CFU: '()Concentration Solution, Colony Forming Units. CFU (Colony Forming Unit) estimates the number of viable microorganisms by growing them in a solid agar.',
  'COHS/1000ft':
    '()Concentration Solution, COHS/1,000 linear feet, represents the concentration of haze per 1000 linear feet of air sampled. 1 COH unit is the amount of dust. A linear foot is a 12-inch straight length',
  CU: 'Picklist or Choicelist, One color unit (CU) is equivalent to one Hazen unit and to one Pt-Co unit',
  DOY: '()Time, Day of year is a number between 1 and 365 ( or 1-366 for leap years) : Number Day / Day Number',
  Da: '()Molecular mass, Daltons',
  Deg: '()Location, Direction or angle, degrees',
  FAU: 'Turbidity, Formazine Attenuation Units',
  FBRU: '()Turbidity, Formazin Backscatter Ratio Units',
  FBU: 'Turbidity, Formazin Backscatter Unit',
  FNMU: 'Turbidity, Formazin Nephelometric Multibeam Unit',
  FNRU: 'Turbidity, Formazin Nephelometric Ratio Unit',
  FNU: 'Turbidity, Formazin Nephelometric Unit',
  FTU: 'Turbidity, Formazin Turbidity Units',
  Granules: '()Weight Mass, Granule count of substance in pan or tailings',
  HU: 'Picklist or Choicelist, Hazen unit',
  IVFU: '()Light Intensity, In vivo fluorescence units',
  'Imp gal': 'Volume, Imperial gallons',
  JCU: '()Light Intensity, Jackson Candle Units',
  JTU: 'Turbidity, Jackson Turbidity Units (FTU=0.4 x JTU)',
  Joules: 'Energy, Joules',
  'Kohm-cm':
    'Electric Resistivity, Kilo-ohms - centimeter (symbol: KΩcm). Resistance R is expressed in Kilo Ohm (KΩ) and distances are expressed in centimeters (cm)',
  L: '()Volume, Liters',
  'L/day': 'Flow, Liters per day',
  'L/hr': 'Flow, Liters per hour',
  'L/mg-cm': '()Concentration Solution, Liters per milligram-centimeter',
  'L/mg-m': 'Concentration Solution, Liter per milligrams by meter',
  'L/min': 'Flow, Liters per minute',
  'L/sec': 'Flow, Liters per second',
  Langleys: '()Energy Intensity, Langleys (cal/sq cm)',
  MFL: '()Concentration Solution, Million Fibers per Liter fiber size > 10u',
  'ML/day': '()Flow, Millions of liters per day',
  MPN: '()Concentration Solution, Most Probable Number. MPN (Most Probable Number) estimates the concentration of microorganisms by growing them in a liquid broth.',
  'MPN/100L': 'Concentration Solution, Most Probable Number per 100 liters',
  'MPN/100g': 'Concentration Solution, Most Probable Number per 100 grams',
  'MPN/100mL':
    '()Concentration Solution, Most Probable Number per 100 milliliters. MPN (Most Probable Number) estimates the concentration of microorganisms by growing them in a liquid broth.',
  'MPN/L': 'Concentration Solution, Most Probable Number per liter',
  'MPN/g': '()Concentration Solution, Most Probable Number per gram',
  MSC: '()Concentration Solution, Mean Standing Crop',
  'MT/km2/yr': 'Viscosity, Metric tons per square kilometer per year',
  'Megam-1':
    'Concentration Solution, Inverse Megameters or per Mega meters or Megam-1',
  'Mg/100cm2/d': '()Mega grams per 100 cm2 per day (d)',
  Mgal: 'Volume, Million gallons',
  'Mgal/day': '()Flow, Millions of gallons per day',
  'Mgal/mnth': 'Flow, Millions of gallons per month',
  'Mgal/year': 'Flow, Millions of gallons per year',
  Mgd: 'Flow, Millions of gallons per day',
  'Mgm/day': '()Megagrams per day; grams (gm) -- not case sensitive',
  Min: 'Location, Direction or angle, minutes',
  Molal: 'Concentration Molar, Molal',
  Molar: 'Concentration Molar, Molar',
  'Mole/L': 'Concentration Molar, Moles per liter',
  Mw: '()Power, megawatts',
  NTMU: 'Turbidity, Nephelometric Turbidity Multibeam Unit',
  NTRU: 'Turbidity, Nephelometric Turbidity Ratio Unit',
  NTU: '()Turbidity, Nephelometric Turbidity Units',
  None: '()Quantity, None',
  Normal: '()Quantity, Normal',
  PCU: '()Picklist or Choicelist, Platinum Cobalt Units (color) - American Public Health Association Color Scale, APHA = Pt-Co = Hazen Color',
  PSS: '()Concentration Solution, Practical Salinity Scale',
  PSU: 'Electrical conductivity, Practical Salinity Unit - It is equivalent to per thousand or (o/00) or to g/kg',
  Pascal: 'Pressure, Pascal units',
  'Plate cnt': '()Quantity, Plate Count',
  RFU: '()Light Intensity, Relative Fluorescence Units',
  RLU: '()Light Intensity, Relative light units',
  RU: '()Light Intensity, Raman units',
  'RUDS/10000ft':
    '()Light Intensity, Reflectance Units of Dirt Shade(RUDS). The soiling index or RUDS is the percentage reflectance obtained using a reflectometer; 10K linear ft of air is drawn through the filter paper',
  RmV: '()Power, Relative millivolts',
  'S/m': 'Electric Resistivity, Siemens per meter',
  SBU: '()Turbidity, Styrene Divinylbenzene Beads (SDVB) backscatter units',
  Sec: 'Location, Direction or angle, seconds',
  'T.O.N.': '()Picklist or Choicelist, Threshold Odor Number',
  'T.U.': 'Concentration Solution, Tritium Unit',
  TU: '()Toxic Units, dividing 100% by the LC50 (% effluent',
  TUc: '()Toxic Units, chronic',
  Torr: 'Pressure, Torr units(vacuum)',
  'W/m2': '()Power, Watts per square meter',
  Watts: 'Power, Watts',
  ac: 'Area, Acres',
  'ac-ft': 'Volume, Acre-feet',
  'ac-in': 'Volume, Acre-inches',
  amps: '()Electrical current, amperes',
  atm: '()Pressure, atmospheres',
  bar: 'Pressure, Bar',
  bbl: 'Volume, Barrel equals 31.50 gallons, 119.24 liters',
  beaufort: '()Movement Force, Wind force (beaufort unit)',
  cal: 'Energy, calories',
  'cal/cm2/day': '()Energy, Calories per square centimeter per day',
  'cal/cm2/hr': '()Energy, Calories per square centimeter per hour',
  'cal/cm2/min': '()Energy, Calories per square centimeter per minute',
  cd: '()Light Intensity, Candela',
  'cells/dL': '()Concentration Solution, Cells per deciliter',
  cfm: 'Flow, Cubic feet per minute',
  cfs: '()Flow, Cubic feet per second',
  'cfu/100g': '()Concentration Solution, Colony Forming Units per 100 grams',
  'cfu/100mL':
    '()Concentration Solution, Colony Forming Units per 100 milliliters. CFU (Colony Forming Unit) estimates the number of viable microorganisms by growing them in a solid agar.',
  'cfu/10mL': 'Concentration Solution, Colony Forming Units per 10 milliliters',
  'cfu/L': '()Concentration Solution, Colony Forming Units per liter',
  'cfu/gdw':
    '()Concentration Solution, Colony Forming Units per gram dryweight',
  'cfu/mL': '()Concentration Solution, Colony Forming Units per milliliters',
  cm: 'Length Distance, Centimeters',
  'cm-1':
    'Concentration Solution, Inverse centimeters or per centimeters or cm-1',
  'cm/sec': 'Speed Velocity, Centimeters per second',
  cm2: 'Area, Square centimeters',
  cm3: 'Volume, Cubic centimeters',
  'cm3/L': 'Concentration Percentage, Cubic centimeters per liter',
  'cm3/cm3':
    '()Concentration Percentage, Cubic centimeters per cubic centimeter',
  'cm3/g': '()Concentration Solution, Cubic centimeters per gram',
  'cm3/hr': 'Flow, Cubic centimeters per hour',
  'cm3/min': 'Flow, Cubic centimeters per minute',
  'cm3/sec': 'Flow, Cubic centimeters per second',
  code: '()Picklist or Choicelist, Please see http://waterdata.usgs.gov/nwis/qwdata?codes_table26_help#62955',
  copies: '()Concentration Solution, copies (ie viral load)',
  'copies/250mL':
    'Concentration Solution, copies per 250 milliliters (ie viral load)',
  'copies/mL':
    '()Concentration Solution, copies per milliliters (ie viral load)',
  count: '()Quantity, Count',
  'counts/sec': '()Concentration Solution, Counts per second',
  'd/h/m/s': '()Time, Days/hours/minutes/seconds',
  dB: '()Sound, Decibels',
  dL: 'Volume, Deciliters',
  dam3: '()Volume, cubic decameter',
  days: 'Time, Days',
  dddmmss: '()Location, Degrees - minutes - seconds of latitude or longitude',
  decibar: 'Pressure, Decibar',
  'deg C': '()Temperature, Degrees Celsius (Centigrade)',
  'deg C/100m': '()Temperature, Degrees Celsius (Centigrade) per 100 meters',
  'deg F': 'Temperature, Degrees Fahrenheit',
  'deg K': 'Temperature, Degrees Kelvin',
  dm: 'Length Distance, Decimeters',
  dm2: 'Area, Square decimeters',
  'dpm/100L':
    '()Concentration Solution, Disintegrations per minute per 100 liters',
  'dpm/cm3': '()Density, Disintegrations per minute per cubic centimeter',
  'dpm/g': '()Radiation, Decay per minute per gram',
  'drips/min': '()Flow, Drips per minute',
  drops: '()Volume, Drops',
  'eq/L': '()Concentration Solution, Equivalents per Liter',
  'fc/ft2': 'Light Intensity, foot candles per square foot',
  'fg/kg': '()Concentration Percentage, Femtogram/kilogram',
  'fibers/L': '()Concentration Solution, Fibers per liter',
  'fibers/cm3': '()Concentration Solution, Fibers per cubic centimeters',
  fraction: '()Concentration Percentage, Fraction of sample total',
  ft: 'Length Distance, Feet',
  'ft-candles': 'Light Intensity, foot candles',
  'ft-lbs': 'Energy, foot pounds',
  'ft/day': 'Speed Velocity, Feet per day',
  'ft/hr': '()Speed Velocity, Feet per hour',
  'ft/mile': '()Slope, feet per mile',
  'ft/min': 'Speed Velocity, Feet per minute',
  'ft/sec': 'Speed Velocity, Feet per second',
  ft2: 'Area, Square feet',
  ft3: 'Volume, Cubic feet',
  'ft3/day': 'Flow, Cubic feet per day',
  'ft3/sec': 'Flow, Cubic feet per second',
  g: '()Weight Mass, Grams',
  'g/L': 'Concentration Solution, Grams per liter',
  'g/cm2': 'Concentration Solution, Grams per square centimeters',
  'g/cm3': 'Density, Grams per cubic centimeter',
  'g/day': 'Flow Mass, Grams per day',
  'g/g': '()Concentration Percentage, Grams per gram',
  'g/hr': 'Flow Mass, Grams per hour',
  'g/kg': 'Concentration Percentage, Grams per kilogram',
  'g/m2': '()Concentration Solution, Grams per square meter',
  'g/m2/day': 'Viscosity, Grams per square meter per day',
  'g/m2/hr': 'Viscosity, Grams per square meter per hour',
  'g/m2/month': '()Viscosity, grams per metre squared per month mg/dm2/month',
  'g/m2/sec': '()Yield, Grams per square meter per second',
  'g/m3': 'Concentration Solution, Density, Grams per cubic meter',
  'g/m3/day': 'Viscosity, Grams per cubic meter per day',
  'g/m3/hr': 'Viscosity, Grams per cubic meter per hour',
  'g/mL': 'Concentration Solution, Grams per milliliter',
  'g/min': 'Flow Mass, Grams per minute',
  'g/sec': 'Flow Mass, Grams per second',
  'g/stalk': '()Concentration Solution, Grams per stalk',
  gal: 'Volume, Fluid gallons',
  'gal/day': 'Flow, Gallons per day',
  'gal/hr': 'Flow, Gallons per hour',
  'gal/min': 'Flow, Gallons per minute',
  'gal/sec': 'Flow, Gallons per second',
  'gc/uL': '()Concentration Solution, genomic copies per microliter',
  'geu/100mL':
    '()Concentration Solution, Genomic Equivalent Units per 100 milliliters',
  'geu/g': '()Concentration Solution, Genomic Equivalent Units per gram',
  gpg: 'Concentration Solution, Grains per gallon (grains/gal)',
  'gpm*^*^*^*^*':
    'DO NOT USE, Flow, Gallons per minute ***deprecated***use gal/min',
  'gpm/ft': '()Viscosity, Drawdown capacity, gallons per minute per foot',
  grains: 'Weight Mass, Grains',
  hPa: '()Pressure, Hectopascals',
  ha: 'Area, Hectares',
  hhmm: '()Time, Hour - minute, based on a 24-hour clock',
  hours: 'Time, Hours',
  hp: 'Power, horsepower',
  in: '()Length Distance, Inches',
  'in/day': '()Speed Velocity, Inches per day',
  'in/hr': '()Speed Velocity, inches per hour',
  'in/min': '()Speed Velocity, inches per minute',
  'in/week': '()Speed Velocity, inches per week',
  in2: 'Area, Square inches',
  in3: 'Volume, Cubic inches',
  inH2O: '()Pressure, inches of water',
  inHg: 'Pressure, inches of mercury (Hg)',
  'ipiu/100L':
    '()Concentration Solution, Most probable number of immune-peroxidase infectious units per 100L; intact and putatively infectious units (IPIUs); https://onlinelibrary.wiley.com/doi/pdf/10.1111/jfs.13077',
  'kOhm/cm': '()Electric Resistivity, Kilo ohm per centimeter',
  kPa: 'Pressure, Kilopascal',
  kcal: '()Energy, kilocalories',
  kg: 'Weight Mass, Kilograms',
  'kg/day': '()Flow Mass, Kilograms per day',
  'kg/day/mi2': '()Yield, kilograms per day per square mile',
  'kg/ha': 'Concentration Solution, kilograms per hectare',
  'kg/m2': 'Concentration Solution, Kilograms per square meter',
  'kg/m3': 'Density, Kilograms per cubic meter',
  'kg/m3-1000': '()Density, Kilograms per cubic meter minus one thousand',
  'kg/t': '()Concentration Solution, Kilograms per Tonne (metric ton)',
  'kg/t CaCO3*^':
    'DO NOT USE, Concentration Solution, Kilograms per Ton calcium carbonate (CaCO3)***retired***use kg/t and speciation = CaCO3',
  'kg/tons': '()Concentration Solution, Kilograms per tons',
  kgal: 'Volume, 1000 gallons',
  km: 'Length Distance, Kilometers',
  'km/hr': 'Speed Velocity, Kilometers per hour',
  'km/sec': 'Speed Velocity, Kilometers per second',
  km2: 'Area, Square kilometers',
  knots: 'Speed Velocity, Nautical miles per hour',
  kw: 'Power, kilowatts',
  lb: 'Weight Mass, Pounds',
  'lb/ac-ft': 'Concentration Solution, pounds per acre feet',
  'lb/acre/yr': 'Viscosity, Pounds per acre per year',
  'lb/day': '()Flow Mass, Pounds per day',
  'lb/day/mi2': '()Yield, pounds per day per square mile',
  'lb/ft2': '()Concentration Solution, pounds per square foot',
  'lb/ft3': '()Density, Pounds per cubic foot',
  'lb/hr': 'Flow Mass, Pounds per hour',
  'lb/in': '()Tension, pounds per inch displacement',
  'lb/kgal': 'Concentration Solution, Pounds/kilogallon',
  'lb/min': 'Flow Mass, Pounds per minute',
  'lb/sec': 'Flow Mass, Pounds per second',
  'lm/ft2': 'Light Intensity, lumens per square foot',
  'lm/m2': '()Light Intensity, lumens per square meter',
  'loc-sec':
    '()Location, Direction or angle, Locational seconds (latitude/longitude)',
  'log10 copies':
    '()Concentration Solution, Log10 copies (If Loga b = x, then a^x=b)',
  lumens: 'Light Intensity, lumens',
  m: 'Length Distance, Meters',
  'm-1*^*^*^*^*':
    'DO NOT USE, Inverse meters or per meters ***retired***use per m',
  'm/sec': '()Speed Velocity, Meters per second',
  'm/y': '()Time, Month/year',
  m2: '()Area, Square meters',
  'm2/g': '()Densisty, Square meters per gram',
  'm2/km2': '()Concentration Solution, Square meters per square kilometers',
  m3: '()Volume, Cubic meters',
  'm3/day': '()Flow, Cubic metres per day',
  'm3/hr': 'Flow, Cubic meters per hour',
  'm3/min': 'Flow, Cubic meters per min',
  'm3/month': '()Flow, Cubic meters per month',
  'm3/sec': 'Flow, Cubic meters per second',
  'm3/week': '()Flow, Cubic metres per week',
  'm3/yr': '()Flow, Cubic meters per year',
  mCi: 'Weight Mass, milliCuries',
  'mCi/km2': '()Radiation, milliCuries per square kilometer',
  mL: 'Volume, milliliters',
  'mL/L': 'Concentration Percentage, milliliters per liter',
  'mL/L/hr': '()Viscosity, milliliters per liter per hour',
  'mL/cm2/day': '()Milliliters per square centimeter per day',
  'mL/m3': 'Concentration Percentage, milliliters per cubic meter',
  'mL/min': '()Flow, milliliters per minute',
  'mL/sec': 'Flow, milliliters per second',
  'mS/cm': 'Electric Resistivity, milli-Siemens per Centimeter',
  'mS/m': '()Electric Resistivity, milli-Siemens per Meter',
  mSv: '()Radiation, milliSievert',
  mV: 'Power, millivolts',
  meq: '()Milliequivalents',
  'meq/100g': '()Concentration Percentage, milli-equivalents per 100 gram',
  'meq/L': '()Density, milli-equivalents per Liter',
  'metric ton': 'Weight Mass, Metric tons (tonne) or MT',
  mg: 'Weight Mass, milligrams',
  'mg N/l*^*^*^':
    'DO NOT USE, Concentration Solution, mg nitrogen in one liter of water or milligrams per liter Nitrogen  ***retired***use mg/l, speciation= as N, ',
  'mg/100g': 'Concentration Percentage, milligrams per 100 grams',
  'mg/L': '()Concentration Solution, milligrams per liter',
  'mg/L/hr': 'Viscosity, milligrams per liter per hour',
  'mg/cm2': 'Concentration Solution, milligrams per square centimeters',
  'mg/cm3': 'Density, milligrams per cubic centimeter',
  'mg/day': 'Flow Mass, milligrams per day',
  'mg/dm2/day': '()Viscosity, milligrams per decimetre squared per day',
  'mg/dm2/month': '()Viscosity, milligrams per decimetre squared per month',
  'mg/g': 'Concentration Percentage, Milligrams per gram',
  'mg/g/hr': '()Viscosity, milligrams per gram per hour ',
  'mg/hr': 'Flow Mass, milligrams per hour',
  'mg/kg': 'Concentration Percentage, Milligrams per kilogram',
  'mg/l CaCO3*^':
    'DO NOT USE, Concentration Solution, milligrams per liter calcium carbonate (CaCO3)***retired***use mg/l and speciation = CaCO3',
  'mg/m2': 'Concentration Solution, Milligrams per square meter',
  'mg/m2/day': '()Viscosity, milligrams per square meter per day',
  'mg/m2/hr': 'Viscosity, Milligrams per square meter per hour',
  'mg/m3': 'Density, milligrams per cubic meter',
  'mg/m3/day': '()Viscosity, Milligrams per cubic meter per day',
  'mg/m3/hr': 'Viscosity, Milligrams per cubic meter per hour',
  'mg/mL': 'Concentration Solution, milligrams per milliliter',
  'mg/min': 'Flow Mass, milligrams per minute',
  'mg/sec': 'Flow Mass, milligrams per second',
  'mho/cm': 'Electrical conductivity, mhos per centimeter',
  mi: 'Length Distance, Miles',
  mi2: 'Area, Square miles',
  micron: 'Weight Mass, Micron',
  milliMolar: 'Flow, milliMolar',
  millibar: 'Pressure, millibar',
  minutes: '()Time, Minutes',
  mm: 'Length Distance, millimeters',
  'mm/day': '()Speed Velocity, Millimeters per day',
  'mm/g': '()Millimeters per gram',
  'mm/hr': '()Speed Velocity, Millimeters per hour',
  'mm/sec': '()Flow, Millimeters per second',
  mm2: 'Area, Square millimeters',
  mm3: 'Volume, Cubic millimeters',
  'mm3/L': '()Concentration Percentage, Cubic millimeters per liter',
  mmH2O: '()Pressure, millimeters of water',
  mmHg: '()Pressure, millimeters of mercury',
  'mmhos/cm': '()Electrical conductivity, millimhos per centimeter',
  'mmol/L': '()Concentration Molar, millimoles per liter',
  'mmol/kg': '()Concentration Percentage, millimoles per kilogram',
  'mmol/m2': '()Millimoles per square meter',
  'mmol/m2/dy': '()Viscosity, millimoles per square meter per day',
  'mmol/m2/hr': 'Viscosity, millimoles per square meter per hour',
  'mmol/mg': 'Concentration Molar, millimoles per milligram',
  mmyy: '()Time, Date Month-Year',
  months: 'Time, Months',
  'mosm/kg': '()Concentration Molar, milliosmole per kg',
  mph: 'Speed Velocity, Miles per hour',
  mrem: 'Radiation, milliRem, one thousands of a rem (roentgen equivalent man)',
  'mrem/day': '()Radiation, millirems per day',
  'mrem/yr': 'Radiation, millirems per year',
  ms: 'Time, milliseconds',
  'nCi/L': 'Concentration Solution, Nanocuries per liter',
  ng: 'Weight Mass, Nanograms',
  'ng/L': 'Density, Nanograms per liter',
  'ng/cm2': 'Concentration Solution, Nanograms per square centimeter',
  'ng/cm3': 'Density, Nanograms per cubic centimeter',
  'ng/g': 'Concentration Percentage, Nanograms per gram',
  'ng/kg': 'Concentration Percentage, Nanograms per kilogram',
  'ng/m2': 'Concentration Solution, Nanograms per square meter',
  'ng/m2/day': '()Viscosity, Nanograms per square meter per day',
  'ng/m3': 'Density, Nanograms per cubic meter',
  'ng/mL': '()Density, Nanograms per milliliter',
  nm: 'Length Distance, Nanometers',
  'nm-1':
    'DO NOT USE, Inverse nanometers or per nanometers ***deprecated***use per nm 19-JUL-10',
  nmi: 'Length Distance, Nautical miles',
  nmi2: 'Area, Square nautical miles',
  'nmol/L': '()Concentration Molar, Nanomoles per liter',
  'nmol/g DW/h': '()Viscosity, Nanomoles per gram dry weight per hour',
  'nmol/hr/g': '()Viscosity, Nanomoles per hour per gram',
  'nmol/kg': 'Concentration Molar, Nanomoles per Kilogram',
  'nmol/m3': '()Concentration Molar, Nanomoles per cubic meter',
  nu: 'Concentration Percentage, Number or gage',
  ohm: '()Electrical resistance, ohms (symbol: Ω)',
  'ohm-cm': 'Electric Resistivity, ohms - centimeter (symbol: Ωcm)',
  'ohm-m':
    '()Electric Resistivity, ohms - meter (symbol: Ωm).  Ohm-meter is a unit of resistivity',
  oz: 'Weight Mass, Ounces',
  pCi: 'Weight Mass, Picocuries',
  'pCi/L': '()Radiation, Picocuries per Liter',
  'pCi/g': '()Radiation, Picocuries per gram',
  'pCi/m2': '()Radiation, Picocuries per square meter',
  'pCi/m3': 'Concentration Solution, Picocuries per cubic meter',
  'pCi/mL': 'Density, Picocuries per milliliter',
  'pct modern': '()Concentration Percentage, Percent modern',
  'per day': '()Time, Inverse days or per day',
  'per m': 'Inverse meter or per meter',
  'per mil': 'Concentration Percentage, Parts per thousand',
  'per nm': 'Inverse nanometers or per nanometers',
  'pfu/100L': '()Concentration Solution, Plaque Forming Units per 100 liters',
  'pfu/100mL':
    '()Concentration Solution, Plaque Forming Units per 100 milliliters',
  'pfu/L': '()Concentration Solution, Plaque Forming Units per liter',
  pg: 'Weight Mass, Picograms',
  'pg/L': 'Density, Picograms per liter',
  'pg/cm3': 'Density, Picograms per cubic centimeter',
  'pg/g': 'Concentration Percentage, Picograms per gram',
  'pg/kg': 'Concentration Percentage, Picograms per kilogram',
  'pg/m2': 'Concentration Solution, Picograms per square meter',
  'pg/m3': 'Density, Picograms per cubic meter',
  'pg/mL': 'Density, Picograms per milliter',
  phi: '()Weight Mass, Krumbein Phi Scale',
  pmc: '()Radiation, Percent modern carbon',
  'pmol/mg/min': '()Viscosity, Picomoles per milligram per minute',
  ppb: 'Concentration Percentage, Parts per billion',
  ppbv: 'Concentration Percentage, Parts per billion by volume',
  ppm: '()Concentration Percentage, Parts per million',
  ppmv: 'Concentration Percentage, Parts per million by volume',
  ppt: 'Concentration Percentage, Parts per trillion',
  ppth: 'Concentration Percentage, Parts per thousand',
  psf: '()Concentration Solution, Pounds per square foot',
  psi: 'Pressure, pounds per square inch',
  pt: 'Volume, Fluid pints',
  qt: 'Volume, Fluid quarts',
  seconds: 'Time, Seconds',
  'std*^*^*^*^*': 'DO NOT USE, Quantity, Standard Unit***retired***use None',
  'tCaCO3/Kt*^*':
    'DO NOT USE, Concentration Solution, Short tons of calcium carbonate (CaCO3) per kiloton***retired***use tons/kt and speciation = CaCO3',
  tons: 'Weight Mass, Short tons',
  'tons/ac ft': 'Concentration Solution, Short tons per acre feet',
  'tons/day': 'Flow Mass, Short tons per day',
  'tons/day/ft': '()Flow Mass, Short tons per day per foot',
  'tons/ft2': '()Short tons per square foot (tsf)',
  'tons/kt': '()Concentration Solution, Short tons per kiloton',
  'tons/sec': '()Flow Mass, Short tons per second',
  'tsc/100mL':
    '()Concentration Solution, Target Sequence Copy per 100 milliliters',
  'tsc/g': '()Concentration Solution, Target Sequence Copy per gram',
  uATM: 'Pressure, micro atmospheres',
  'uE/m2': '()Microeinsteins per square meter',
  'uE/m2/s': '()Viscosity, Microeinsteins per square meter per second',
  'uE/m2/sec':
    '()Viscosity, Photosynth. radiation,micro-Einsteins/sq.meter/sec',
  uL: 'Volume, Microliters',
  uPa2: '()Micropascals squared',
  uS: 'Electrical conductance, Micro-Siemens',
  'uS/cm': '()Electric Resistivity, Micro-Siemens per Centimeter',
  'uS/m': 'Electric Resistivity, Micro-Siemens per Meter',
  'uW/cm2': '()Power, Micro-watts per square centimeter',
  'ueq/L': 'Density, Micro-equivalents per Liter',
  ug: 'Weight Mass, Micrograms',
  'ug/100cm2': 'Concentration Solution, micrograms per 100 square cm',
  'ug/L': '()Density, Micrograms per liter',
  'ug/PUF': '()Concentration Solution, micrograms per polyurethane foam sample',
  'ug/cart': '()Concentration Solution, Micrograms per cartridge',
  'ug/cm2': '()Concentration Solution, Micrograms per square centimeters',
  'ug/cm2/30day': '()Viscosity, Micrograms per square centimeter per 30 day',
  'ug/cm2/day': 'Viscosity, Micrograms per square centimeter per day',
  'ug/cm3': 'Density, Micrograms per cubic centimeter',
  'ug/dm2/day': '()Viscosity, Micrograms per decimetre squared per month',
  'ug/dm2/month': '()Viscosity, Micrograms per decimetre squared per month',
  'ug/g': 'Concentration Percentage, Micrograms per gram',
  'ug/g DW/hr': '()Viscosity, Micrograms per gram dry weight per hour',
  'ug/hr/g': '()Viscosity, Micrograms per hour per gram',
  'ug/kg': '()Concentration Percentage, Micrograms per kilogram',
  'ug/m2': 'Concentration Solution, Micrograms per square meter',
  'ug/m2/hr': '()Viscosity, Micrograms per square meter per hour',
  'ug/m3': 'Density, Micrograms per cubic meter',
  'ug/mL': 'Density, Micrograms per milliliters',
  'ug/net': '()Concentration Solution, micrograms per net sample',
  'ug/scrubbie': '()Concentration Solution, micrograms per scrubbie sample',
  'ug/sec': '()Flow Mass, Micrograms per second',
  'ug/wipe': '()Concentration Solution, micrograms per wipe sample',
  um: '()Length Distance, Micrometers',
  'um/yr':
    '()Velocity, The micrometer (1 μm) is often called the micron. micron per year',
  um3: '()Volume, Cubic micrometers',
  'um3/100mL':
    '()Concentration Percentage, Cubic micrometer per 100 milliliters',
  'um3/L': 'Concentration Percentage, Cubic microns per liter',
  'um3/cm2': '()Concentration Solution, Cubic microns per square cm',
  'um3/mL': 'Concentration Percentage, Cubic microns per ml',
  umho: '()Electrical conductance, micro-mhos',
  'umho/cm': 'Electrical conductivity, micro-mhos per centimeter',
  umol: '()Weight Mass, Micromoles',
  'umol/L': 'Concentration Molar, Micromoles per liter',
  'umol/S/m2': '()Viscosity, Micromoles per siemen per square meter',
  'umol/g': 'Concentration Percentage, Micromoles per gram',
  'umol/kg': '()Concentration Molar, Micromoles per kilogram',
  'umol/m2/s':
    '()Viscosity, Micromoles square meter per second. For Light, photosynthetic active radiation (PAR). A unit of measure of the amount of light hitting a surface that is in the range of 400-700 nanometers',
  'umol/mol': '()Concentration Percentage, Micromoles per mole',
  'units/cm':
    '()Concentration Solution, Units per centimeter, for UV absorbance',
  'units/m': 'Concentration Solution, Units per metre, for UV absorbance',
  volts: '()Power, Electro-motive force, volts',
  weeks: 'Time, Weeks',
  'y/m/d': '()Time, Year/month/day',
  yd: 'Length Distance, Yards',
  yd2: 'Area, Square yards',
  yd3: 'Volume, Cubic yards',
  years: 'Time, Years',
  ymmdd: '()Time, Date Year (single digit) - Month - Day',
  yyyymmdd: '()Time, Date Year (four digits) - Month - Day'
}
