export default {
  16582: ' (Tribal)',
  123225: 'Beach Program',
  934010:
    'Confederated Tribes of the Umatilla Indian Reservation; Confederated Tribes of the Umatilla Indian Reservation Oregon',
  939785:
    'This is a duplicate organization setup for the NHDES and does not contain any data. It is strictly used for testing only.',
  947757: 'Confederated Tribes of Coos, Lower Umpqua and Siulsaw Indians; ',
  11113300: 'STATE OF NEW HAMPSHIRE ENVIRONMENTAL AGENCY',
  '0800257_WQX': 'Water quality',
  '0800597_WQX': 'Region 8 Superfund Program',
  '0800650_WQX': 'Water quality',
  '0800852_WQX': 'Water Quality Monitoring',
  '0801194_WQX': '',
  '0801417_WQX': 'Water Quality',
  '0801478_WQX': 'Region 8 Superfund Program',
  '0801505_WQX': 'water quality',
  '0801600_WQX': 'Water Quality Data',
  '0801695_WQX': 'Water Quality Data',
  '0801698_WQX': 'Water Quality Data',
  '0801812_WQX': 'Water Quality Data',
  '081575_WQX': '',
  '081577_WQX': 'The City and County of Denver',
  '081700_WQX': 'Gilt Edge Mine data',
  '0834QB00_WQX': 'Water Quality Data',
  '1083919_WQX': 'Bronx River Alliance',
  '1111REG1_WQX': 'Water Quality Monitoring Data',
  '1117MBR_WQX': 'Water Quality Data',
  '1119USBR_WQX': 'Water Quality Monitoring Data',
  '11COETUL_WQX': 'Water Quality Monitoring Data',
  '11DELMOD_WQX': 'Water Quality Monitoring Data',
  '11FLKNMS_WQX': 'Water Quality Monitoring Data.',
  '11NPSWRD_WQX': '',
  '11TOX09_WQX': 'Priority Pollutant Data',
  '1CTDPHBM': '',
  '1VTDECWQ': '',
  '211WVOWR_WQX':
    'Water Quality Monitoring Data for all the Waters in State of West Virginia.',
  '21AKBCH': 'Beach Monitoring Data',
  '21ALBCH': 'State of Alabama Environmental Agency',
  '21AQ_WQX': '',
  '21ARIZGW_WQX': 'Water Quality Monitoring',
  '21ARIZ_WQX': 'Water Quality Monitoring Data for all the Waters in the state',
  '21AS_WQX': '',
  '21AWIC': '',
  '21BRBCH': 'The Natural Resources Departhment within the Bad River Tribe',
  '21CABCH': 'Contractor for the State of California',
  '21CAOCSD_WQX': 'Water quality monitoring data',
  '21COL001_WQX':
    'Colorado DPHE Water Quality Control Division data migrated from legacy STORET',
  '21DEBCH': "Delaware's environmental organization",
  '21DELAWQ_WQX': 'Division of Water  Environmental Laboratory Section',
  '21FLACEP_WQX': 'Water Quality Monitoring Data',
  '21FLACST_WQX': 'Water Quality Monitoring Data',
  '21FLALTA_WQX': 'Water Qaulity Monitoring',
  '21FLAMEC_WQX': 'Water Quality Monitoring data',
  '21FLANER_WQX': 'Water Quality Monitoring Data',
  '21FLAVON_WQX': 'Water Quality Monitoring Data',
  '21FLA_WQX': 'Water Quality Monitoring Data',
  '21FLBABR_WQX': 'Water Quality Monitoring Data',
  '21FLBFA_WQX':
    'Partnering of The Bream Fisherman Association with  The Florida Department of Environmental Protection for Water Quality Monitoring for Santa Rosa and Escambia Counties',
  '21FLBRA_WQX': 'Water Quality Monitoring Data',
  '21FLBREV_WQX': 'Water Quality Monitoring Data',
  '21FLBROW_WQX': 'Water Quality Monitoring Data\nNELAC Certification #E46053',
  '21FLBSG_WQX': 'Surface water Biological Sediment',
  '21FLCBA_WQX': 'Water Quality Monitoring Data',
  '21FLCCSW_WQX': 'Water quality monitoring data',
  '21FLCCZM_WQX': 'Water Quality Monitoring Data',
  '21FLCEN_WQX': 'Water Quality Monitoring Data',
  '21FLCHAR_WQX':
    'The Charlotte Harbor Estuaries Volunteer Water Quality Monitoring Network (CHEVWQMN)',
  '21FLCHDH': '',
  '21FLCHDH_WQX': 'Water Quality Monitoring Data',
  '21FLCMP_WQX':
    'Okaloosa County Environmental Council water quality monitoring organization ("Aqualab") partnering with The Florida Department of Environmental Protection for  Water Quality Monitoring of Choctawhatchee Bay and adjacent water bodies.',
  '21FLCOAB_WQX': 'Water Quality Monitoring data',
  '21FLCOBS_WQX': 'Water Quality Monitoring Data',
  '21FLCOFM_WQX': 'Water Quality Monitoring Data',
  '21FLCOJB_WQX': 'Water Quality Monitoring data',
  '21FLCOLL_WQX': '3339 Tamiami Trail East, Suite 304\nNaples, FL 34112',
  '21FLCOMI_WQX': 'Water Quality Monitoring Data',
  '21FLCONB_WQX': 'Water Quality Monitoring Data',
  '21FLCONS_WQX': 'Water Quality Monitoring',
  '21FLCOPC_WQX': 'Water Quality Monitoring Data',
  '21FLCOSP_WQX': 'Water Quality Monitoring data',
  '21FLCOT_WQX': 'Water Quality Monitoring Data',
  '21FLCPSJ_WQX': 'water quality monitoring data',
  '21FLCPSL_WQX': 'Water Quality Monitoring Data',
  '21FLCRCP_WQX': 'Water Quality Monitoring Data',
  '21FLDADE_WQX': 'Water Quality Monitoring Data',
  '21FLDELT_WQX': 'Water Quality Monitoring',
  '21FLDOH_WQX': 'Floridas Healthy Beaches Program Water Quality Data',
  '21FLDUNE_WQX': 'City of Dunedin',
  '21FLEECO_WQX': 'Ambient Surface Water Quality Monitoring Data',
  '21FLERDI_WQX': 'Water Quality Monitoring Data',
  '21FLESC_WQX': 'Water Quality Monitoring Data',
  '21FLESPI_WQX': 'Water Quality Monitoring Data',
  '21FLFMRI_WQX': 'Water Quality Monitoring Data',
  '21FLFRYD_WQX': 'Water Quality Monitoring Data',
  '21FLFSI_WQX': 'Water Quality Monitoring Data',
  '21FLFTM_WQX': 'Water Quality Monitoring Data',
  '21FLFWC_WQX': 'Water Quality Monitoring Data',
  '21FLGAEP_WQX': 'Water Quality Monitoring Data',
  '21FLGBO1_WQX':
    'Water Quality Monitoring Data: USEPA Office of Research and Development, National Health and Environmental Effects Research Laboratory (NHEERL), Gulf Ecology Division',
  '21FLGCWW_WQX': 'Groundwater Monitoring',
  '21FLGFWF_WQX': 'Water Quality Monitoring Data',
  '21FLGPC_WQX': 'Water Quality Monitoring Data',
  '21FLGTM_WQX': 'Water Quality Monitoring Data',
  '21FLGWMS_WQX': 'Water Quality Monitoring Data',
  '21FLGW_WQX': 'Water Quality Monitoring Data',
  '21FLHBOI_WQX': 'Water Quality Monitoring Data',
  '21FLHILL_WQX':
    'Ambient water quality monitoring data collected by Hillsborough County Environmental Protection Commission, Monitoring and Analysis Section\n\nNote: Detection limit for Enterococcus bacteria is 2 / 100 mL unless otherwise indicated for 2001.',
  '21FLIMCA_WQX': 'Surface Water Data',
  '21FLJEA_WQX': 'Water Quality Monitoring data',
  '21FLJXWQ_WQX': 'Water Quality Monitoring data',
  '21FLKEYW_WQX': 'Water Quality Monitoring Data',
  '21FLKISS_WQX': 'Water Quality Monitoring Data',
  '21FLKTNC_WQX': 'Water Quality Monitoring Data',
  '21FLKWAT_WQX': 'Water Quality Monitoring Data',
  '21FLLCHD_WQX': 'Water Quality Monitoring Data',
  '21FLLCPC_WQX': 'Water Resource Monitoring for Lake County',
  '21FLLEHI_WQX': 'Water Quality Monitoring Data',
  '21FLLEON_WQX': 'Water Quality Monitoring Data',
  '21FLLOXB_WQX': 'Biological Data',
  '21FLLOX_WQX': 'Water Quality Monitoring Data',
  '21FLMANA_WQX': 'Water Quality Monitoring Data',
  '21FLMAYP_WQX': 'Water Quality Monitoring data',
  '21FLMCGL_WQX': 'Water Quality Monitoring Data',
  '21FLMOSA_WQX': 'Mosaic Fertilizer, LLC.',
  '21FLMRC_WQX': 'Water Quality Monitoring Data',
  '21FLNAPL_WQX': 'Water Quality Monitoring Data',
  '21FLNWFD_WQX': 'Ambient Water Quality Monitoring Data',
  '21FLORAN_WQX': 'Ambient Water Quality Monitoring of Data',
  '21FLORL_WQX':
    "Within the Stormwater Division, our mission is to collect and maintain, through water samples, monitoring and inspections, the data necessary to support the preservation of the quality of Orlando's lakes.",
  '21FLPASC_WQX': 'Water Quality Monitoring Data',
  '21FLPBCH_WQX': 'Water Quality Monitoring',
  '21FLPBSD_WQX': 'Water Quality Monitoring Data',
  '21FLPCSW_WQX': 'Water Quality Monitoring Data',
  '21FLPDEM_WQX':
    'The Water Resources Management Section (WRMS) of the Pinellas County Department of Environmental Management (DEM) began the Surface Water Ambient Monitoring Program (SWAMP) in 1990 as part of the County Comprehensive plan of 1989.',
  '21FLPNS_WQX':
    'Water Quality Monitoring Data for the Watershed Management Section of the Water Resources Department of The Florida Department of Environmental Protection',
  '21FLPOLK_WQX':
    'To monitor, manage, prtoect and improve the groundwater and surface water resources of Polk County',
  '21FLRCID_WQX': 'Water Quality Monitoring Data',
  '21FLROOK_WQX': '',
  '21FLSARA_WQX': 'Surface Water, Ground Water, Biological, & Sediment.',
  '21FLSBL_WQX': 'Water Quality Monitoring Data',
  '21FLSCCF_WQX': 'Water Quality Monitoring Data',
  '21FLSEAS_WQX': 'Water Quality Monitoring Data',
  '21FLSEM_WQX': 'Water Quality Monitoring Data',
  '21FLSFWM_WQX': 'Water Quality Monitoring Data',
  '21FLSGCSP': '',
  '21FLSJWM_WQX': 'Water Quality Monitoring Data',
  '21FLSMRC_WQX': '',
  '21FLSUW_WQX': 'Water quality Monitoring Data',
  '21FLSWFD_WQX': 'Water Quality Monitoring Data',
  '21FLTBW_WQX': 'Water Quality Monitoring Data.??',
  '21FLTHAS_WQX': 'Water Quality Monitoring Data',
  '21FLTHLR_WQX':
    'Florida Department of Environmental Protection-Tallahassee ROC',
  '21FLTLHR_WQX': 'Water quality monitoring data',
  '21FLTPA_WQX':
    'State environmental regulatory agency which generates water and sediment quality data, physicochemical data and biological data.',
  '21FLVEMD_WQX':
    'The VCEHL is a full service local laboratory formed by combining County of Volusia Environmental Management Services and state Department of Health personnel.  Ambient monitoring of three river systems is conducted.',
  '21FLWET_WQX': 'Water Qaulity Monitoring',
  '21FLWPBH_WQX': 'Water Quality',
  '21FLWPB_WQX': 'Water Quality Monitoring Data',
  '21FLWQA_WQX':
    'Watershed Assessment Section (WAS) - Formerly WQAS\nSurface Water Quality Monitoring Data and TMDLs',
  '21FLWQSP_WQX': 'Water Quality Monitoring Data',
  '21GACRD': 'COASTAL RESOURCES DIVISION',
  '21GAEPD_WQX': 'Georgia DNR Environmental Protection Division',
  '21GA_WQX': 'Water Quality Monitoring Data for all the Waters in the state',
  '21GPBCH': '',
  '21GUAM': 'Water Quality Monitoring Data',
  '21GUBCH': '',
  '21HI': '',
  '21ILBCH_WQX': '',
  '21INBCH': '',
  '21INDEM': '',
  '21IND_WQX': 'Water Quality Monitoring Data for all the Waters in the state',
  '21IOWA_WQX':
    'Data collected by the Iowa Dept. of Natural Resources Water Monitoring Section or one of its delegates.',
  '21KAN001_WQX':
    'Water Quality Monitoring Data for all the Waters in the state',
  '21KY_WQX': 'KY WQX',
  '21LABCH': '',
  '21MABCH': '',
  '21MEBCH': 'Maine Dept of Env Protection.',
  '21MICH_WQX': '',
  '21MNBCH': '',
  '21MSBCH': 'Mississippi Agency responsible for Beaches data',
  '21MSWQ_WQX':
    "The Mississippi Department of Environmental Quality is responsible for protecting the state's air, land, and water. Our mission is to safeguard the health, safety, and welfare of present and future generations of Mississippians by conserving and improving our environment and fostering wise economic growth through focused research and responsible regulation.",
  '21NC01WQ_WQX':
    'Water Quality Monitoring Data for all the Waters in the state',
  '21NC02WQ_WQX':
    'Water Quality Monitoring Data for all the Waters in the state',
  '21NC03WQ':
    'State of North Carolina, Department of Environment and Natural Resources.',
  '21NCBCH':
    'NC Department of Environment and Natural Resources, Division of Environmental Health, Recreational Water Quality Program',
  '21NCCOALITIONS': 'NC DWQ Monitoring Coalition Program',
  '21NCMONITORING': 'NC DWR Monitoring Coalition Program',
  '21NDHDWQ_WQX': 'Division Of Water Quality',
  '21NEB001_WQX': '',
  '21NEV1_WQX': 'Nevada Division of Environmental Protection',
  '21NJBCH': '',
  '21NJDEP1_WQX': '',
  '21NMEX_WQX': 'NM Environmental Dept./SWQB',
  '21NYBCH': '',
  '21NYDECA_WQX': 'To protect and conserve the waters of New York State',
  '21OHBCH': '',
  '21OHDGW_WQX': '',
  '21OHIO_WQX': '',
  '21ORBCH': 'Beaches Program',
  '21PABCH': 'LOCAL HEALTH DEPARTMENT',
  '21PA_WQX': 'PA ENVIRONMENTAL PROTECTION',
  '21RIBCH': '',
  '21SC60WQ_WQX': '',
  '21SCBCH_WQX': '',
  '21SCESOP_WQX': 'Water Quality Monitoring Data',
  '21SCGW_WQX': 'Groundwater Monitoring Data',
  '21SCSANT_WQX': 'SC Public Service Authority',
  '21SCSHL_WQX': '',
  '21TNWQ_WQX': '',
  '21TXBCH': 'GLO',
  '21VABCH': 'Beach Program',
  '21VASWCB': '',
  '21WABCH': '',
  '21WIBCH': '',
  '21WVWQAS_WQX':
    'Water Quality Monitoring Data for all the Waters in the state',
  '22LAGWTR_WQX': 'Ground water data',
  '31DELRBC_WQX': '',
  '31DRBCSP_WQX': 'Water Quality Monitoring Data',
  '31ISC2RS_WQX': 'A Tri-State Water and Air Pollution Control Agency',
  '31ORWUNT_WQX': 'Water Quality Monitoring Data',
  '42SRBCWQ_WQX': 'Water Quality Monitoring Data',
  '501CTHREE': 'Bring clean water to communities in need.',
  '952307_WQX': '',
  A4GL_WQX: '',
  ABCI_WQX:
    'Tribal Environmental Protection Agency for the Augustine Band of Cahuilla Indians',
  ABSHAWNEE: 'Absentee Shawnee Tribe of Oklahoma',
  ACBCI_WQX: 'Agua Caliente Band of Cahuilla Indians; ',
  ACIC_WQX: 'Ak-Chin Indian Community Environmental Protection Department; ',
  ACOMA_PUEBLO_WQX: 'Pueblo of Acoma; Pueblo of Acoma',
  ADGGS: 'Alaska Division of Geological & Geophysical Surveys',
  ADVENTURESCIENTISTS:
    'Citizen science data collection in far flung locations around the world.',
  AFW_PDX: 'Portland, Oregon office',
  AHRA: '',
  AIEO: 'American Indian Environmental Office; ',
  'AK-CHIN_WQX':
    'Ak-Chin Indian Community; Environmental Protection Authority; Water Quality Program',
  AKBLM_FDO: 'Water Quality Monitoring Data',
  AKDECAKMAP:
    'The mission of DEC\'s Division of Water is to improve and protect the quality of all Alaskan waters and under the Clean Water Act (CWA)Sections 303(d) and 305(b) Alaska has the responsibility to report and identify causes and sources of water quality impairment by "characterizing all the waters in Alaska". One way the division carries out this mission is to monitor and report on water quality. The Alaska Monitoring & Assessment Program (AKMAP) fulfills this responsibility.',
  AKDECSPAR: '',
  AKDECWQ: 'Water quality Standards Assessment & Restoration',
  AKDFGSPF: 'Alaska Department of Fish and Game, Division of Sport Fish',
  AKDNRFOR: '',
  'ALABAMACOUSHATTATRIBE.TX_WQX': 'Alabama-Coushatta Tribe of Texas;',
  ALASSWCD_WQX: 'Water Quality Monitoring Data',
  ALLARM: '',
  ALO_WQX:
    'Promote and maintain clean water and a healthy coastal environment through education, research, and active participation.',
  ALS: 'The American Littoral Society promotes the study and conservation of marine life and habitat, protects the coast from harm, and empowers others to do the same.',
  ANCHORQEA: 'Clients',
  ANIMASWP:
    'The AWP is a stakeholder driven, collaborative, watershed-based group made up of partners representing diverse interests across the watershed in New Mexico, the Southern Ute Tribal Lands and Colorado. Current membership is over 100 individuals and entities. The AWP works together across state and Tribal boundaries to protect and improve the quality of water resources in the Animas River.',
  ANTIX_WQX: 'National Park Service',
  APPLEGATE_WC: 'Former VolMon group',
  AQUINNAH_WQX: 'Wampanoag Tribe of Gay Head (Aquinnah) - Massachusetts;',
  ARDEQH2O_WQX: '',
  ARMYCORPS: 'US Army Corps of Engineers District (West Virginia)',
  ARR: '',
  ARSG: 'Water Quality Monitoring Data',
  ARWRF: '',
  ARWWRRI_WQX: 'Water Quality Monitoring Data: BIOmonitoring',
  ASEPA_WQX: '',
  ASPECT_WQX: '',
  ASUERF: '',
  AURORA_WQX: 'Water Quality Monitoring Data',
  AWC_WQX:
    'Water Quality Monitoring Data. American Water is a water resource company where the majority of the companys activities are centered in locally-managed utility subsidiaries that are regulated by the state in which each operates.',
  AWQDECJN: '',
  AWQDECJN_WQX: '',
  AWRC: '',
  AWRL: '',
  AZDEQ_GW: 'Water Quality Division: Groundwater',
  AZDEQ_SW: 'Water Quality Division: Surface Water',
  AZDEQ_WPD: 'Waste Programs Division',
  BACKBAYNWR: 'Back Bay National Wildlife Refuge',
  BADRIVER_WQX: 'Bad River Tribe',
  BATTELLE_NFTDR_WQX: 'Battelle',
  BATTELLE_NOR_WQX: '',
  BBP_WQX:
    'The Barnegat Bay Partnership is a partnership of federal, state, municipal, academic, business, and private organizations working together to help restore, protect, and enhance the natural resources of the Barnegat Bay ecosystem.',
  BCENV:
    'Ministry of Environment and Climate Change Strategy, Environmental Protection Division',
  BCHMI_WQX: 'Beaches Program Data',
  BCUTAHLAB: 'Brigham City Laboratory',
  BEAR_CRK_WQX: 'Water Quality Data',
  BERGERGROUP: '',
  BERRY: '',
  BESD: 'Colorado',
  BETA_OCMA: '',
  BIGDRY: '',
  BIGLAG_WQX: 'Big Lagoon Rancheria (California); ',
  BIGPINEPAIUTE:
    'Big Pine Paiute Tribe; Big Pine Paiute Tribe of the Owens Valley',
  BIGSANDY: 'Big Sandy Rancheria;',
  BIISHNIINI4: '',
  BISHOPPAIUTETRIBE: 'Bishop Paiute Shoshone Indians Tribe; ',
  BISHOP_PAIUTE_TRIBE_WQX: 'Bishop Paiute Tribe',
  BLCKFEET: '',
  BLMRW: 'Water Quality Monitoring Data',
  BLM_WRBBD: '',
  BLR: 'Blue Lake Rancheria (California); ',
  BLR_WQX: '(Tribal)',
  BLUERIVERWATERSHEDASSOCIATION: '',
  BMIC_WQX: 'Bay Mills Indian Community;',
  BMWM_TEST: 'TEST',
  BOISNETT_WQX:
    'Region 5 Wild Rice - Bois Forte/Nett Lake Band of Chippewa Indians',
  BOOMSNUBSITE_EA:
    'Data loaded by EA Engineering Inc. for the Boomsnub Superfund Site, Vancouver, Clark County, Washington.',
  BOUNTIFL_WQX: ' Superfund',
  BPMWQX:
    "Supporing EPA's Bonita Peak Mining District's (Superfund site) public data sharing efforts",
  BRB: 'Bear River Band of Rohnerville Rancheria (California);',
  BRIDGEPORTIC: 'Federally Recognized Tribe',
  BRIGHTON_WQX: 'Water Quality Monitoring Data',
  BROADRIVERNC: 'French Broad Riverkeeper monitoring',
  BTBAQUATIC_WQX: 'Grand Traverse band of Ottawa and Chippewa Indians; ',
  BTMUA: 'Drinking water provider',
  BTWTRFRM: 'Water Quality Monitoring Data.',
  BUNKER_FWS: 'Water Quality Monitoring Data',
  BUNKER_USGS: '',
  BUNKER_WQX: 'Water Quality Monitoring Data',
  BURNSPAIUTE: 'Burns Paiute Tribe;',
  BURNSPAIUTE123: 'Burns Paiute Tribe; ',
  BVR: '(Tribal)',
  BXA: 'Volunteer Monitoring Group',
  CABAZWQ32: 'Cabazon Band Of Mission Indians; ',
  CABEACH_WQX: 'California Beach Monitoring Data',
  CADDONATION_WQX: 'Caddo Nation;',
  CADMUS: '',
  CADPR_WQX: 'Water Quality Monitoring Data',
  CADWR_WQX: 'Water Quality Monitoring Data',
  CAFRESNO_WQX: 'Water Quality Data',
  CALSWAMP_WQX: 'Water Quality Monitoring Data.',
  CALTRANS_WQX: '',
  CALWR_WQX:
    'DWR is responsible for the operation of the State Water Project, including the California Aqueduct.  DWR also monitors surface and groundwater at locations throughout California.',
  CAPECRD_WQX: 'Water Quality Monitoring Data',
  CARGILLMS_WQX: 'Cargill Meat Solutions (aka. Fort Morgan Beef Plant)',
  CATAWBA: ' (Tribal)',
  CATAWBARIVERKEEPER: 'Catawba Riverkeeper Foundation (CRF)',
  CA_BVR:
    'Big Valley Band of Pomo Indians of the Big Valley Rancheria, California; Tribal government',
  CA_SWRCB: '',
  CBMI_WQX: 'Cabazon Band of Mission Indians (California);',
  CBP_WQX: 'Chesapeake Bay Program (PRODUCTION Environment)',
  CBS: '',
  CC: '',
  CCAMP_WQX: 'Water Quality Data',
  'CCCE-WHSE': 'Cape Cod Cooperative Extension/Woods Hole Sea Grant',
  CCSCD: '',
  CCSHBWA: 'Crafts Creek Spring Hill Brook Watershed Association',
  CCSR: 'Cohasset Center for Student Coastal Research',
  CCUI_WQX: 'Cow Creek Umpqua Indians;',
  CCU_EQL: '',
  CCWC: "Coal Creek Watershed Coalition (CCWC) is 501(c)(3) non-profit organization. The mission of CCWC is to maintain, restore and enhance the environmental integrity of Crested Butte's local watersheds to ensure those local watersheds and habitats are of the highest possible quality necessary to support wildlife, aquatic life, and human life.",
  CCWF: 'Water Quality Data to promote sustainable natural resource management throughout the Clear Creek Watershed and serve as a model for the arid mountain west..',
  CDATRUST: '',
  CDATWATRES: 'Coeur dAlene Tribe Water Resources Department; ',
  CDOT: '',
  CEDARRANCH_WQX: 'Cedarville Rancheria',
  CEDEN: 'California State Water Resources Control Board',
  CENAB: 'US Army Corps of Engineers District',
  CENTREAL_WQX: '',
  CENWWEDH_WQX: 'Water Quality Data',
  CEPACBMI_WQX: '',
  'CFE-STS': '1143930, Save the Sound, Water Quality Monitoring',
  CGWPCF: 'Colorado',
  CHARLOTTEHARBOREC_WQX: '',
  CHATFLD_WQX: 'Water Quality Data',
  CHATTAHOOCHEERIVERKEEPER: 'Chattahoochee Riverkeeper',
  CHEHALIS_WQX: 'Confederated Tribes of the Chehalis Indian Reservation;',
  CHEMEHUEVI_WQX: 'Chemehuevi Indian Tribe; ',
  CHEROKEEMD: 'Colorado',
  CHEROKEE_WQX: 'Cherokee Nation (Oklahoma);',
  CHEYENNEWSD1: '',
  CHEYRIVR: ' (Tribal)',
  CHICKALOONNATIVEVILLAGE_WQX: 'Chickaloon Native Village;',
  CHIPCREE_WQX: '',
  CHNEPCHB_WQX: 'Water Quality Monitoring Data',
  CHNEPCHE_WQX:
    'This ORGID refers to data collected in the East Wall of Charlotte Harbor by the Coastal Charlotte Harbor Monitoring Network (CCHMN).  STORET upload was conducted by the Charlotte Harbor Environmental Center with funding from the SWFWMD.',
  CHNEPCHP_WQX:
    'This ORGID refers to data collected in Cape Haze by the Coastal Charlotte Harbor Monitoring Network (CCHMN).  STORET upload was conducted by the Charlotte Harbor Environmental Center with funding from the SWFWMD.',
  CHNEPCHW_WQX:
    'Charlotte harbor National Estuaries Program Water Quality Monitoring Data for the Charlotte Harbor West Wall Stratum',
  CHNEPEB_WQX: 'Water Quality Monitoring Data',
  CHNEPLLB_WQX:
    'This ORGID refers to data collected in Lower Lemon Bay by the Coastal Charlotte Harbor Monitoring Network (CCHMN).  STORET upload was conducted by the Charlotte Harbor Environmental Center with funding from the SWFWMD.',
  CHNEPMP_WQX: 'Water Quality Monitoring Data',
  CHNEPPIS_WQX: 'Water Quality Monitoring Data',
  CHNEPSCB_WQX: 'Water Quality Monitoring Data',
  CHNEPTCR_WQX: 'Water Quality Monitoring Data',
  CHNEPTMR_WQX:
    'This ORGID refers to data collected in the East Wall of Charlotte Harbor by the Coastal Charlotte Harbor Monitoring Network (CCHMN).  STORET upload was conducted by the Charlotte Harbor Environmental Center with funding from the SWFWMD.',
  CHNEPTPR_WQX:
    'This ORGID refers to data collected in the East Wall of Charlotte Harbor by the Coastal Charlotte Harbor Monitoring Network (CCHMN).  STORET upload was conducted by the Charlotte Harbor Environmental Center with funding from the SWFWMD.',
  CHOCNATWQX: 'Choctaw Nation;',
  CHRISJCHEN: '',
  CITYFTCO_WQX: 'Water Quality Data',
  CITYOFPG_WQX: 'Water Quality Monitoring Data.',
  CITYPUEBLO_WWD: 'Colorado',
  CLACKAMAS_SWCD: 'Current VolMon group',
  CLALLAMCODCD: '',
  CLALLAMCOUNTYDCD: '',
  CLALLAMCOUNTYEH_WQX: 'Clallam County Environmental Health Services',
  CLPWC: 'Volunteer Monitoring Group',
  CMCNRMI_WQX:
    'The Natural Resource Management (NRM) academic program at Colorado Mountain College offers an associate degree in Natural Resource Management.  Students are provided with the opportunity to work on real life environmental projects in class and through paid jobs with the NRM Field Institute. NRM has been involved in over 50 environmental projects partnering with the USFS, USGS, US BLM, USFWS, CPW, and numerous regional and local governments and organizations.',
  CMCPD:
    'The Cape May County Planning Department is the professional arm of the Cape May County Planning Board. The department is responsible for the day to day operations that carry out the functions of the Planning Board.',
  CMP_WQX: 'managed by DE Sea Grant',
  CNA: '',
  CNENVSER: 'Chickasaw Nation;',
  CNWQD: 'Comanche Nation Water Quality Department',
  COCHITIPUEBLO: 'Cochiti Pueblo; Cochiti Pueblo of New Mexico',
  COCOPAH_INDIAN: 'Cocopah Indian Tribe Environmental Protection Office;',
  'COE/ISU_WQX': '',
  COEOMAHA_WQX: 'US Army Corps of Engineers Omaha District',
  COK2014: "Contact Name: Carol O'Donnell-Kee",
  COKORG_WQX: '',
  COLO319: '',
  COLOSU: '',
  COLUMBIA_SWCD: 'Kari Hollander, Current VolMon group',
  CONCORDIA_COLLEGE: 'Concordia College (Minnesota)',
  CONFLUENCE: 'Confluence Compliance Companies, LLC',
  CONNRIVERCONSERVANCY: 'Connecticut River Conservancy',
  COOSWA: 'Volunteer Monitoring Group',
  COQUILLETRIBE_WQX: 'Coquille Indian Tribe;',
  COQUILLE_WA: 'Current VolMon group',
  CORIVWCH_WQX: 'Water Quality Monitoring',
  CORTINARANCHERIA_WQX: 'Cortina Rancheria Kletsel Dehe Wintun Nation',
  COYOTEVAL_WQX: 'Coyote Valley Tribal EPD;',
  CPNWATER: 'Citizen Potawatomi Nation;',
  CPRW: '',
  CRBC_WQX: 'Suzi Cloutier, Current VolMon group',
  CRITEPO_WQX: 'Colorado River Indian Tribes Environmental Office;',
  CRITFC_WQX: 'Nez Perce Tribe of Idaho',
  CRK_WQX: 'Lorri Epstein',
  CROWCRKS: '',
  CROWNATN: '',
  CRWA: 'Water Quality Monitoring Data',
  CRWC_WQX: 'Crooked River Watershed Council',
  CSAZ: 'City of Scottsdale, Arizona',
  CSC_WQX: '',
  CSH: 'New York',
  CSKTPESTICIDE_WQX: 'Confederated Salish and Kootenai Tribes; ',
  CSKTRIBE: '',
  'CSR_EPA_CWA-106': 'Cold Springs Rancheria; ',
  CSU_FISHERIESECOLOGYLAB: '',
  CTA_WQX: 'Craig Tribal Association;',
  CTCLUSI_WQX:
    'Confederated Tribes of the Coos, Lower Umpqua and Siuslaw Indians;',
  CTEPO_WQX: 'Cahuilla Band of Indians - Cahuilla Tribal Environmental Office',
  CTGR: 'The Confederated Tribes of Grand Ronde (Oregon);',
  CTSI_WQX: 'Confederated Tribes of Siletz Indians; ',
  CTUIR_WQX: 'Confederated Tribes of the Umatilla Indian Reservation;',
  CTVOLMON: 'CT DEEP Volunteer Water Monitoring Program',
  CT_DEP01_WQX:
    'This is the central agency for all water quality data in this system',
  CURRY_WP: 'Erin Minster - Current VolMon group',
  CUSP: 'CDSN - Coalition for the Upper South Platte',
  CVC: 'Conemaugh Valley Conservancy',
  CWLT_WQX: 'Cahto Water Lab testing; ',
  CWSC_WQX: '',
  CWSD_WQX: 'Water Quality Monitoring Data and and SPCURE member',
  DAUPHINCD_WQX: 'Dauphin County Conservation District',
  DCD: 'Dickinson Conservation District',
  'DCRBPI_ WQX': 'Dry Creek Rancheria Band of Pomo Indians;',
  DDEH_WQX: 'Water Quality Monitoring Data',
  DEER_CREEK: 'EPA Region 9; ',
  DELACIB: 'Delaware Center for the Inland Bays Water Monitoring Data',
  DELAWARENATION: 'Delaware Nation; Delaware Nation',
  DEMOTEST: 'Test Organization; ',
  DEMOTEST_WQX: 'Department of Natural Resources',
  DENTONWATERSHED_WQX: '',
  DIAL_CORDY_WQX: '',
  DOEE: 'Water Quality Monitoring Data for all the Waters in the state',
  DRBA: 'Dan River Basin Association',
  DRBC: 'Interstate River Basin Commission',
  DRMPWQX: 'Region 6 - ENIPC - Mescalero Apache Tribe',
  DRMS: 'Colorado Division of Reclamation, Mining and Safety (DRMS), Inactive Mines Program (IMP)',
  DRN: 'Delaware Riverkeeper Network',
  DUCKWATER: 'Duckwater Shoshone Tribe; ',
  DVSJ: "Death Valley Scotty's JCT; Death Valley Scotty's Junction, California",
  DWH_SCRIBE1082:
    'Surface water and sediment sampling collected in response to the BP Gulf of Mexico Oil Spill',
  EAENGINEERING_WQX: '',
  EBCI: '(Tribal)',
  EBR_WQX: 'City of Baton Rouge and Parish of East Baton Rouge',
  ECLS_WQX: 'Environmental and Chemical Laboratory Services ',
  'ECO-WNC': '',
  'ECOLOG&RESEARCH': 'Ecological Logistics & Research Ltd. ',
  ECU_CSI_COASTALPROCESSES: '',
  ECU_ECOL_ENGR: '',
  EFDELRBC_WQX: 'Effluent Data',
  ELISS: '',
  ELKVALLEYCA_WQX: 'Elk Valley Rancheria, California;',
  ELWHA1_WQX: 'Lower Elwha Klallam Tribe (Washington); ',
  ELWHAWQ1_WQX: '',
  EMAP_CS_WQX: 'Coastal',
  EMAP_GRE: '',
  EMSWCD: 'East Multnomah Soil and Water Conservation District',
  ENVIROB1_WQX: 'Colville Confederated Tribes (Washington);',
  EOR_WQX: '',
  'EPA-C_WQX': 'CBP (TEST/Staging Environment)',
  'EPA-EAID-R3_WQX': '',
  'EPA-WPD-R3_WQX': 'EPA Region 3 TMDL Program',
  EPAORD: 'EPA Office of Research and Development',
  EPAORD_WQX: 'EPA Office of Research and Development',
  EPAR2: 'US EPA Region 2 - Clean Water Division',
  EPAR2_USVIBAWQMP_WQX:
    'US Virgin Islands Beach Advisory Water Quality Monitoring Program',
  EPAR5_SLR_WQX: 'Sea Level Rise (SLR) and (http:///www.csc.noaa.gov/slr)',
  EPAREG6_WQX: 'US EPA, Region 6 Dallas, TX',
  EPASTAGINGD: 'NOAA Divers data migration review',
  EPATEST: '',
  EPATESTA_PAM: '',
  EPA_GLNPO:
    'Will be used to store the historical GLENDA data that will be added to the WQX in the future.',
  EPA_OCMA_R1: '',
  EPA_OCMA_R2: '',
  EPA_OCMA_R4: '',
  EPA_OCMA_R6: 'EPA Ocean and Coastal Monitoring Assessment',
  EPA_R2: 'EPA Region 2',
  EPA_R2_EXT: 'EPA Region 2 Volunteer Partners',
  EPA_R7_GRANT_WQX: 'Grantee groups in EPA Region 7',
  EPA_R7_WQX: 'U.S. Environmental Protection Agency',
  EPA_REGION_2: '',
  EPA_WPD_R3: '',
  EQUILIBRIUM: '',
  ERG: 'Eastern Research Group, Inc.',
  ERWC: '',
  ERWSD: 'Eagle River Water and Sanitation District',
  ESATR08_WQX: 'TechLaw/USEPA ESAT R08 Water Quality Data',
  ESTOO: 'Eastern Shawnee Tribe of Oklahoma; ',
  ESTO_WQX: '',
  ETEC: '',
  EXLSTREAM1: 'Appalachian Watershed & Stream Monitors (AWSM) program',
  FAEC: 'Water Quality Monitoring Data',
  FBUSER_WQX: 'Gros Ventre and Assiniboine Tribe (Fort Belknap Indian Res); ',
  FCPOTAWATOMI_WQX: '',
  FIIR: ' (Tribal)',
  FLASIOUX: '',
  FLO_SEP: 'City of Florence-Siuslaw estuary Partnership',
  FLO_URBAN: 'City of Florence-Urban Waters Grant; monitoring data',
  FLPRMRWS_WQX: 'Water Quality Monitoring Data',
  FMYN_WQX: 'Fort McDowell Yavapai Nation;',
  FOB: 'Volunteer Monitoring Group',
  FOBWV: 'non-profit conservation organization West Virginia',
  FOCW: 'Restore, preserve, and promote the outstanding natural qualities of the Cheat River watershed.',
  FONDULAC_WQX: '',
  FORTLWWTP: 'Colorado',
  FORTPECK: '',
  FOSCWQ_WQX: '',
  FOUNSD: 'Colorado',
  FPST: 'Fallon Paiute-Shoshone Tribe;',
  FRESHKILLSPARK: 'Freshkills Park',
  FRESHWATER_INSTITUTE: '',
  FRIENDS_BAY: '',
  FRWA: 'Farmington River Watershed Association',
  FSAWQP_WQX: '',
  FSCD: 'Freehold Soil Conservation District',
  FTBLKNAP: '',
  'FWC-CREMP_WQX':
    'Florida Fish and Wildlife Conservation Commission, Fish and Wildlife Research Institute',
  'FWC/FWRI_WQX':
    'Water Quality Monitoring Data: Florida Fish and Wildlife Conservation Commission Fish and Wildlife Research Institute',
  FWCLOCAL_WQX: 'Water Quality Monitoring Data',
  FWC_SGMP_WQX:
    'Water Quality Monitoring Data: entered by the Florida Fish and Wildlife Conservation Commission (Org ID FWC/FWRI)',
  FWC_WQMP_WQX:
    'Water Quality Monitoring Data: entered by the Florida Fish and Wildlife Conservation Commission (Org ID FWC/FWRI)',
  FWS_MATTAMUSKEET: '',
  GBMCASSOC2014: '',
  GBNERR: 'Great Bay National Estuarine Research Reserve Monitoring Data',
  GCWIN: '',
  GEC_WQX: 'Water Quality Monitoring Data',
  GEI: '',
  GEICON_WQX: 'Water Quality Monitoring Data',
  GGCWC: 'Volunteer Monitoring Group',
  GIALANDANDWATER: 'Green Iowa AmeriCorps',
  GILLIAM_SWCD: 'Volunteer Monitoring Group',
  GLC_WQX: '',
  GLEC: '',
  GLENDALE_WQX: 'Water Quality Monitoring Data',
  GLEON: 'GLEON Lake Observer mobile app data',
  GLIFWC: 'Great Lakes Indian Fish and Wildlife Commission',
  GNLK01_WQX: '',
  GPC5_WQX:
    'Grand Portage Band of Lake Superior Chippewa (Minnesota Chippewa Tribes)',
  GPELC: '',
  GPORTAGE_WQX: 'GRAND PORTAGE Band of CHIPPEWA INDIANS (MN); ',
  GRIC_WQX: 'Gila River Indian Community DEQ; Gila River Indian Community DEQ',
  GSWA: 'Great Swamp Watershed Association',
  GTBOCI_WQX: 'Grand Traverse Band; ',
  GTBWATER_WQX: 'Grand Traverse Band of Ottawa & Chippewa Indians;',
  GTC_WQX: 'Native Village of Georgetown Water Quality',
  GUAM: '',
  GWCO: 'Groundwater Colorado',
  HALEYALDRICH: '',
  HANALEI_WQX: 'Water Quality Monitoring Data',
  HANNAHWQ_WQX: 'HANNAHVILLE TRIBAL COMMUNITY;',
  HARBORWATCH_WQX: '',
  HAWRIVER03030002: 'Haw River Assembly',
  HAYWOOD_WQX: '',
  HBMI_WQX: ' (Tribal)',
  HDRINC_WQX: '',
  HEPD_WQX: '',
  HI301H_WQX: 'Water Quality Monitoring Datta',
  HIA_WQX: 'Water Quality Data',
  HIEPO_WQX: 'Water Quality Monitoring for TMDL Program',
  HIHAWEHWWTP: '',
  HOFSTRAUML: '',
  HOHTRIBE_WQX: 'Hoh Indian Tribe; ',
  HOOPERDOB_WQX: 'Hooper Lab, Dept. of Biology, Western Washington',
  HOOSIER: '',
  HOPI_WQX: 'Hopi Tribe Water Resources Program (Arizona);',
  HOPTERA_WQX: 'Hopland Band of Pomo Indians Tribal EPA; ',
  HO_CHUNK_WQX: '',
  HPUL1EPA_WQX: 'Habematolel Pomo of Upper Lake Envir. Dept.; ',
  HRF: 'Volunteer Monitoring Group',
  HRWRP_RA: 'Water Quality Monitoring Data',
  HSGMN_WQX: 'Groundwater Data',
  HUALAPAI: 'Hualapai; ',
  HUIWAIOLA_WQX: 'The Nature Conservancy - Honolulu',
  HVA: 'Housatonic Valley Association - Housatonic River Watershed',
  HVTEPA_WQX: '',
  HW: 'Peter Hayes, Current VolMon Group',
  IAAFO_WQX: '',
  IAPEST: '',
  IASNAPST_WQX: 'Water Quality Monitoring Data for all the Waters in the state',
  IDAGMN_WQX: 'Illinois Department of Agriculture',
  IDEQ_CDAOFFICE_WQX:
    'Water Quality Monitoring Data for all the Waters in the state',
  IDEQ_WQX: 'Idaho Dept of Environmental Quality',
  IDNRDFW: 'Water Quality Monitoring Data',
  IDWR: '',
  IEC: '',
  'IEC-NYNJCT': '',
  IHS: 'Indian Health Service',
  IIDFG: '',
  ILRIVERWATCH: 'Illinois RiverWatch Network',
  IL_EPA_WQX: '',
  INDECON: 'Industrial Economics',
  INSTOR_WQX: 'Indiana Department of Environmental Management',
  INTRMTN_WQX: 'Superfund',
  IOWACITY_WQX: '',
  IOWAGW_WQX: '',
  IOWAST_WQX:
    'Physical, chemical, and biological data from 45 wetlands in northern Iowa',
  IOWATER_WQX: '',
  IOWATROK_WQX: 'Iowa Tribe of Oklahoma',
  IRONMT_WQX: 'Water Quality Monitoring Data',
  IRWA: 'Ipswich River Watershed Association',
  ISDA_WQX: 'Idaho State Department of Agriculture',
  IWLA: 'Izaak Walton League - national conservation organization',
  JA: '',
  JAMUL_WQX: ' (Tribal)',
  JCPH_WQX: '',
  JICARILLAAPACHE:
    'Jicarilla Apache Nation; Region 6 Tribes of NM - ENIPCInc - Jicarilla Apache Nation',
  JRSIMPLOT_FMC: 'J.R. Simplot and FMC Corporation for Gay Mine',
  JSKTRIBE_WQX: ' (Tribal)',
  KARUKDNR_WQX: 'Karuk Tribe; Karuk Tribe Water Quality Program',
  KASHIA: 'Kashia Band of Pomo Indians of the Stewarts Point Rancheria;',
  KATRINA6_WQX: 'Water Quality Data',
  KATSPROJ_WQX: 'Water Quality Monitoring Data.',
  KAWNATON_WQX: 'Kaw Nation;',
  KBICNRD_WQX: ' (Tribal)',
  KBOPWQP: ' (Tribal)',
  KBS: 'Kansas Biological Survey',
  KENAI_NWR: '',
  KENAI_WQX: 'Non profit organization',
  KERBERCREEK: 'Kerber Creek watershed for BLM Natural Resource; ',
  KICKAPOO: '',
  KICKAPOO07: 'Kickapoo Tribe in Kansas;',
  KINGCOUNTY: '',
  KIOWA_WQX: 'Kiowa Tribe of Oklahoma; Kiowa Tribe of Oklahoma',
  KITSAPCHD_WQX: '',
  KLAMATHTRIBES_WQX:
    'Klamath Tribes Natural Resources Department; Protection of the natural-resource related rights guaranteed to the tribes in the treaty of 1864 is largely the responsibility of the Natural Resources Department. This department aids the Klamath Tribes mission by protecting preserving and enhancing natural resources.',
  KNA: '',
  KNRD_WQX: 'Kalispel Natural Resources Department Tribal (Washington);',
  KS_GEOWATER_CTR: '',
  KWMNDATA_WQX:
    'The Keystone Watershed Monitoring Network (KWMN) is an umbrella organization for volunteer monitors in Pennsylvania. The mission of the KWMN is to promote volunteer monitoring to protect and improve the quality of Pennsylvania watersheds.',
  KWO: 'Water Quality monitoring and wetland',
  KWO2017: 'Kansas Water Office',
  'KY-EPRIVIA': 'www.eprivia.com  Louisville, KY',
  LACITY: '',
  LADEQWPD_WQX: 'Statewide Water Quality Monitoring Network',
  LAJOLLA: 'La Jolla Band of Luiseno Indians; ',
  LAKELAND_WQX:
    'Water Quality Monitoring Sampling and Data keeping for city lakes.',
  LANECOUNCILOFGOVERNMENTS: '',
  LAWRENCEBROOKWW_WQX:
    "This is a group that monitors the Lawrence Brook Watershed chain of water bodies in Middlesex County NJ and includes South Brunswick, North Brunswick, East Brunswick, Milltown, and part of New Brunswick in it's sampling area.",
  LCBP: '',
  LCO106_WQX: 'Water Quality Monitoring Data.',
  LCOWIS_WQX:
    'Lac Courte Oreilles Band of Lake Superior Chippewa Indians of Wisconsin',
  LCWCD_WQX:
    'Lincoln Soil and Water Conservation District *Contact - Audrey Sweet',
  LDEQ319: 'Louisiana Department of Environmental Quality',
  LDFWATER2007: 'Water Quality Monitoring Data.',
  LEECHLAK_WQX: 'Leech Lake Band of Ojibwe;',
  LEIGHROCKS: 'Contact Name: Leigh Lager',
  LEVELOCK: 'Levelock Village Council;',
  LEWWTP_WQX: 'Water Quality Monitoring Data',
  LFGC: 'Colorado',
  LFMSDD: 'Colorado',
  LFVC: 'Lake Fork Valley Conservancy of the Gunnison River Valley -  Water quality data collected to assess historic mining impacts to water quality in Henson Creek and other tributaries to the Lake Fork of the Gunnison River',
  LFWS: 'Legacy Water Quality Monitoring Data for Lake Fork of the Gunnison River - LFWS reformed as LFVC in 2011',
  LHC: 'The Lake Hopatcong Commission is an independent State agency overseen by an 11-member board of Commissioners.  The Commission is responsible for conducting, managing and coordinating activities for the preservation, restoration and enhancement of Lake Hopatcong and its watershed.  Members of the Commission work as representatives of the lake community, and are dedicated to permanently preserving the natural, historical and recreational resources of the watershed for this generation and beyond.',
  LISICOS: 'Long Island Sound Integrated Coastal Observing System',
  LOCUS_WQX: 'Locus Technologies',
  LONGTOM_WC: 'Former VolMon group',
  LOSCOYOTESBANDOFCAHUILLACUPENO:
    'Los Coyotes Band of Cahuilla Cupeno Indians;',
  LOWERRARITANWATERSHED: '',
  LPBFSAVEOURLAKE: 'Lake Pontchartrain Basin Foundation',
  LPEPA106: ' (Tribal)',
  LPPSR_WQX: 'Lone Pine Paiute-Shoshone Reservation; ',
  LQWA: 'Lake Quinsigamond Watershed Association',
  LRBOI_WQX: '',
  LSFOBLM: '',
  LSIOUX_WQX: '',
  LSUAGBG_WQX: 'LSU AgCenter Botanic Gardens at Burden',
  LSWCD_WQX: 'Audrey Sweet, Current VolMon group',
  LTBBWATR_WQX: '',
  LTENV_WQX: '',
  LUMMINSN_WQX: 'LummiNation (Washington);',
  LWRBRULE: '',
  MAKAH_WQX: 'Makah Tribe;',
  MALHEUR_WC: 'Current VolMon group',
  MAMIN_WQX: 'USEPA; ',
  MANZANITA: 'Manzanita Band of the Kumeyaay Nation; ',
  'MARITIME-PLANNING-WQX': '',
  MARSHALL_WQX: 'Marshall University',
  MASSBAYS: '',
  MASSBAYS01: 'Massachusetts Bays National Estuary Program',
  MASSDEP: 'Massachusetts Department of Environmental Protection (MassDEP)',
  MATTOLERESTORATIONCOUNCIL: 'Water Quality Monitoring Data',
  MATTOLE_SALMON: '',
  MAULFOSTER_WQX: '',
  MAWRRC_WQX: 'Massachusetts Water Resources Research Center',
  MAWRWMP:
    'Monitoring of physical, chemical and biological attributes of the Westfield River and some of it tributaries',
  MA_DEP: 'Division of Watershed Management (DWM)',
  MBCI_OEP: '',
  MBMG_WQX:
    'The MBMG_WQX organization is for data collected and stored by the Montana Bureau of Mines and Geology.',
  MCD1913FLOOD: '',
  MCHD: '',
  MCNCREEK_WQX: '',
  MCPH_WQX: 'Mason County Public Health',
  MCWCC_WQX: '',
  MDC: '',
  MDDNR:
    'The Department of Natural Resources leads Maryland toward a sustainable future for our environment, society, and economy by preserving, protecting, restoring, and enhancing natural resources. The data represent key measures of water and habitat quality for living resources such as fish, crabs and oysters. The information is used to guide the restoration of the Chesapeake Bay, its tributaries, and Coastal Bays by identifying specific problems and evaluating the success of management initiatives.',
  MDEDAT01_WQX:
    'Technical and Regulatory Services Administration Data  from HMI sampling',
  MDEDAT03_WQX:
    'Primarily Toxics data used for TMDL development and water quality assessment.',
  MDEDAT05_WQX:
    'contains  MBSS Data etc., Core Trend Benthic input by MDE  and DNR',
  MDEDAT06_WQX:
    'Quantitative Analyis section Data, miscellaneous data that MDE aquired.',
  MDEDAT07_WQX:
    "The State monitors fecal coliform levels as a requirement of the National Shellfish Sanitation Program (NSSP). The Department of the Environment is responsible for classifying and managing Maryland's shellfish harvesting areas. The goal of shellfish harvesting area classification and management is to provide maximum utilization of shellfish resources and to reduce the risk of shellfish-borne illness",
  MDEDAT08_WQX:
    'The BEACH Act was signed into law October 10, 2000. The Beach Act addresses coastal recreational waters and public health risk associated with human contact with potential pathogens in sewage-contaminated waters.',
  MDEDAT09_WQX:
    'Data used for Risk Assessment. Primarily fish, shellfish and crab  tissue contaminant information.',
  MDEDAT10_WQX: '',
  MDEQ_MPDES_WQX:
    'The MDEQ_MPDES_WQX organization is for data associated with MPDES permits.',
  MDEQ_REM_WQX:
    "The MDEQ_REM_WQX organization is for data associated with DEQ's Remediation Division.",
  MDEQ_WQ_WQX:
    "The MDEQ_WQ_WQX organization is for data collected by DEQ's Water Quality Planning Bureau (WQPB).",
  MDE_EASP: 'Environmental Assessment and Standard Program Data',
  MDE_FIELDSERVICES_WQX:
    'Data collected by MDEs field office for different surveys, mostly TMDL initiatives.  It mainly consists of physical parameters, chlorophyll, nutrients, BOD and sediments.  There are some coliform (bacteria) data; also, elements associated with mining.',
  MDE_FSP: '',
  MDE_STORMWATER: 'MDE Stormwater data',
  MDE_TMDL: 'TMDL Technical Development Program data',
  MDE_WQPR:
    'Water Quality Monitoring  Data,Maryland Department of the Environment 319 Program',
  MDNR: '',
  MDO: '',
  MDPOINTSOURCE:
    "Discharge monitoring reports (DMRs) and monthly operating reports (MORs) for the 58 major WWTPs, 215 minor WWTPs, and 10 major industrial point sources within the State of Maryland and are stored in MDE's point source database.  This data set contains results for nutrients such as phosphorous and nitrogen that may impact water quality in the Chesapeake Bay.",
  MEC: '',
  MEDEP_WQX: 'Maine Dept of Env Protection.',
  MEIYINWUSUNYPLATTSBURGH: '',
  MENOM_WQX: '',
  MERI: 'Our mission is to provide the scientific community, policy makers, and the public with the knowledge and predictive understanding necessary to conserve, protect, and manage the District ecosystems and the services they provide.',
  MERRIMACK_RIVER_WATERSHED_WQX: '',
  MESKWAKI_DNR: 'Meskwaki Department of Natural Resources;',
  METC_WQX: 'Metropolitan Council (Minnesota)',
  MHA_NATN: ' (Tribal)',
  MHA_WQX: 'Mandan, Hidsata, and Arikara tribal lands (MHA Nation); ',
  MIAMITRIBEOFOKLAHOMA: ' (Tribal)',
  MIDCOWATERSHED:
    'The Middle Colorado Watershed Council (MCWC) is a 501c(3) nonprofit organization whose mission is to evaluate, protect and enhance the health of the Middle Colorado River Watershed through the cooperative effort of watershed stakeholders',
  MIDDLEDESCHUTES_WC: 'Volunteer Organization',
  MIDDLESPRINGWATERSHED: '',
  MIDDLETOWNUPCW_WQX: 'Middletown Rancheria Environmental Center ; ',
  MIDEWIN:
    'United States National Grassland operated by the United States Forest Service',
  MIDNITE_2: '',
  MILLERCOORS: 'MillerCoors is a member of SPCURE',
  MITCR_WQX:
    'Mechoopda Indian Tribe of Chico Rancheria; Mechoopda Indian Tribe of Chico Rancheria',
  MIT_WQX: ' (Tribal)',
  MKIESER: '',
  MLBO_DNR_WQX: '',
  MNDA_PESTICIDE: 'Statewide monitoring, non-facility',
  MNDNR_AGW:
    'Minnesota Department of Natural Resources - Ambient Groundwater Program',
  MNISOSE07:
    'Mni Sose Itnertribal Water Rights Coalition; Water Quality Monitoring Data',
  MNPCA: 'Statewide ambient surface water monitoring, non-facility',
  MNPCA1_WQX: 'Water Quality Monitoring Data for all the Waters in the state',
  MNPCAB_WQX: 'Water Quality Monitoring Data for all the Waters in the state',
  MNPCA_AGW: 'Statewide ambient groundwater monitoring, non-facility',
  MNPCA_BIO:
    'Statewide ambient surface water monitoring to support the biological monitoring program, non-facility',
  MOAPA_WQX: 'the Moapa Band of Pautes;',
  MONT_DEQ_WQX:
    'The MONT_DEQ_WQX organization is a static, historic dataset with the majority of data originating from the Storease database.',
  MONT_PPL_WQX:
    'The MONT_PPL_WQX organization is for data collected by PPL Montana.',
  MOORETOWNEPO: 'Mooretown Rancheria water quality monitoring',
  MORONGO1_WQX: '',
  MPSLML: 'Marine Pollution Studies Lab at Moss Landing Marine Laboratories,',
  MRC: 'Monitoring coalition w/ an approved QAPP through the SC Development of Health and Environmental Control',
  MRSENVMB_WQX: 'NPDES Monitoring Data',
  MRWA: 'Musconetcong River Watershed Association',
  MSI: 'Mountain Studies Institute (MSI) is an independent not-for-profit mountain research and education center established in 2002 in Silverton, Colorado. MSI develops science that people can use to address environmental issues facing the San Juan Mountains. We conduct and facilitate research, provide educational opportunities and internships, and conduct environmental monitoring. We connect scientists and stakeholders across the San Juan Mountain region to go beyond scientific inquiry to the meaning',
  MSU: '',
  MSUEXT_GC_WQX: 'Montana State University Extension - Gallatin County',
  MSWCD_WQX:
    'Malheur Soil and Water Conservation District (SWCD) *Contact - Gary Faw',
  MT305B_SECONDARYDATA:
    'The MT305b_SecondaryData organization is for data submitted to the Montana Water Quality Planning Bureau during calls for "all existing and readily available water quality-related data and information" per the federal Clean Water Act and 40 CFR 130.7 (5).  These data were not collected by or explicitly for Montana DEQ\'s WQPB.',
  MTNWE:
    'The MTNWE organization is for data collected and managed by NorthWestern Energy.',
  MTVOLWQM_WQX:
    'The MTVOLWQM_WQX organization is for data collected by volunteer organizations, groups, or individuals that are not operating under a DEQ approved QAPP/SAP.',
  MTWTRSHD_WQX:
    'The MTWTRSHD_WQX organization is for data collected externally from DEQ, but using grant monies such as 319 or 106 or managed under a DEQ approved QAPP/SAP.',
  MUSCOGEE_CREEK: 'Muscogee Creek Nation; ',
  MUSCONETCONGORG_WQX: '',
  MWA1: 'The Musconetcong Watershed Association (MWA) is a non-profit organization incorporated in 1992 to protect and enhance the Musconetcong River and its related resources. MWA members are part of a network of individuals, families and organizations that care about the Musconetcong River and its watershed.',
  MWRDSTOR_WQX:
    'Water Quality Monitoring: 100 East Erie Street, Chicago, IL 60611  (312) 751-5600',
  MWRD_WQX: 'Water Quality Monitoring Data and SPCURE member',
  MYRWA: 'Water Quality Monitoring Data',
  NALMS: 'Volunteer',
  NAMBEPBLO_WQX: 'Pueblo of Nambe, NM',
  NANTICOKEWTRALL_WQX: '',
  NARSTEST: '',
  NARS_WQX: '',
  NCADH: 'North Carolina Aquatic Data Hub',
  NCUSGS: '',
  NCWA_WQX: 'North Coast Watershed Association',
  NCWCD: 'Water Quality Monitoring Data.',
  NCWQR: '',
  NEIARCD_WQX: '',
  NEIWPCC: '',
  NEWRIVERCONSERVANCY: 'New River Conservancy',
  NEZPERCETRIBE_WQX:
    'Nez Perce Tribe; Water Resources Department WQX Data Exchange',
  NFRIA: 'Water Quality Monitoring Data',
  NIAMLARB1_WQX: '',
  NISQUALLY: 'Nisqually Water Quality; ',
  NIT_WQX: 'Narragansett  Indian Tribe',
  NJCSO: 'NJCSO Group',
  NJDEPNJWAP: 'NJDEP, NJ Watershed Ambassador Prog',
  NJDEPRS: 'NJDEP Reference Sites',
  NJDEPVMG: 'NJDEP Volunteer Monitoring Group',
  NJDEP_AMERICORPS:
    'The New Jersey Watershed Ambassadors Program is a community-oriented AmeriCorps environmental program designed to raise awareness about watershed issues in New Jersey. Watershed Ambassadors monitor the rivers of New Jersey by visual and biological volunteer monitoring program. The members also train community volunteers and teach them to use these two volunteer monitoring techniques.',
  NJDEP_BB: '',
  NJDEP_BB_TEST: '',
  NJDEP_BEARS:
    "The purpose of the Bureau of Environmental Analysis and Restoration (BEAR) will be to support the Division's mission through the development of technical tools for implementation by the Division. This will be accomplished through the completion of Established TMDLs and the revision and development of a Stream Corridor Ordinance, Well Head Protection Ordinance and an Enhanced MS4 Ordinance.",
  NJDEP_BFBM:
    "The Bureau is responsible for monitoring the ambient conditions of the state's fresh and ground water resources. This monitoring includes regular statewide sampling through of 115 surface water monitoring stations, 820 benthic macroinvertebrate stream monitoring stations, 100 fish assemblage stream monitoring stations, and 150 ground water stations.",
  NJDEP_BMWM:
    "The Bureau is responsible for water quality monitoring used to classify approximately 700,000 acres of marine and estuarine shellfish waters, In this regard, approximately 15,000 ambient water samples are collected yearly from a 4,000 station sampling network. All of these samples are analyzed at the Bureau's southern regional DEP laboratory. In addition, the bureau oversees both the Beach Monitoring and the Clean Shores programs.",
  NJDEP_BSWP:
    'The Bureau of Surface Water Permitting regulates facilities discharging domestic and industrial wastewater directly into surface waters of the state as part of the NJPDES program.\nPermittees include various industries, federal, state, county, and municip',
  NJDEP_BWQSA:
    'The Bureau of Water Quality Standards and Assessment is responsible for water quality assessments of all waters of the State and the New Jersey Integrated Water Quality Monitoring and Assessment Report.',
  NJDEP_DSREH:
    "The Division of Science, Research and Environmental Health (formerly the Office of Science and previously the Division of Science, Research and Technology) is the New Jersey Department of Environmental Protection's (DEP) primary scientific research and technical support unit. The role of this division, through its studies, evaluations and monitoring efforts, is to provide DEP with a sound technical foundation upon which to base the department's policy and regulatory decisions.",
  NJDEP_OS_TEST: 'Contact Name: Tom McKeon',
  NJDEP_PESTICIDES: '',
  NJHDG:
    'Nine northeastern NJ wastewater treatment agencies working collaboratively on water quality issues in the NY/NJ Harbor Estuary.',
  NJMC: '',
  NJPC: 'The New Jersey Pinelands Commission is an independent state agency whose mission is to "preserve, protect, and enhance the natural and cultural resources of the Pinelands National Reserve, and to encourage compatible economic and other human activities consistent with that purpose."',
  NJRCD:
    'The Resource Conservation and Development Program was initiated in 1962 to help people care for and protect their natural resources to improve the economy, environment, and living standards of an area.  Our mission is to facilitate the transition to sustainable use and protection of human and natural resources in the region through partnerships, education, and innovation.',
  NJWAP: '',
  NJWSA: '',
  NJ_MSU: '',
  NKUWATER_WQX:
    'Water Quality Monitoring Data:Consortia working with local groups including the Licking Watershed Watch.',
  NNB: 'Volunteer Monitoring Group',
  NNEPA: 'Navajo Nation; ',
  NOAA_CORALREEFS_WQX: '',
  NOMEESKIMO_WQX: 'Nome Eskimo Community; Nome Eskimo Community',
  NOOKSACK_WQX: ' (Tribal)',
  NORMANDEAUASSOC: 'Normandeau Associates Inc.',
  NOTTAWHURON_WQX: ' (Tribal)',
  NRTHCHEY: 'Environmental Protection Department',
  NRWA_WQX: 'Water Quality Monitoring Data',
  NRWC: '',
  NSEA: 'The Nooksack Salmon Enhancement Association is a community based nonprofit dedicated to restoring wild salmon populations in Whatcom County.',
  NSQS: 'blah',
  NSRWA: 'North and South Rivers Watershed Association',
  NTEMPLE_WQX: 'Water Quality Data',
  NTHRNUTE: '',
  NVC_WQX: 'Native Village of Council; Native Village of Council',
  NVEPA_WQP: 'Navajo EPA Water Quality Program ; ',
  NWIFC_WQX: 'Northwest Indian Fisheries Commission; ',
  NWRSFWS_WQX: '',
  OARS: 'OARS - For the Assabet Sudbury & Concord Rivers',
  OCC: 'The OCC organization is for data associated with the Otter Creek watershed, specifically with the Otter Creek Coal area.',
  OCDWEP_WQX: 'Onondaga County Department of Water Environment Protection',
  OESERLSCA_WQX:
    'Region 10: Oeser Property, Little Squalicum Creek Area, Bellingham, WA',
  OGLALAST: ' (Tribal)',
  OHDDAGW:
    'Ambient water quality program in OH Division of Drinking and Ground Waters',
  'OH_KY_IN-WSC': 'Continuous Water Quality Data',
  OISC_WQX:
    'Office of Indiana State Chemist has regulatory authority for use of pesticides, nutrients, feed, and seeds in Indiana',
  OKCONCOM_WQX: 'Water Quality Monitoring Data for all the Waters in the state',
  OKCORCOM_WQX: 'Water Quality data submitted by ODEQ',
  OKDAFF_WQX: 'Water Quality data submitted by ODEQ',
  OKDEQ_WQX: '',
  'OKWRB-GMAP_WQX': 'OKWRB use internally for groundwater monitoring',
  'OKWRB-LAKES_WQX': '',
  'OKWRB-STREAMS_WQX':
    'Oklahoma Water Resources Board Streams and Rivers Monitoring',
  OKWRB_WQX: 'Water Quality',
  OLMS: "Non-profit dedicated to the protection of Ohio's lakes and their watershed",
  ONEIDA_WQX: 'Oneida Nation',
  OOPBLO: 'Ohkay Owingeh Pueblo; Pueblo of Ohkay Owingeh, NM',
  ORDNRMRLSTD_GI:
    'USEPA Office of Research and Development, National Risk Management Research Laboratory',
  OREGONDEQ: '',
  OSAGENTN: 'Osage Nation Environmental and Natural Resources Dept; ',
  OSAGENTN_WQX: 'Osage Nation; Osage Nation',
  OST_SHPD: '',
  OST_SHPD_TEST: '',
  'OSU-OOIEA': "Ocean Observatories Initiative's Endurance Array",
  OTIE: '',
  OTTAWATRIBEOFOK: '',
  OVIWC: '',
  O_MTRIBE_WQX: '',
  P4_PRODUCTION_IDAHO: 'P4 Production LLC, Soda Springs Plant, Idaho',
  PADDLEFISH: '',
  PADEP319_WQX: 'Department of Environmental Protection 319 Program',
  PADEPLAKE_WQX: '',
  PALABAND: 'Pala Band of Mission Indians; Pala Band of Mission Indians',
  PALERMOWELLFIELD_CH2M: 'Palermo Wellfield Superfund Site water quality data',
  PALERMOWELLFIELD_WQX: '',
  PASSAMAQUODDYSIPAYIKENV: 'Passamaquoddy Tribe at Pleasant Point; ',
  PATCMON_WQX: 'Potomac Appalachian Trail Club Volunteer Monitoring - VA,MD; ',
  PAUMATRIBE: 'Pauma Band of Mission Indians;',
  PBDNR: 'Pokagon Band of Potawatomi Indians Department of Natural Resources;',
  PBWC_WQX: 'Powder Basin Watershed Council *Contact - Christopher Morris',
  PCCB_WQX: 'Polk County Conservation Board (Polk County, Iowa)',
  PCSWD: '',
  PCWA: 'Pompeston Creek Watershed Association',
  PDHP7L: 'Park District of Highland Park',
  PECHANGA_WQX: 'Pechanga Band of Luiseno Indians',
  PENOBSCOTINDIANNATIONDNR: ' (Tribal)',
  PGSTNATR_WQX: ' (Tribal)',
  PICAYUNERANCHERIACWA106: 'Rancheria of the Chukchansi Indians; ',
  PICEANCE_LDR: 'Piceance Basin Colorado',
  PICURIS_PUEBLO: 'Picuris Pueblo',
  PIIC_WQX: '',
  PIMA_AZ: '',
  PINOLEVILLEPOMONATION_WQX: 'Pinoleville Pomo Nation;',
  PLYMOUTHDMEA: 'Plymouth Department of Marine and Environmental Affairs',
  PNDECS_WQX: 'Pawnee Nation Dept of Environmental Conservation and Safety;',
  POARCHCRK_WQX: 'Poarch Band of Creek Indians;',
  POLSWATER_WQX: 'Pueblo of Laguna',
  POMO989_WQX: ' (Tribal)',
  PORTGRAHAM: 'Water Quality Monitoring',
  PORTLANDHARBORRISS: 'City of Portland',
  PPNPROGRAM: 'Pinoleville Pomo Nation;',
  PRAIRIEBAND: 'Prairie Band Potawatomi Nation;',
  PRCI_WQX: 'Picayune Rancheria of the Chukchansi Indians; ',
  PRCWA:
    'Non-profit organization dedicated to promoting the restoration and protection of the waters and environment of the Parker River and Plum Island Sound Watersheds',
  PREEM: '',
  PREP: 'Piscataqua Region Estuaries Partnership',
  PREQB_GW_WQX: 'Water Quality Monitoring Data for all the Waters in the state',
  PRTWQX: 'Pit River Tribe; ',
  PR_BEACH_WQX:
    'The purpose of the Puerto Rico Environmental Quality Board is the Environmental Protection of pollution problem in Puerto Rico',
  PR_COAST_WQX: 'Water Quality Monitoring Data for all the Waters in the state',
  PR_LAKES_WQX: '',
  PR_RIVER_WQX: 'Water Quality Monitoring Data',
  PSUCLR: '',
  PTI_ITS_WQX: 'Passamaquoddy Tribe of Indians, Indian Township Reservation;',
  PTMSC: 'Non-profit marine science education',
  PUEBLOISLETA: 'Pueblo of Isleta;',
  PUEBLOJEMEZ: 'Pueblo of Jemez',
  PUEBLOOFTESUQUE: 'Region 6 NM - Pueblo of Tesuque',
  PUEBLOWMD: 'Colorado',
  PUEBLO_POJOAQUE: 'Pueblo of Pojoaque Environment Department',
  PUEBLO_SANTAANA: '',
  PUJ: '',
  PUR_WQX: 'Joe Carnes, Current VolMon group',
  PUYALLUP_WQX: ' (Tribal)',
  PYRAMIDLAKE: 'Pyramid Lake Paiute Tribe;',
  QIN_WQX: ' (Tribal)',
  QTEO_WQX: '(Tribal)',
  QUAPAWTR_WQX: 'Quapaw Tribe of Oklahoma; ',
  QUECHAN_WQX: 'Quechan Indian Tribe;',
  QUILEUTE_WQX: '',
  QVIR: 'Quartz Valley Indian Reservation;',
  QVIR_WQXRETIRED:
    'Quartz Valley Indian Reservation - Env. Dept. (California);',
  R0910: '',
  R10BLACKBUTTEMINE:
    'The Black Butte Mine is a former mercury mine located in southern Lane County in the Coast Fork Willamette River Basin.',
  R10BOOMSNUB:
    'Boomsnub -  BOC Gases Superfund Site Data 1987-2013 Loaded by EPA Region 10',
  R10BUNKER:
    "Bunker Hill Mining and Metallurgical Complex and Coeur d'Alene Basin, Kellogg, ID",
  R10DUWAMISH:
    "The Lower Duwamish Waterway Superfund site is a 5.5 mile stretch of the Duwamish River that flows into Elliott Bay in Seattle, Washington. The waterway is flanked by industrial corridors, as well as the South Park and Georgetown neighborhoods. The site was added to EPA's National Priorities List in 2001. Pollutants in the sediments include polychlorinated biphenyls or PCBs, dioxins/furans, carcinogenic polycyclic aromatic hydrocarbons or cPAHs, and arsenic.",
  R10ELKHEADMINE: 'Elkhead Mine Soil Sampling, Douglas County OREGON',
  R10ERU10EK: '',
  R10MIDNITE:
    'Midnite Mine is an inactive open-pit uranium mine on the Spokane Indian reservation in eastern Washington; potential threats include elevated levels of radioactivity and heavy metals and radionuclides mobilized in acid mine drainage.',
  R10NPDES: 'Monitoring data collected by or for NPDES-permitted facilities.',
  R10NWPIPEANDCASING:
    'Northwest Pipe and Casing Company-Hall Process Company Superfund Site, Milwaukie, OR; RI and Post-RI data set assembled by Weston and delivered to EPA in Access97 format, date range 7/1/88 - 4/6/99.',
  R10OEA:
    'Various studies performed by or for US EPA Region 10, Office of Environmental Assessment',
  R10PORTLANDHARBOR:
    'Portland Harbor is located in and along the Willamette River in Portland, Oregon. More than a century of historical industrial use has resulted in Willamette River sediments being contaminated with many hazardous substances, such as heavy metals, polychlorinated biphenyls (PCBs), polynuclear aromatic hydrocarbons (PAH), dioxin/furans, and pesticides. The investigation area currently extends from the Columbia Slough to the Fremont Bridge.',
  R10SUMASMOUNTAIN:
    'Investigation of asbestos contamination; sampling along Swift Creek and the Sumas River, near the town of Nooksack, in Whatcom County, Washington.',
  R10SUPERFUNDHISTORICAL: 'EPA Region 10 Superfund Historical Data',
  R10UPPERCOLUMBIA:
    'Remedial Investigation and Feasibility Study (RI/FS) of hazardous waste contamination in the Columbia River from the U.S./Canada border to the Grand Coulee Dam. River and lake sediment contamination includes heavy metals such as cadmium, copper, lead, mercury and zinc, and dioxins and furans.',
  R10YROADLANDFILLS:
    'Y-Road Landfills Superfund Site Inspection Groundwater Monitoring Data, Bellingham, WASHINGTON, May 2004',
  R2_LAB_WQX: '',
  R4ATHENS_WQX: '',
  R4WPD: '',
  R8MONTWQ:
    'The R8MONTWQ organization is for data collected under EPA Region 8 projects.  The EPA Montana office is the "owner" of this organziation.',
  R9VOL_WQX: 'Water Quality Monitoring Data',
  RAMONA: 'Ramona Band of Cahuilla; ',
  RCA: '',
  'RCE WRP':
    'The Rutgers Cooperative Extension (RCE) is an integral part of the School of Environmental and Biological Sciences, the New Jersey Agriculture Experiment Station (NJAES), and Rutgers, The State University of New Jersey.  RCE focuses on issues and needs relating to agriculture and the environment; management of natural resources; food safety, quality, and health; family stability; economic security; and youth development.',
  RCESLM:
    'Ramsey County Environmental Services, Lake Management Surface Water Quality',
  REDCLIFF_WQX: '',
  REDDINGRANCHERIA_WQX: 'Redding Rancheria Tribe; ',
  REDLAKE_WQX: '',
  REVIVETHESANJOAQUIN_WQX: '',
  RFC: 'Founded in November 1996, Roaring Fork Conservancy is the watershed conservation organization in the Roaring Fork Valley that brings people together to protect our rivers. As an independent, not-for-profit 501(c)3 organization our mission is to inspire people to explore, value, and protect the Roaring Fork Watershed. From Aspen to Glenwood Springs, Meredith to Marble, Roaring Fork Conservancy is focused on: water quantity and water quality.',
  RGHRP: '',
  RHA: 'Raritan Headwaters Association',
  RIDEM: 'RIDEM',
  RITA6_WQX: 'Hurricane Rita Water Quality Data',
  RIVERKEEPER:
    'Riverkeeper is a member-supported watchdog organization dedicated to defending the Hudson River and its tributaries and protecting the drinking water supply of nine million New York City and Hudson Valley residents.',
  RM11E_SUPRIFS:
    'This data was collected as part of the Supplemental Remedial Investigation/Feasibility Study (RI/FS) conducted along the east side of the Willamette River between approximately River Mile (RM) 10.9 and RM 11.6 (referred to as RM11E) in Portland, Oregon. The results were uploaded by GSI Water Solutions, Inc. on behalf of the RM11E Group,  including Cargill, Inc., CBS Corporation, the City of Portland, DIL Trust, Glacier Northwest, Inc., and PacifiCorp.',
  ROBINSONRANCHERIAENVIRONMENTAL: 'Robinson Rancheria Environmental Center; ',
  ROSEBUDSIOUXTRIBE: 'Rosebud Sioux Tribe',
  ROUNDVALLEY: 'Round Valley Indian Tribes; Round Valley Indian Tribes',
  RREPA_WQX: 'Resighini Rancheria Environmental Protection (California);',
  RRK_WQX: 'Rogue Riverkeeper',
  RRWC_WQX:
    'Sarah Sauter, Current VolMon group, Includes Little Butte/Upper Rogue and Middle Rogue Watershed Council data from LASAR',
  RTI: 'http://www.rti.org/',
  RU_MUSC: 'Water Quality Monitoring Project for Musconetcong River',
  RVCG: 'Greg Stabach, Current VolMon group',
  RVRPOMO: ' (Tribal)',
  SACFOXMO: 'Sac and Fox Nation of Missouri in Kansas and Nebraska;',
  SACWSD_WQX: 'Water Quality Monitoring Data',
  SAGIN01_WQX:
    'Saginaw Chippewa Planning Department (MI); Water Qulaity Monitoring Data.',
  SAINTVSD: 'Colorado',
  SALTCHUCK_WQX: '',
  SAMISHINDIAN_WQX: '',
  'SAN PASQUAL':
    'San Pasqual Band of Diegueno Indians (i.e. San Pasqual Tribe); ',
  SANBERNARDINONATIONALFOREST: '',
  SANCARLOSAPACHETRIBE: 'San Carlos Apache Tribe - EPA; ',
  SANDIAWQ_WQX: 'Pueblo of Sandia Water Quality Program (New Mexico)',
  SANFELIPE_WQX: 'San Felipe Pueblo, NM',
  SANILDEFONSODECP: '(Tribal)',
  SANMANUEL: 'San Manuel Band of Mission Indians; ',
  SANMATEORCD: 'San Mateo Resource Conservation District',
  SANPASQUAL_WQX: 'San Pasqual Band of Mission Indians; ',
  SANTACLARAPBLO: 'Pueblo of Santa Clara',
  SANTAROSA: 'Santa Rosa Rancheria; ',
  SANTEEWATER: 'Santee Sioux Nation of Nebraska;',
  SAUKSUIATTLE: 'Sauk-Suiattle Indian Tribe; ',
  SAULTSTEMARIE: ' (Tribal)',
  SBITENV_WQX: 'Shoaltwater Bay Tribe (Washington);',
  SBMWA: 'Stony Brook-Millstone Watershed Association',
  SBS: '',
  SBWA: 'South Branch Watershed Assoc',
  SBWA1: 'South Branch Watershed Association-WQDE version phone-908-782-0422',
  SBWC_WQX: 'Pat Welle, Current VolMon group',
  'SC&LRWC': '',
  SCCRK: 'South Carolina Congaree RiverKeeper',
  SCCWK: 'South Carolina Charleston WaterKeeper',
  SCDHSECOLOGY: '',
  SCEQ: '',
  SCI: '',
  SCWA: '',
  SDCKWMG_WQX: 'Water Quality Monitoring Data',
  SDDENR_WQX: 'Department of Natural Resources',
  SDGEO_WQX: 'Water Quality',
  SDJSA:
    'The Silverthorne/Dillon Joint Sewer Authority is a municipal wastewater treatment facility serving the Towns of Silverthorne and Dillon as well as the areas of Dillon Valley, Buffalo Mountain and Mesa Cortina.',
  SEATTLERIVER_WQX:
    'river sediment chemistry results collected for the City of Seattle.',
  SELDOVIA: 'Seldovia Village Tribe (SVT); ',
  SFBED_WQX: 'South Fork Band Environmental Department',
  SFNOES_WQX: ' (Tribal)',
  SHELLYAB_WQX: 'Water Quality Monitoring Data.',
  SHOPAITR_WQX: 'Shoshone-Paiute  Tribes (Nevada); ',
  SHOSHONE_BANNOCK: 'Shoshone Bannock Tribes',
  SHOSHONE_BANNOCK_WQX: 'Shoshone-Bannock Tribes; ',
  SIR_WQX: 'Susanville Indian Rancheria (SIR);',
  SITC_SF: 'Swinomish Tribal Shellfish data',
  SIUSLAW: 'Kyle Terry, Current VolMon group',
  SIUSLAW_WQX: 'Ecotrust; ',
  SJBEP:
    'San Juan Bay Estuary Program: a 501c3 nonprofit corporation for the National Estuary Program.',
  SJICD_WA:
    'Resource data to provide landowners and residents with technical and financial assistance to meet regional natural resource conservation goals',
  SJLWT: '',
  SKAGITCOUNTY_WQX: 'Surface Water Quality Monitoring Program',
  SKAGITWG_WQX:
    'Skagit River Watershed Grant (TNC, SRSC, WWAA)  - Washington; Water Quality Monitoring Data for the Sauk-Suiattle Indian Tribe and the Swinomish Indian Tribal Community',
  SKOKDATA_WQX: ' (Tribal)',
  SKYHORSETECH:
    'Surface vehicle collecting water sampling data on the Raritan River in NJ. Partnering with the Lower Raritan Watershed.',
  SLCOWS: 'Salt Lake County Watershed',
  SLPWA: 'Water quality monitoring for Seneca Lake, New York',
  SLU_WQX: 'EPA Urban Waters Grant - St. Louis University',
  SMENVIRONMENTAL_WQX: 'San Manuel Band of Mission Indians; ',
  SMIE: 'Water Quality Monitoring Data',
  SMSCGOV_WQX: 'Shakopee Mdewakanton (MN)',
  SMWC: 'The San Miguel Watershed Coalition is a 501(c)(3) non-profit organization, governed by a 10 person board. The San Miguel Watershed Coalition was formed around 1998, to enable a collaborative forum for all residents, businesses, landowners, land managers and non-profit organizations to discuss and influence the future of the watershed.',
  SNEPO_WQX: 'Seminole Nation; Seminole Nation',
  SNOQUALM_WQX: '',
  SNSA_WQX: 'Water Quality Monitoring Data',
  SOBOBA_WQX: 'Soboba Band of Luiseno Indians;',
  SOKAOGON_WQX: '',
  SOUTHSANTIAM_WC: 'Eric Anderson, Current VolMon group',
  SOUTHUTE: '',
  SOU_WQX: 'Southern Oregon University',
  SPC: 'Volunteer Monitoring Group',
  SPIRITLK: ' (Tribal)',
  SQUAXIN: '',
  SRBCI: 'Santa Rosa Band of Cahuilla Indians water quality',
  SRCD: 'Biomonitoring Program that monitors chemical, physical and biological aspects of local creeks',
  SRMTAKNY_WQX: 'St. Regis Mohawk Tribe (New York); ',
  SRMTWRP_WQX: 'St. Regis Mohawk Tribe Environment Div Water Resource Progrm;',
  SRPMIC: '',
  SRPMIC_WQX: 'Salt River Pima-Maricopa Indian Community;',
  SRRTFF: 'Reporting of toxic compounds in the Spokane River',
  SRR_WQX: 'Smith River Rancheria (California);',
  SRSTEPA: '',
  SSCW: 'Salem Sound Coastwatch',
  SSD: 'Colorado',
  SSWCD: 'Seth Mead, Current VolMon group',
  STANDARD_WQX: 'Water Quality Data',
  STANDLEY:
    'Water Quality Data for Upper Clear Creek Watershed from Georgetown to South Platte River',
  STCROIX_WQX: '',
  STF: 'Water Quality Data collected for a voluntary group of private, local, regional, state, and federal interests committed to reducing selenium in locally affected water ways while maintaining the economic viability and agricultural heritage of our areas.',
  STF_WQX: 'Seminole Tribe of Florida;',
  STJOHNSRIVERKPR_WQX: '',
  STOCKBRIDGE_MUNSEE: '',
  STOI: 'Spokane Tribe of Indians (Washington);',
  STORLVD_WQX: 'Water Quality Monitoring Data',
  STROUD_WQX: 'Water Quality Monitoring Data',
  ST_CROIX_WQX: 'St. Croix Chippewa Indians of Wisconsin (WI); ',
  SUMFS: 'Stockton University Marine Field Station',
  SUNENCO: 'Suncor Energy (USA) Inc. (Colorado)',
  SUQUAMISH: ' (Tribal)',
  SVR: '',
  SWFMDDEP_WQX: 'Water Quality Monitoring Data',
  SWINOMISH: '(Tribal)',
  SWO_OEP: '',
  SWQC: "The Summit Water Quality Committee (SWQC) is a watershed organization formalized by intergovernmental agreement.  Members include the Towns, County and major municipal dischargers (permits # CO-0021598, CO-0020451, CO-0020826, CO-0029955, CO-0021539) in Summit County Colorado. SWQC's focus is on providing definitive environmental assessments of the Blue River Watershed, including Dillon and Green Mountain Reservoirs and promoting pollution control.",
  SWRCB: '',
  SYCEO_WQX: ' (Tribal)',
  'T-BIOPSS': 'Washington Department of Fish and Wildlife (WDFW)',
  TABLEMOUNTAINRANCHERIA_WQX: 'Table Mountain Rancheria;',
  TAKSHANUK: 'Takshanuk Watershed Council Water Quality Monitoring',
  TAOSPBLO_WQX: 'Pueblo of Taos',
  TCEH: 'Thurston County Environmental Health',
  TCEQMAIN:
    'The Texas Commission on Environmental Quality (TCEQ) is the environmental agency for the state',
  TDECDOE_WQX: 'DOE Oversight Office',
  TDECWPC_WQX: 'WPC Division',
  TDECWR_WQX: '',
  TECK_AMERICAN: 'Teck American Incorporated',
  TEPA29: '',
  TESTGCSWQX: '',
  TESTORG_2999: 'TESTORG_2999; ',
  TEST_SD: '',
  TETRATECH: '',
  TGENVIRO: '',
  THCOENVHWA_WQX:
    'Division of Thuston County Public Health and Social Services',
  THD_LAB: 'Tennessee Department of Health Division of Laboratory Services',
  THORNTON_WQX: 'Water Quality Monitoring Data',
  THURSTONCOUNTY: 'Thurston County PHSS',
  TILLAMOOK_EP: 'York Johnson, Current VolMon group',
  TIMBISHA: 'Timbisha Shoshone Tribe; ',
  TIMSSD: 'Timpanogos Special Service District',
  TJRI: 'Town of Jamestown Rhode Island',
  TLBP_WQX: 'Tenmile Lakes Basin Partnership',
  'TLINGIT-HAIDA': 'Transboundary Rivers Baseline Water Quality Study Data',
  TMBLM_WQX: 'Bureau of Land Management, Tillamook Field Office (OR/WA)',
  TMTC_WQX: 'Tuolumne Me-Wuk Tribal Council, Environmental Dept.;',
  TNCAZ_WQX: 'The Nature Conservancy water quality monitoring',
  TNCNJ_WQX: 'The Nature Conservancy',
  "TOHONOO'ODHAMNATION":
    "Tohono O'odham Nation; Tohono O'odham Nation - Water Quality Monitoring Data",
  TOMWC: '',
  TONKAWA1: 'Tonkawa Tribe of Oklahoma; ',
  TONKAWA_WQX: 'Tonkawa Tribe of Oklahoma; ',
  TPCHD_WQX: '',
  TPEO_WQX:
    'Taos Pueblo Environmental Office; Taos Pueblo Environmental Office',
  TREX: 'Tribal Environmental Exchange Network; Environmental monitoring network for water quality data',
  TRILWWTF: 'Colorado',
  TRINIDADRANCHERIAEPA: 'Trinidad Rancheria;',
  TRTUL_WQX: 'Tulalip Tribes; ',
  TSWQC_WQX:
    'The TSWQC_WQX organization is for data collected under the direction of the Tri-State Water Quality Council.',
  TTFFX: '',
  TU: 'Conservation of freshwater streams, rivers, and associated upland habitats for trout, salmon, other aquatic species, and people',
  TUMWATER: 'City of Tumwater - Public Works',
  TURTLEMT: 'Archie Gronvold 106 Coordinator',
  TWI: 'Stony Brook-Millstone and the Central Delaware River Watersheds',
  TWWWTF: 'Colorado',
  TXSTRMTM_WQX: '',
  TYSON: '',
  UAEFMD_WQX: 'Edge-of Field monitoring data',
  'UB-SIAT-PE_WQX': 'University of Baltimore',
  UC_REGION_USBOR_WQX: '',
  UDAF: 'Utah Department of Agriculture and Food',
  UDWC_WQX: '',
  UH_CLEARLAKE: '',
  UMC: '',
  UMCRWWTF: 'Colorado',
  UMMP: 'THE UMMP IS A VOLUNTEER RIVER QUALITY MONITORING PROGRAM MANAGED BY THE UPPER MERRIMACK RIVER LOCAL ADVISORY COMMITTEE.  ESTABLISHED IN 1995, THE UMMP MONITORS RIVER QUALITY AT 11 SITES FROM FRANKLIN TO BOW ON THE PEMI, WINNI, CONTOOCOOK AND MERRI RIVERS',
  UMR: '',
  UPPERSKAGIT: 'Upper Skagit Indian Tribe;',
  URIWW:
    'Current (and historical) information on the water quality of surface water resources throughout Rhode Island, including lakes, ponds, reservoirs, rivers, streams and the marine environment.',
  URS: '',
  URWA: 'Upper Raritan Watershed Association',
  'USACE-STL-EC-E': '',
  USACENWP_WQX: '',
  USACENWS_WQX:
    'U.S. Army Corps of Engineers, Seattle District Water Management Section',
  USACESPK: '',
  USACE_WQX: 'Erich Emery - Great Lakes and Ohio River Division',
  USACOEND: 'US Army Corps of Engineers Nashville District',
  USBR: 'Utah Branch of United States Beau of Reclamation',
  'USBR-WCAO': 'Bureau of Reclamation Western Colorado Area Office',
  USCOEKY: 'US Army Corps of Engineers District',
  USDACA: '',
  USEPAREGION9: 'USEPA Region 9',
  USEPA_CORALREEFS_WQX: '',
  USEPA_REGION8: '',
  USET_WQX: 'United South and Eastern Tribes, Inc. (Tennessee); ',
  USFS0614_WQX: 'Water Quality Data',
  USFSPRESCOTT: '',
  USFSWHITEMT: '',
  USFWS_ALASKA: 'US Fish and Wildlife Service - Alaska Region',
  USFWS_NM_WQX: 'Water Quality Monitoring Data',
  USGS: '',
  'USGS-AK': 'USGS Alaska Water Science Center',
  'USGS-AR': '',
  'USGS-MN': 'USGS Minnesota Water Science Center',
  USGSNC: '',
  USIOUX_WQX: '',
  USVI: 'Water Quality Monitoring Data BEACHES',
  USVIST_WQX: 'Water Quality Monitoring Data for all the Waters in the state',
  UTAHDWQ_WQX: 'Ambient Water Quality Monitoring Data',
  UTAHGS: 'Utah Geological Survey',
  UTDWR: 'Utah Division of Wildlife Resources',
  UTEMTN: '',
  UTOGM_WQX: 'Utah Division of Oil, Gas, and Mining',
  UTRRVA05: '',
  UTTCHD: 'Utah - TriCounty Health Department',
  'UU-SWQ': '',
  UVAVTSSS_WQX: '',
  UWFCEDB_WQX:
    'Center for Environmental Diagnostics and Bioremediation, University of West Florida',
  UWP: '',
  UWT_CUW: 'University of Washington Tacoma at Center for Urban Waters',
  U_NH01:
    "THE UNIVERSITY OF NEW HAMPSHIRE'S JACKSON ESTUARINE LABORATORY (JEL) IS LOCATED FIVE MILES FROM THE DURHAM CAMPUS ON THE SHORES OF GREAT BAY ESTUARY AT ADAMS POINT (SEE DIRECTIONS, FACILITIES). RESIDENT FACULTY MEMBERS CONDUCT RESEARCH THAT COVERS A WIDE RANGE OF FIELDS AND IS SUPPORTED BY A VARIETY OF PRIVATE, STATE AND FEDERAL AGENCIES. STUDENTS, POST-DOCTORAL FELLOWS AND VISITING SCIENTISTS ARE ALSO ACTIVE IN JEL RESEARCH -CONTACT IS ADMIN/PROGRAM SUPPORT ASSISTANT",
  VADEP319: 'VA Department of Environmental Quality 319 Grants Monitoring',
  VALENCIA_WQX: 'Water Quality Monitoring Data',
  VBKI_WQX: 'Viejas Band of Kumeyaay Indians; Viejas Band of Kumeyaay Indians',
  VERMONTANR: '',
  VERSAR: '',
  VM_SDCWC_AW: 'Paul Robertson, Current VolMon group',
  VM_SWC: 'Kyle Terry, Current VolMon group',
  VOS1_WQX: 'Village of Solomon; Village of Solomon',
  'VT2009,': '',
  VWIN: 'Water Quality Monitoring Data',
  WALKER_PAIUTE: 'WALKER RIVER PAIUTE;',
  WALLAWALLA_WC: 'Current VolMon group',
  WARMSPRINGS09: 'Confederated Tribes of Warm Springs;',
  WASHNVCA_WQX: '',
  WASIT: 'STILLAGUAMISH NATURAL RESOURCES DEPARTMENT',
  WATERANDAIR: 'www.waterandair.com',
  WATERLDF_WQX: 'Lac Du Flambeau Band of Lake Superior Chippewa Indians DNR; ',
  WATERQUALITYPORTAL: 'www.waterqualitydata.us',
  WAYNE_STATE_UNIVERSITY: '',
  WA_ECOLOGY: 'Washington State Government',
  WCD: 'A local unit of government in Washington County, Minnesota dedicated to soil and water conservation',
  WC_WQX: '',
  WDEP_WQX:
    'Wichita and Affiliated Tribes of Oklahoma Water Quality Monitoring Data',
  WDFW: 'Washington Department of Fish and Wildlife; ',
  WEARTH_WQX: 'White Earth Band of Chippewa (MN);',
  WETLAB: 'Western Environmental Testing Laboratory; ',
  WFWQC_UT: 'Wasatch Front Water Quality Council Utah',
  WHATCOMCD_WQX: 'Whatcom Conservation District',
  WHATCOM_WQX: 'Whatcom County Public Works',
  WHITEMOUNTAIN_WQX: 'White Mountain Apache Tribe;',
  WICHITAEPA_WQX:
    'Wichita and Affiliated Tribes Of Oklahoma; Wichita and Affiliated Tribes Of Oklahoma',
  WIDNR_WQX: 'Wisconsin Department of Natural Resources.',
  WILLOWCREEK: 'CDSN - Willow Creek Reclamation Committee',
  WINDWARDENV_WQX: 'WindwardEnvironmental',
  WINNEBAGO07: 'Winnebago Tribe of Nebraska; ',
  WINNEBAGO07_WQX: 'Winnebago Tribe of Nebraska;',
  WIYOT_WQX: 'Wiyot Tribe (California);',
  WI_MMSD: '',
  WLA: '',
  WMAT_WQX: 'White Mountain Apache Tribe Watershed Program;',
  WMHMD: 'Colorado',
  WNENVDPT_WQX: '',
  WOOD: 'Energy services company submitting sediment data for a dredging project.',
  WQXPQRC: '',
  WQXTEST: 'Test',
  WQXWEBTRAINING: '',
  WQXWEBTRAINING1: '',
  WQXWEBTRAINING10: 'Planning and Natural Resources Department',
  WQXWEBTRAINING11: '',
  WQXWEBTRAINING12: '',
  WQXWEBTRAINING13: '',
  WQXWEBTRAINING14: '',
  WQXWEBTRAINING15: '',
  WQXWEBTRAINING16: '',
  WQXWEBTRAINING17: '',
  WQXWEBTRAINING18: '',
  WQXWEBTRAINING19: '',
  WQXWEBTRAINING2: '',
  WQXWEBTRAINING21: '',
  WQXWEBTRAINING22: 'Northern Basin WVDEP NPS program',
  WQXWEBTRAINING23: '',
  WQXWEBTRAINING24:
    'Community based non profit organization dedicated to restoring wild salmon runs in Whatcom County',
  WQXWEBTRAINING25: '',
  WQXWEBTRAINING26: '',
  WQXWEBTRAINING27: '',
  WQXWEBTRAINING28: '',
  WQXWEBTRAINING29: '',
  WQXWEBTRAINING3: '',
  WQXWEBTRAINING30: '',
  WQXWEBTRAINING4: '',
  WQXWEBTRAINING5: '',
  WQXWEBTRAINING6: '',
  WQXWEBTRAINING7: '',
  WQXWEBTRAINING8: '',
  WQXWEBTRAINING9: '',
  WRDM18: 'Chesapeake Commons',
  WREQC_WQX: '',
  WRFOBLM: '',
  WRWMG: '',
  WRWQMP: '',
  WSDANRAS: 'Washington State Department of Agriculture',
  WSDA_WQX:
    'Washington State Department of Agriculture, Dairy Nutrient Management Program',
  WSG: 'The WSG mission is to help people and marine life thrive by supplying research, technical expertise and educational activities that support the responsible use and conservation of ocean and coastal ecosystems.',
  WSSC_WQX: 'Water Quality Monitoring',
  WU: '',
  WVDEPNPS: '',
  WVDEP_WIB_WQX:
    'West Virginia Department of Environmental Protection Watershed Improvement Branch',
  WVDEP_WQX: 'State of WV Ambient Water Quality',
  WVSU_AERS:
    'High frequency data in three locations along the Kanawha River, WV measuring temperature, pH, DO, NO3, Cl, ORP, specific conductance, turbidity',
  WVSU_WQX: 'West Virginia State University',
  WVU_WQX: 'West Virginia University',
  WWMD_VA: '',
  WWMD_VA_WQX: 'Water Quality Monitoring Data',
  WWP: '',
  WWSD: 'Colorado',
  WWXINCOG: '',
  WYDEQ_WATERSHED: '',
  WYDEQ_WQX: 'Water Quality Monitoring Data for all the Waters in the state',
  YAKAMA_WQX: 'Yakama Nation Environmental Management Program; ',
  YAKIMAVLYDAIRIES_WQX: 'c/o  Inland Earth Sciences Corp.',
  YAN_WQX: 'Yavapai-Apache Nation;',
  YELLOWBUG: ' (Tribal)',
  YERINGTON_WQX: 'Yerington Paiute Tribe; Yerington Paiute Tribe',
  YOMBA: 'Yomba Shoshone Tribe; ',
  YPIT_WQX: ' (Tribal)',
  YRITWC: ' (Tribal)',
  YUROKTEP_WQX: 'Yurok Tribe; Yurok Tribe Environmental Program',
  ZIAPUEBLO_WQX: ''
}
