export default {
  16582:
    'Chickaloon Native Village (Tribal) || Chickaloon Native Village (Tribal)',
  123225: 'Beach Program',
  934010:
    'Confederated Tribes of the Umatilla Indian Reservation (Tribal) || Confederated Tribes of the Umatilla Indian Reservation (Tribal)',
  939785:
    'This is a duplicate organization setup for the NHDES and does not contain any data. It is strictly used for testing only.',
  947757:
    'Confederated Tribes of the Coos, Lower Umpqua and Siuslaw Indians (Tribal) || Confederated Tribes of the Coos, Lower Umpqua and Siuslaw Indians (Tribal)',
  1121575: 'Water Quality Monitoring Data',
  1143709: '',
  1328642: '',
  11113300: 'STATE OF NEW HAMPSHIRE ENVIRONMENTAL AGENCY',
  '*********RIVERWATCH': '',
  '*******CMC': '(https://www.chesapeakemonitoringcoop.org/)',
  '0800257_WQX': 'Water quality',
  '0800597_WQX': 'Region 8 Superfund Program',
  '0800650_WQX': 'Water quality',
  '0800852_WQX': 'Water Quality Monitoring',
  '0801194_WQX': '',
  '0801417_WQX': 'Water Quality',
  '0801478_WQX': 'Region 8 Superfund Program',
  '0801505_WQX': 'water quality',
  '0801600_WQX': 'Water Quality Data',
  '0801695_WQX': 'Water Quality Data',
  '0801698_WQX': 'Water Quality Data',
  '0801812_WQX': 'Water Quality Data',
  '081575_WQX': '',
  '081577_WQX': 'The City and County of Denver',
  '081700_WQX': 'Gilt Edge Mine data',
  '0834QB00_WQX': 'Water Quality Data',
  '1083919_WQX': 'Bronx River Alliance',
  '1111REG1_WQX': 'Water Quality Monitoring Data',
  '1117MBR_WQX': 'Water Quality Data',
  '1119USBR_WQX': 'Water Quality Monitoring Data',
  '11COETUL_WQX': 'Water Quality Monitoring Data',
  '11DELMOD_WQX': 'Water Quality Monitoring Data',
  '11FLKNMS_WQX': 'Water Quality Monitoring Data.',
  '11NPSWRD_WQX': '',
  '11TOX09_WQX': 'Priority Pollutant Data',
  '1CTDPHBM': '',
  '1VTDECWQ': '',
  '211WVOWR_WQX':
    'Water Quality Monitoring Data for all the Waters in State of West Virginia.',
  '21AKBCH': 'Beach Monitoring Data',
  '21ALBCH': 'State of Alabama Environmental Agency',
  '21AQ_WQX': '',
  '21ARIZGW_WQX': 'Water Quality Monitoring',
  '21AS_WQX': '',
  '21AWIC': '',
  '21BRBCH': 'The Natural Resources Department within the Bad River Tribe',
  '21CABCH': 'Contractor for the State of California',
  '21CAOCSD_WQX': 'Water quality monitoring data',
  '21COL001_WQX':
    'Colorado DPHE Water Quality Control Division data migrated from legacy STORET',
  '21DEBCH': 'Delaware environmental agency',
  '21DELAWQ_WQX': 'Delaware environmental agency',
  '21FLACEP_WQX': 'Water Quality Monitoring Data',
  '21FLACST_WQX': 'Water Quality Monitoring Data',
  '21FLALTA_WQX': 'Water Quality Monitoring Data',
  '21FLAMEC_WQX': 'Water Quality Monitoring data',
  '21FLANER_WQX': 'Water Quality Monitoring Data',
  '21FLAVON_WQX': 'Water Quality Monitoring Data',
  '21FLA_WQX': 'Water Quality Monitoring Data',
  '21FLBABR_WQX': 'Water Quality Monitoring Data',
  '21FLBBAP_WQX': 'Water Quality Monitoring Data',
  '21FLBFA_WQX':
    'Partnering of The Bream Fisherman Association with  The Florida Department of Environmental Protection for Water Quality Monitoring for Santa Rosa and Escambia Counties',
  '21FLBRA_WQX': 'Water Quality Monitoring Data',
  '21FLBREV_WQX': 'Water Quality Monitoring Data',
  '21FLBROW_WQX': 'Water Quality Monitoring Data\nNELAC Certification #E46053',
  '21FLBSG_WQX': 'Surface water Biological Sediment',
  '21FLCASS_WQX': 'Water Quality Monitoring Data',
  '21FLCBA_WQX': 'Water Quality Monitoring Data',
  '21FLCCSW_WQX': 'Water quality monitoring data',
  '21FLCCZM_WQX': 'Water Quality Monitoring Data',
  '21FLCEN_WQX': 'Water Quality Monitoring Data',
  '21FLCHAR_WQX':
    'The Charlotte Harbor Estuaries Volunteer Water Quality Monitoring Network (CHEVWQMN)',
  '21FLCHCO_WQX': 'Water Quality Monitoring Data',
  '21FLCHDH': '',
  '21FLCHDH_WQX': 'Water Quality Monitoring Data',
  '21FLCMP_WQX':
    'Okaloosa County Environmental Council water quality monitoring organization ("Aqualab") partnering with The Florida Department of Environmental Protection for  Water Quality Monitoring of Choctawhatchee Bay and adjacent water bodies.',
  '21FLCOAB_WQX': 'Water Quality Monitoring data',
  '21FLCOBS_WQX': 'Water Quality Monitoring Data',
  '21FLCOFM_WQX': 'Water Quality Monitoring Data',
  '21FLCOJB_WQX': 'Water Quality Monitoring data',
  '21FLCOLL_WQX': '3339 Tamiami Trail East, Suite 304\nNaples, FL 34112',
  '21FLCOMI_WQX': 'Water Quality Monitoring Data',
  '21FLCONB_WQX': 'Water Quality Monitoring Data',
  '21FLCONS_WQX': 'Water Quality Monitoring',
  '21FLCOPC_WQX': 'Water Quality Monitoring Data',
  '21FLCOSP_WQX': 'Water Quality Monitoring data',
  '21FLCOT_WQX': 'Water Quality Monitoring Data',
  '21FLCPSJ_WQX': 'water quality monitoring data',
  '21FLCPSL_WQX': 'Water Quality Monitoring Data',
  '21FLCRCP_WQX': 'Water Quality Monitoring Data',
  '21FLDADE_WQX': 'Water Quality Monitoring Data',
  '21FLDELT_WQX': 'Water Quality Monitoring',
  '21FLDOH_WQX': 'Floridas Healthy Beaches Program Water Quality Data',
  '21FLDUNE_WQX': 'Water Quality Monitoring Data',
  '21FLECUA_WQX': 'Water Quality Monitoring Data',
  '21FLEECO_WQX': 'Ambient Surface Water Quality Monitoring Data',
  '21FLERDI_WQX': 'Water Quality Monitoring Data',
  '21FLESC_WQX': 'Water Quality Monitoring Data',
  '21FLESPI_WQX': 'Water Quality Monitoring Data',
  '21FLFLAT_WQX': 'Water Quality Monitoring Data',
  '21FLFMRI_WQX': 'Water Quality Monitoring Data',
  '21FLFRYD_WQX': 'Water Quality Monitoring Data',
  '21FLFSI_WQX': 'Water Quality Monitoring Data',
  '21FLFTM_WQX': 'Water Quality Monitoring Data',
  '21FLFWC_WQX': 'Water Quality Monitoring Data',
  '21FLGAEP_WQX': 'Water Quality Monitoring Data',
  '21FLGBO1_WQX':
    'Water Quality Monitoring Data: USEPA Office of Research and Development, National Health and Environmental Effects Research Laboratory (NHEERL), Gulf Ecology Division',
  '21FLGCWW_WQX': 'Groundwater Monitoring',
  '21FLGFWF_WQX': 'Water Quality Monitoring Data',
  '21FLGJAX_WQX': 'Water Quality Monitoring Data',
  '21FLGPC_WQX': 'Water Quality Monitoring Data',
  '21FLGTM_WQX': 'Water Quality Monitoring Data',
  '21FLGWMS_WQX': 'Water Quality Monitoring Data',
  '21FLGW_WQX': 'Water Quality Monitoring Data',
  '21FLHBOI_WQX': 'Water Quality Monitoring Data',
  '21FLHESD_WQX': 'Water Quality Monitoring Data',
  '21FLHILL_WQX':
    'Ambient water quality monitoring data collected by Hillsborough County Environmental Protection Commission, Monitoring and Analysis Section\n\nNote: Detection limit for Enterococcus bacteria is 2 / 100 mL unless otherwise indicated for 2001.',
  '21FLIMCA_WQX': 'Surface Water Data',
  '21FLJEA_WQX': 'Water Quality Monitoring data',
  '21FLJXWQ_WQX': 'Water Quality Monitoring data',
  '21FLKEYW_WQX': 'Water Quality Monitoring Data',
  '21FLKISS_WQX': 'Water Quality Monitoring Data',
  '21FLKNMS_WQX': 'Water Quality Monitoring Data',
  '21FLKTNC_WQX': 'Water Quality Monitoring Data',
  '21FLKWAT_WQX': 'Water Quality Monitoring Data',
  '21FLLCHD_WQX': 'Water Quality Monitoring Data',
  '21FLLCPC_WQX': 'Water Resource Monitoring for Lake County',
  '21FLLEHI_WQX': 'Water Quality Monitoring Data',
  '21FLLEON_WQX': 'Water Quality Monitoring Data',
  '21FLLOXB_WQX': 'Biological Data',
  '21FLLOX_WQX': 'Water Quality Monitoring Data',
  '21FLMAIT_WQX': 'Water Quality Monitoring Data',
  '21FLMANA_WQX': 'Water Quality Monitoring Data',
  '21FLMAR_WQX': 'Water Quality Monitoring Data',
  '21FLMAYP_WQX': 'Water Quality Monitoring data',
  '21FLMCGL_WQX': 'Water Quality Monitoring Data',
  '21FLMONR_WQX': 'Water Quality Monitoring Data',
  '21FLMOSA_WQX': 'Water Quality Monitoring Data',
  '21FLMRC_WQX': 'Water Quality Monitoring Data',
  '21FLMWK_WQX': 'Water Quality Monitoring Data',
  '21FLNAPL_WQX': 'Water Quality Monitoring Data',
  '21FLNOPO_WQX': 'Water Quality Monitoring Data',
  '21FLNUTT_WQX': 'Water Quality Monitoring Data',
  '21FLNWFD_WQX': 'Ambient Water Quality Monitoring Data',
  '21FLORAN_WQX': 'Ambient Water Quality Monitoring of Data',
  '21FLORL_WQX':
    "Within the Stormwater Division, our mission is to collect and maintain, through water samples, monitoring and inspections, the data necessary to support the preservation of the quality of Orlando's lakes.",
  '21FLOSCE_WQX': 'Water Quality Monitoring Data',
  '21FLPASC_WQX': 'Water Quality Monitoring Data',
  '21FLPBCH_WQX': 'Water Quality Monitoring',
  '21FLPBSD_WQX': 'Water Quality Monitoring Data',
  '21FLPCSW_WQX': 'Water Quality Monitoring Data',
  '21FLPDEM_WQX':
    'The Water Resources Management Section (WRMS) of the Pinellas County Department of Environmental Management (DEM) began the Surface Water Ambient Monitoring Program (SWAMP) in 1990 as part of the County Comprehensive plan of 1989.',
  '21FLPNS_WQX':
    'Water Quality Monitoring Data for the Watershed Management Section of the Water Resources Department of The Florida Department of Environmental Protection',
  '21FLPOLK_WQX':
    'To monitor, manage, prtoect and improve the groundwater and surface water resources of Polk County',
  '21FLRCID_WQX': 'Water Quality Monitoring Data',
  '21FLROOK_WQX': 'Water Quality Monitoring Data',
  '21FLSABR_WQX': 'Water Quality Monitoring Data',
  '21FLSARA_WQX': 'Surface Water, Ground Water, Biological, & Sediment.',
  '21FLSBL_WQX': 'Water Quality Monitoring Data',
  '21FLSCCF_WQX': 'Water Quality Monitoring Data',
  '21FLSCWK_WQX': 'Water Quality Monitoring Data',
  '21FLSEAS_WQX': 'Water Quality Monitoring Data',
  '21FLSEM_WQX': 'Water Quality Monitoring Data',
  '21FLSFWM_WQX': 'Water Quality Monitoring Data',
  '21FLSGCSP': '',
  '21FLSJUD_WQX': 'Water Quality Monitoring Data',
  '21FLSJWM_WQX': 'Water Quality Monitoring Data',
  '21FLSMRC_WQX': '',
  '21FLSUW_WQX': 'Water quality Monitoring Data',
  '21FLSWFD_WQX': 'Water Quality Monitoring Data',
  '21FLTBW_WQX': 'Water Quality Monitoring Data.¶',
  '21FLTHAS_WQX': 'Water Quality Monitoring Data',
  '21FLTHLR_WQX':
    'Florida Department of Environmental Protection-Tallahassee ROC',
  '21FLTLHR_WQX': 'Water quality monitoring data',
  '21FLTPA_WQX':
    'State environmental regulatory agency which generates water and sediment quality data, physicochemical data and biological data.',
  '21FLUFSW_WQX': 'Water Quality Monitoring Data',
  '21FLVEMD_WQX':
    'The VCEHL is a full service local laboratory formed by combining County of Volusia Environmental Management Services and state Department of Health personnel.  Ambient monitoring of three river systems is conducted.',
  '21FLVOE_WQX': 'Water Quality Monitoring Data',
  '21FLWET_WQX': 'Water Qaulity Monitoring',
  '21FLWPBH_WQX': 'Water Quality',
  '21FLWPB_WQX': 'Water Quality Monitoring Data',
  '21FLWQA_WQX':
    'Watershed Assessment Section (WAS) - Formerly WQAS\nSurface Water Quality Monitoring Data and TMDLs',
  '21FLWQSP_WQX': 'Water Quality Monitoring Data',
  '21GACRD': 'COASTAL RESOURCES DIVISION',
  '21GAEPD_WQX': 'Georgia DNR Environmental Protection Division',
  '21GA_WQX': 'Water Quality Monitoring Data for all the Waters in the state',
  '21GPBCH': '',
  '21GUAM': 'Water Quality Monitoring Data',
  '21GUBCH': '',
  '21HI': '',
  '21ILBCH_WQX': '',
  '21INBCH': '',
  '21INDEM': '',
  '21IND_WQX': 'Water Quality Monitoring Data for all the Waters in the state',
  '21IOWA_WQX':
    'Data collected by the Iowa Dept. of Natural Resources Water Monitoring Section or one of its delegates.',
  '21KAN001_WQX':
    'Water Quality Monitoring Data for all the Waters in the state',
  '21KY_WQX': 'KY WQX',
  '21LABCH': '',
  '21MABCH': '',
  '21MEBCH': 'Maine Dept of Env Protection.',
  '21MICH_WQX': '',
  '21MNBCH': '',
  '21MSBCH': 'Mississippi Agency responsible for Beaches data',
  '21MSWQ_WQX':
    "The Mississippi Department of Environmental Quality is responsible for protecting the state's air, land, and water. Our mission is to safeguard the health, safety, and welfare of present and future generations of Mississippians by conserving and improving our environment and fostering wise economic growth through focused research and responsible regulation.",
  '21NC01WQ_WQX':
    'Water Quality Monitoring Data for all the Waters in the state',
  '21NC02WQ_WQX':
    'Water Quality Monitoring Data for all the Waters in the state',
  '21NC03WQ':
    'State of North Carolina, Dept of Environment Quality, Div of Water Resources',
  '21NCBCH':
    'NC Department of Environment and Natural Resources, Division of Environmental Health, Recreational Water Quality Program',
  '21NCCOALITIONS': 'NC DWQ Monitoring Coalition Program',
  '21NCMONITORING': 'NC DWR Monitoring Coalition Program',
  '21NDHDWQ_WQX': 'Division Of Water Quality',
  '21NEB001_WQX': '',
  '21NEV1_WQX': 'Nevada Division of Environmental Protection',
  '21NJBCH': '',
  '21NJDEP1_WQX': '',
  '21NMEX_WQX': 'NM Environmental Dept./SWQB',
  '21NYBCH': '',
  '21NYDECA_WQX': 'To protect and conserve the waters of New York State',
  '21OHBCH': '',
  '21OHDGW_WQX': '',
  '21OHIO_WQX': '',
  '21ORBCH': 'Beaches Program',
  '21PABCH': 'Local health department',
  '21PA_WQX': 'PA ENVIRONMENTAL PROTECTION',
  '21RIBCH': '',
  '21SC60WQ_WQX': '',
  '21SCBCH_WQX': '',
  '21SCESOP_WQX': 'Water Quality Monitoring Data',
  '21SCGW_WQX': 'Groundwater Monitoring Data',
  '21SCSANT_WQX': 'SC Public Service Authority',
  '21SCSHL_WQX': 'South Carolina Department of Environmental Services',
  '21TNWQ_WQX': '',
  '21TXBCH': 'GLO',
  '21VABCH': 'Beach Program',
  '21VASWCB': '',
  '21WABCH': '',
  '21WIBCH': '',
  '21WVWQAS_WQX':
    'Water Quality Monitoring Data for all the Waters in the state',
  '22LAGWTR_WQX': 'Ground water data',
  '31DELRBC_WQX': '',
  '31DRBCSP_WQX': 'Water Quality Monitoring Data',
  '31ISC2RS_WQX': 'A Tri-State Water and Air Pollution Control Agency',
  '31ORWUNT_WQX': 'Water Quality Monitoring Data',
  '42SRBCWQ_WQX': 'Water Quality Monitoring Data',
  '501CTHREE': 'Bring clean water to communities in need.',
  '952307_WQX': '',
  A4GL_WQX: '',
  ABCI_WQX:
    'Tribal Environmental Protection Agency for the Augustine Band of Cahuilla Indians',
  ABSHAWNEE:
    'Absentee Shawnee Tribe of Oklahoma (Tribal) || Absentee Shawnee Tribe of Oklahoma (Tribal)',
  ACBCI_WQX:
    'Agua Caliente Band of Cahuilla Indians of the Agua Caliente Indian Reservation, California (Tribal) || Agua Caliente Band of Cahuilla Indians of the Agua Caliente Indian Reservation, California (Tribal)',
  ACOMA_PUEBLO_WQX:
    'Pueblo of Acoma, New Mexico (Tribal) || Pueblo of Acoma, New Mexico (Tribal)',
  ADGGS: 'Alaska Division of Geological & Geophysical Surveys',
  ADVENTURESCIENTISTS:
    'Citizen science data collection in far flung locations around the world.',
  AFW_PDX: 'Portland, Oregon office',
  AHRA: '',
  AIEO: 'American Indian Environmental Office (Tribal) || American Indian Environmental Office (Tribal)',
  'AK-CHIN_WQX':
    'Ak-Chin Indian Community (Tribal) || Ak-Chin Indian Community (Tribal)',
  AKBLM_FDO: 'Water Quality Monitoring Data',
  AKDECAKMAP:
    'The mission of DEC\'s Division of Water is to improve and protect the quality of all Alaskan waters and under the Clean Water Act (CWA)Sections 303(d) and 305(b) Alaska has the responsibility to report and identify causes and sources of water quality impairment by "characterizing all the waters in Alaska". One way the division carries out this mission is to monitor and report on water quality. The Alaska Monitoring & Assessment Program (AKMAP) fulfills this responsibility.',
  AKDECSPAR: '',
  AKDECWQ: 'Water quality Standards Assessment & Restoration',
  AKDFGSPF: 'Alaska Department of Fish and Game, Division of Sport Fish',
  AKDNRFOR: '',
  'ALABAMACOUSHATTATRIBE.TX_WQX':
    'Alabama-Coushatta Tribe of Texas (Tribal) || Alabama-Coushatta Tribe of Texas (Tribal)',
  ALASSWCD_WQX: 'Water Quality Monitoring Data',
  ALLARM: '',
  ALO_WQX:
    'Promote and maintain clean water and a healthy coastal environment through education, research, and active participation.',
  'ALS-SJ':
    'American Littoral Society - Delaware Bayshore Office, Water Quality Monitoring',
  ALS_WQX:
    'The American Littoral Society promotes the study and conservation of marine life and habitat, protects the coast from harm, and empowers others to do the same.',
  ANCHORQEA: 'Clients',
  ANIMASWP:
    'The AWP is a stakeholder driven, collaborative, watershed-based group made up of partners representing diverse interests across the watershed in New Mexico, the Southern Ute Tribal Lands and Colorado. Current membership is over 100 individuals and entities. The AWP works together across state and Tribal boundaries to protect and improve the quality of water resources in the Animas River.',
  ANTIX_WQX: 'National Park Service',
  APCC_WQX: '',
  APPLEGATE_WC: 'Former VolMon group',
  AQS: "Beta COPY of AQS which is EPA's repository of ambient air quality data that assists in air quality assessments, designations, modeling for permit review",
  AQUINNAH_WQX: 'Wampanoag Tribe of Gay Head (Aquinnah) - Massachusetts;',
  ARCADISNY: '',
  ARDEQH2O_WQX: '',
  AREMP:
    'The Aquatic and Riparian Effectiveness Monitoring Program (AREMP) is a "Service First" program consisting of USDA Forest Service (USFS) and USDI Bureau of Land Management (BLM)',
  'ARKANSASE&E': 'Energy and Environment - Arkansas.gov',
  ARMYCORPS: 'US Army Corps of Engineers District (West Virginia)',
  ARR: '',
  ARSG: 'Water Quality Monitoring Data',
  ARWRF: '',
  ARWWRRI_WQX: 'Water Quality Monitoring Data: BIOmonitoring',
  ASEPA_WQX: '',
  ASHCREEKCONSERVATIONASSOC:
    'The Ash Creek Conservation Association mission is to advocate for protecting and restoring the ecologically fragile Ash Creek tidal estuary, as well as surrounding waters and coastal land areas.',
  ASPECT_WQX: '',
  ASUERF: '',
  AURORA_WQX: 'Water Quality Monitoring Data',
  AUSABLECENTER: '',
  AWC_WQX:
    'Water Quality Monitoring Data. American Water is a water resource company where the majority of the companys activities are centered in locally-managed utility subsidiaries that are regulated by the state in which each operates.',
  AWQDECJN: '',
  AWQDECJN_WQX: '',
  AWRC: '',
  AWRL: '',
  AWW_WQX: 'Citizen Science Monitoring Program',
  AZDEQ_GW: 'Water Quality Division: Groundwater',
  AZDEQ_SW: 'Water Quality Division: Surface Water',
  AZDEQ_WPD: 'Waste Programs Division',
  BACKBAYNWR: 'Back Bay National Wildlife Refuge',
  BADRIVER_WQX: 'Bad River Tribe',
  BANTAMLAKE_WQX: '',
  BATTELLE_NFTDR_WQX: 'Battelle',
  BATTELLE_NOR_WQX: '',
  BBC: 'Baywatch Monitoring Program',
  BBP_WQX:
    'The Barnegat Bay Partnership is a partnership of federal, state, municipal, academic, business, and private organizations working together to help restore, protect, and enhance the natural resources of the Barnegat Bay ecosystem.',
  BCENV:
    'Ministry of Environment and Climate Change Strategy, Environmental Protection Division',
  BCHMI_WQX: 'Beaches Program Data',
  BCUTAHLAB: 'Brigham City Laboratory',
  BEAR_CRK_WQX: 'Water Quality Data',
  BENTON_SWCD: '',
  BERGERGROUP: '',
  BERRY: '',
  BESD: 'Colorado',
  BETA_OCMA: '',
  BIGDRY: '',
  BIGLAG_WQX:
    'Big Lagoon Rancheria, California (Tribal) || Big Lagoon Rancheria, California (Tribal)',
  BIGPINEPAIUTE:
    'Big Pine Paiute Tribe of the Owens Valley (Tribal) || Big Pine Paiute Tribe of the Owens Valley (Tribal)',
  BIGSANDY:
    'Big Sandy Rancheria of Western Mono Indians of California || Big Sandy Rancheria of Western Mono Indians of California (Tribal)',
  BIISHNIINI4: '',
  BILLIONOYSTERPROJECT: '',
  BISHOPPAIUTETRIBE:
    'Bishop Paiute Tribe (Tribal) || Bishop Paiute Tribe (Tribal)',
  BISHOP_PAIUTE_TRIBE_WQX: 'Bishop Paiute Tribe',
  BLCKFEET: '',
  BLMRW: 'Water Quality Monitoring Data',
  BLM_WRBBD: '',
  BLR: 'Blue Lake Rancheria (California) (Tribal) || Blue Lake Rancheria (California) (Tribal)',
  BLR_WQX: 'BLUE LAKE RANCHERIA',
  BLUERIVERWATERSHEDASSOCIATION: '',
  BMIC_WQX:
    'Bay Mills Indian Community, Michigan (Tribal) || Bay Mills Indian Community, Michigan (Tribal)',
  BMWM_TEST: 'TEST',
  BOISNETT_WQX:
    'Region 5 Wild Rice - Bois Forte/Nett Lake Band of Chippewa Indians',
  BOOMSNUBSITE_EA:
    'Data loaded by EA Engineering Inc. for the Boomsnub Superfund Site, Vancouver, Clark County, Washington.',
  BOUNTIFL_WQX: ' Superfund',
  BPMWQX:
    "Supporing EPA's Bonita Peak Mining District's (Superfund site) public data sharing efforts",
  BRB: 'Bear River Band of the Rohnerville Rancheria, California (Tribal) || Bear River Band of the Rohnerville Rancheria, California (Tribal)',
  BRC: 'THE MISSION restore the Blackstone River and to improve the health of the Blackstone River Watershed.',
  BRIDGEPORTIC:
    'Bridgeport Indian Colony (Tribal) || Bridgeport Indian Colony (Tribal)',
  BRIGHTON_WQX: 'Water Quality Monitoring Data',
  BROADRIVERNC: 'French Broad Riverkeeper monitoring',
  BRWC_WV: '',
  BTBAQUATIC_WQX:
    'Grand Traverse Band of Ottawa and Chippewa Indians, Michigan (Tribal) || Grand Traverse Band of Ottawa and Chippewa Indians, Michigan (Tribal)',
  BTMUA: 'Drinking water provider',
  BTWTRFRM: 'Water Quality Monitoring Data.',
  BUCKSCCD: '',
  BUNKER_FWS: 'Water Quality Monitoring Data',
  BUNKER_USGS: '',
  BUNKER_WQX: 'Water Quality Monitoring Data',
  BURNSPAIUTE: 'Burns Paiute Tribe (Tribal) || Burns Paiute Tribe (Tribal)',
  BURNSPAIUTE123: 'Burns Paiute Tribe (Tribal) || Burns Paiute Tribe (Tribal)',
  BUZZARDSBAYNEP: 'Tribal',
  BVR: '',
  BXA: 'Volunteer Monitoring Group',
  CABAZWQ32:
    'Cabazon Band of Mission Indians, California (Tribal) || Cabazon Band of Mission Indians, California (Tribal)',
  CABEACH_WQX: 'California Beach Monitoring Data',
  CADDONATION_WQX:
    'Caddo Nation of Oklahoma (Tribal) || Caddo Nation of Oklahoma (Tribal)',
  CADMUS: '',
  CADPR_WQX: 'Water Quality Monitoring Data',
  CADWR_WQX:
    'California Department of Water Resources (Volunteer)* || California Department of Water Resources (Volunteer)*',
  CAFRESNO_WQX: 'Water Quality Data',
  CALSWAMP_WQX: 'Water Quality Monitoring Data.',
  CALTRANS_WQX: '',
  CALWR_WQX:
    'DWR is responsible for the operation of the State Water Project, including the California Aqueduct.  DWR also monitors surface and groundwater at locations throughout California.',
  CAPECOD_REG_WQ: '',
  CAPECRD_WQX: 'Water Quality Monitoring Data',
  CARGILLMS_WQX: 'Cargill Meat Solutions (aka. Fort Morgan Beef Plant)',
  CATAWBA: '(Tribal)',
  CATAWBARIVERKEEPER: 'Catawba Riverkeeper Foundation (CRF)',
  CA_BVR:
    'Big Valley Band of Pomo Indians of the Big Valley Rancheria, California (Tribal) || Big Valley Band of Pomo Indians of the Big Valley Rancheria, California (Tribal)',
  CA_SWRCB: '',
  CBMI_WQX:
    'Cabazon Band of Mission Indians, California (Tribal) || Cabazon Band of Mission Indians, California (Tribal)',
  CBP_WQX: 'Chesapeake Bay Program (PRODUCTION Environment)',
  CBS: '',
  CC: '',
  CCAMP_WQX: 'Water Quality Data',
  CCC: '',
  'CCCE-WHSE': 'Cape Cod Cooperative Extension/Woods Hole Sea Grant',
  CCS: 'https://coastalstudies.org/',
  CCSCD: '',
  CCSHBWA: 'Crafts Creek Spring Hill Brook Watershed Association',
  CCSR: 'Cohasset Center for Student Coastal Research',
  CCUI_WQX:
    'Cow Creek Band of Umpqua Tribe of Indians (Tribal) || Cow Creek Band of Umpqua Tribe of Indians (Tribal)',
  CCU_EQL: '',
  CCWC: "Coal Creek Watershed Coalition (CCWC) is 501(c)(3) non-profit organization. The mission of CCWC is to maintain, restore and enhance the environmental integrity of Crested Butte's local watersheds to ensure those local watersheds and habitats are of the highest possible quality necessary to support wildlife, aquatic life, and human life.",
  CCWF: 'Water Quality Data to promote sustainable natural resource management throughout the Clear Creek Watershed and serve as a model for the arid mountain west..',
  CDATRUST: '',
  CDATWATRES: "Coeur D'Alene Tribe (Tribal) || Coeur D'Alene Tribe (Tribal)",
  CDOT: '',
  CEDARRANCH_WQX:
    'Cedarville Rancheria (Tribal) || Cedarville Rancheria (Tribal)',
  CEDEN: 'California State Water Resources Control Board',
  CENAB: 'US Army Corps of Engineers District',
  CENTREAL_WQX: '',
  CENWWEDH_WQX: 'Water Quality Data',
  CEPACBMI_WQX: '',
  CGWPCF: 'Colorado',
  CHARLOTTEHARBOREC_WQX: '',
  CHATFLD_WQX: 'Water Quality Data',
  CHATTAHOOCHEERIVERKEEPER: 'Chattahoochee Riverkeeper',
  CHEHALIS_WQX:
    'Confederated Tribes of the Chehalis Reservation (Tribal) || Confederated Tribes of the Chehalis Reservation (Tribal)',
  CHEMEHUEVI_WQX:
    'Chemehuevi Indian Tribe of the Chemehuevi Reservation, California (Tribal) || Chemehuevi Indian Tribe of the Chemehuevi Reservation, California (Tribal)',
  CHEROKEEMD: 'Colorado',
  CHEROKEE_WQX: 'Cherokee Nation (Tribal) || Cherokee Nation (Tribal)',
  CHESAPEAKBAYNERR: '',
  CHESAPEAKEMONITORINGCOOP: '',
  CHEYENNEWSD1: '',
  CHEYRIVR:
    'Cheyenne River Sioux Tribe (South Dakota) (Tribal) || Cheyenne River Sioux Tribe (South Dakota) (Tribal)',
  CHICKALOONNATIVEVILLAGE_WQX:
    'Chickaloon Native Village (Tribal) || Chickaloon Native Village (Tribal)',
  CHIPCREE_WQX: '',
  CHNEPCHB_WQX: 'Water Quality Monitoring Data',
  CHNEPCHE_WQX:
    'This ORGID refers to data collected in the East Wall of Charlotte Harbor by the Coastal Charlotte Harbor Monitoring Network (CCHMN).  STORET upload was conducted by the Charlotte Harbor Environmental Center with funding from the SWFWMD.',
  CHNEPCHP_WQX:
    'This ORGID refers to data collected in Cape Haze by the Coastal Charlotte Harbor Monitoring Network (CCHMN).  STORET upload was conducted by the Charlotte Harbor Environmental Center with funding from the SWFWMD.',
  CHNEPCHW_WQX:
    'Charlotte harbor National Estuaries Program Water Quality Monitoring Data for the Charlotte Harbor West Wall Stratum',
  CHNEPEB_WQX: 'Water Quality Monitoring Data',
  CHNEPLLB_WQX:
    'This ORGID refers to data collected in Lower Lemon Bay by the Coastal Charlotte Harbor Monitoring Network (CCHMN).  STORET upload was conducted by the Charlotte Harbor Environmental Center with funding from the SWFWMD.',
  CHNEPMP_WQX: 'Water Quality Monitoring Data',
  CHNEPPIS_WQX: 'Water Quality Monitoring Data',
  CHNEPSCB_WQX: 'Water Quality Monitoring Data',
  CHNEPTCR_WQX: 'Water Quality Monitoring Data',
  CHNEPTMR_WQX:
    'This ORGID refers to data collected in the East Wall of Charlotte Harbor by the Coastal Charlotte Harbor Monitoring Network (CCHMN).  STORET upload was conducted by the Charlotte Harbor Environmental Center with funding from the SWFWMD.',
  CHNEPTPR_WQX:
    'This ORGID refers to data collected in the East Wall of Charlotte Harbor by the Coastal Charlotte Harbor Monitoring Network (CCHMN).  STORET upload was conducted by the Charlotte Harbor Environmental Center with funding from the SWFWMD.',
  CHOCNATWQX:
    'The Choctaw Nation of Oklahoma (Tribal) || The Choctaw Nation of Oklahoma (Tribal)',
  CHRISJCHEN: '',
  CITYFTCO_WQX: 'Water Quality Data',
  CITYOFPG_WQX: 'Water Quality Monitoring Data.',
  CITYPUEBLO_WWD: 'Colorado',
  CLACKAMAS_SWCD: 'Current VolMon group',
  CLALLAMCODCD: "Clallam County-DCD || Jamestown S'Klallam Tribe (Tribal)",
  CLALLAMCOUNTYDCD: '',
  CLALLAMCOUNTYEH_WQX: 'Clallam County Environmental Health Services',
  CLEARFIELDCD: '',
  CLINCHVALLEYSWCD_WQX: '',
  CLPWC: 'Volunteer Monitoring Group',
  CMCNRMI_WQX:
    'The Natural Resource Management (NRM) academic program at Colorado Mountain College offers an associate degree in Natural Resource Management.  Students are provided with the opportunity to work on real life environmental projects in class and through paid jobs with the NRM Field Institute. NRM has been involved in over 50 environmental projects partnering with the USFS, USGS, US BLM, USFWS, CPW, and numerous regional and local governments and organizations.',
  CMCPD:
    'The Cape May County Planning Department is the professional arm of the Cape May County Planning Board. The department is responsible for the day to day operations that carry out the functions of the Planning Board.',
  CMP_WQX: 'managed by DE Sea Grant',
  CNA: '',
  CNENVSER:
    'Chickasaw Nation Environmental Service || Chickasaw Nation Environmental Service (Tribal)',
  CNEPWATERPROGRAM: '',
  CNWQD: 'Comanche Nation Water Quality Department',
  COASTALAMERICAFOUNDATION: '',
  COCHITIPUEBLO:
    'Pueblo of Cochiti, New Mexico (Tribal) || Pueblo of Cochiti, New Mexico (Tribal)',
  COCOPAH_INDIAN:
    'Cocopah Tribe of Arizona (Tribal) || Cocopah Tribe of Arizona (Tribal)',
  'COE/ISU_WQX': '',
  COEOMAHA_WQX: 'US Army Corps of Engineers Omaha District',
  COK2014: "Contact Name: Carol O'Donnell-Kee",
  COKORG_WQX: '',
  COLO319: '',
  COLOSU: '',
  COLUMBIA_SWCD: 'Kari Hollander, Current VolMon group',
  CONCORDIA_COLLEGE: 'Concordia College (Minnesota)',
  CONFLUENCE: 'Confluence Compliance Companies, LLC',
  CONNRIVERCONSERVANCY: 'Connecticut River Conservancy',
  CONSERVATION_COMMISSION: 'Oklahoma Conservation Commission',
  COOSWA: 'Volunteer Monitoring Group',
  COQUILLETRIBE_WQX:
    'Coquille Indian Tribe (Tribal) || Coquille Indian Tribe (Tribal)',
  COQUILLE_WA: 'Current VolMon group',
  CORIVWCH_WQX: 'Water Quality Monitoring',
  CORNELLSCALE: '',
  CORTINARANCHERIA_WQX: 'Cortina Rancheria Kletsel Dehe Wintun Nation',
  COYOTEVAL_WQX:
    'Coyote Valley Band of Pomo Indians of California (Tribal) || Coyote Valley Band of Pomo Indians of California (Tribal)',
  CPNWATER:
    'Citizen Potawatomi Nation, Oklahoma (Tribal) || Citizen Potawatomi Nation, Oklahoma (Tribal)',
  CPRW: '',
  CRBC_WQX: 'Suzi Cloutier, Current VolMon group',
  CRITEPO_WQX:
    'Colorado River Indian Tribes of the Colorado River Indian Reservation, Arizona and California (Tribal) || Colorado River Indian Tribes of the Colorado River Indian Reservation, Arizona and California (Tribal)',
  CRITFC_WQX:
    'Nez Perce Tribe of Idaho (Tribal) || Nez Perce Tribe of Idaho (Tribal)',
  CRK_WQX: 'Lorri Epstein',
  CROWCRKS: '',
  CROWNATN: '',
  CRWA: 'Water Quality Monitoring Data',
  CRWC_WQX: 'Crooked River Watershed Council',
  CSAZ: 'City of Scottsdale, Arizona',
  CSC_WQX: '',
  CSH: 'New York',
  CSHH: '',
  CSKTPESTICIDE_WQX:
    'Confederated Salish and Kootenai Tribes of the Flathead Reservation (Tribal) || Confederated Salish and Kootenai Tribes of the Flathead Reservation (Tribal)',
  CSKTRIBE: '',
  'CSR_EPA_CWA-106':
    'Cold Springs Rancheria of Mono Indians of California (Tribal) || Cold Springs Rancheria of Mono Indians of California (Tribal)',
  'CSU-CIVIL&ENVIRONMENTAL-ENG': '',
  CSU_AWQP: '',
  CTA_WQX:
    'Craig Tribal Association (Tribal) || Craig Tribal Association (Tribal)',
  CTCLUSI_WQX: '',
  CTEPO_WQX:
    'Cahuilla Band of Indians - Cahuilla Tribal Environmental Office (Tribal) || Cahuilla Band of Indians - Cahuilla Tribal Environmental Office (Tribal)',
  CTGR: 'Confederated Tribes of the Grand Ronde Community of Oregon (Tribal) || Confederated Tribes of the Grand Ronde Community of Oregon (Tribal)',
  CTGRGOSHUTE: 'Confederated Tribes Of The Goshute Reservation',
  CTSI_WQX:
    'Confederated Tribes of Siletz Indians of Oregon (Tribal) || Confederated Tribes of Siletz Indians of Oregon (Tribal)',
  CTUIR_WQX:
    'Confederated Tribes of the Umatilla Indian Reservation (Tribal) || Confederated Tribes of the Umatilla Indian Reservation (Tribal)',
  CTVOLMON: 'CT DEEP Volunteer Water Monitoring Program',
  CT_DEP01_WQX:
    'This is the central agency for all water quality data in this system',
  CT_NERR: '',
  CURRY_WP: 'Erin Minster - Current VolMon group',
  CUSH: 'Working to eliminate nitrogen pollution, bacterial contamination and plastic waste from our local waters.',
  CUSP: 'CDSN - Coalition for the Upper South Platte',
  CVC: 'Conemaugh Valley Conservancy',
  CWLT_WQX:
    'Cahto Tribe of the Laytonville Rancheria (Tribal) || Cahto Tribe of the Laytonville Rancheria (Tribal)',
  CWQL: '',
  CWSC_WQX: '',
  CWSD_WQX: 'Water Quality Monitoring Data and and SPCURE member',
  DAUPHINCD_WQX: 'Dauphin County Conservation District',
  DCD: 'Dickinson Conservation District',
  'DCRBPI_ WQX':
    'Dry Creek Rancheria Band of Pomo Indians, California (Tribal) || Dry Creek Rancheria Band of Pomo Indians, California (Tribal)',
  DDEH_WQX: 'Water Quality Monitoring Data',
  DEER_CREEK: 'EPA Region 9; ',
  DELACIB: 'Delaware Center for the Inland Bays Water Monitoring Data',
  DELAWARENATION:
    'Delaware Nation, Oklahoma (Tribal) || Delaware Nation, Oklahoma (Tribal)',
  DEMOTEST: 'Test Organization; ',
  DEMOTEST_WQX: 'Department of Natural Resources',
  DENTONWATERSHED_WQX: '',
  DIAL_CORDY_WQX: '',
  DNREC_DOW: '',
  DOEE: 'Water Quality Monitoring Data for all the Waters in the state',
  DRBA: 'Dan River Basin Association',
  DRBC: 'Interstate River Basin Commission',
  DRMPWQX: 'Region 6 - ENIPC - Mescalero Apache Tribe',
  DRMS: 'Colorado Division of Reclamation, Mining and Safety (DRMS), Inactive Mines Program (IMP)',
  DRN: 'Delaware Riverkeeper Network',
  DUCKSU_WQX: '',
  DUCKWATER:
    'Duckwater Shoshone Tribe of the Duckwater Reservation, Nevada (Tribal) || Duckwater Shoshone Tribe of the Duckwater Reservation, Nevada (Tribal)',
  DVSJ: 'Death Valley Timbi-sha Shoshone Tribe (Tribal) || Death Valley Timbi-sha Shoshone Tribe (Tribal)',
  DWH_SCRIBE1082:
    'Surface water and sediment sampling collected in response to the BP Gulf of Mexico Oil Spill',
  EAENGINEERING_WQX: '',
  EBCI: 'Eastern Band of Cherokee Indians (Tribal) || Eastern Band of Cherokee Indians (Tribal)',
  EBR_WQX: 'City of Baton Rouge and Parish of East Baton Rouge',
  ECLS_WQX: 'Environmental and Chemical Laboratory Services ',
  'ECO-WNC': '',
  'ECOLOG&RESEARCH': 'Ecological Logistics & Research Ltd. ',
  ECU_CSI_COASTALPROCESSES: '',
  ECU_ECOL_ENGR: '',
  EFDELRBC_WQX: 'Effluent Data',
  ELEPHANTFISH: 'ElephantFish, LLC',
  ELISS: '',
  ELKVALLEYCA_WQX:
    'Elk Valley Rancheria, California (Tribal) || Elk Valley Rancheria, California (Tribal)',
  ELMONTGOMERY: '',
  ELP12345: '',
  ELWHA1_WQX:
    'Lower Elwha Tribal Community (Tribal) || Lower Elwha Tribal Community (Tribal)',
  ELWHAWQ1_WQX: '',
  EMAP_CS_WQX: 'Coastal',
  EMAP_GRE: '',
  EMSWCD: 'East Multnomah Soil and Water Conservation District',
  EMU_WATER: '',
  ENVIROB1_WQX:
    'Confederated Tribes of the Colville Reservation (Tribal) || Confederated Tribes of the Colville Reservation (Tribal)',
  ENVIROSCIENCEASSOC: '',
  EOR_WQX: '',
  'EPA-C_WQX': 'CBP (TEST/Staging Environment)',
  'EPA-EAID-R3_WQX': '',
  'EPA-FSB-R3_WQX': '',
  'EPA-WPD-R3_WQX': 'EPA Region 3 TMDL Program',
  EPAORD: 'EPA Office of Research and Development',
  EPAORD_WQX: 'EPA Office of Research and Development',
  EPAR2: 'US EPA Region 2 - Clean Water Division',
  EPAR2_USVIBAWQMP_WQX:
    'US Virgin Islands Beach Advisory Water Quality Monitoring Program',
  EPAR5_SLR_WQX: 'Sea Level Rise (SLR) and (http:///www.csc.noaa.gov/slr)',
  EPAR5_WQX: '',
  EPAREG6_WQX: 'US EPA, Region 6 Dallas, TX',
  EPASTAGINGD: 'Volunteer',
  EPATEST: '',
  EPATESTA_PAM: '',
  EPA_GLNPO:
    'Will be used to store the historical GLENDA data that will be added to the WQX in the future.',
  EPA_MPRSAMONITORING: '',
  EPA_OCMA_R1: '',
  EPA_OCMA_R2: '',
  EPA_OCMA_R4: '',
  EPA_OCMA_R6: 'EPA Ocean and Coastal Monitoring Assessment',
  EPA_R2: 'EPA Region 2',
  EPA_R2_EXT: 'EPA Region 2 Volunteer Partners',
  EPA_R7_GRANT_WQX: 'Grantee groups in EPA Region 7',
  EPA_R7_WQX: 'U.S. Environmental Protection Agency',
  EPA_REGION_2: '',
  EPA_WPD_R3: '',
  EPIC_WQX: '',
  EQUILIBRIUM: '',
  ERG: 'Eastern Research Group, Inc.',
  ERMMINNEAPOLIS: '',
  ERWC: '',
  ERWSCC_WQX: '',
  ERWSD: 'Eagle River Water and Sanitation District',
  ESATR08_WQX: 'TechLaw/USEPA ESAT R08 Water Quality Data',
  ESTOO:
    'Eastern Shawnee Tribe of Oklahoma (Tribal) || Eastern Shawnee Tribe of Oklahoma (Tribal)',
  ESTO_WQX: '',
  ETEC: '',
  EVR: 'EVR Operations Limited formerly Teck American Incorporated',
  EXLSTREAM1: 'Appalachian Watershed & Stream Monitors (AWSM) program',
  'FA-NJ': '',
  FAEC: 'Water Quality Monitoring Data',
  FBIC: 'Fort Bidwell Reservation',
  FCPOTAWATOMI_WQX: '',
  FIGRWQP: '',
  FIIR: 'Fort Independence Indian Community of Paiute Indians of the Fort Independence Reservation, California || Fort Independence Indian Community of Paiute Indians of the Fort Independence Reservation, California',
  FLASIOUX: '',
  FLO_SEP: 'City of Florence-Siuslaw estuary Partnership',
  FLO_URBAN: 'City of Florence-Urban Waters Grant; monitoring data',
  FLPRMRWS_WQX: 'Water Quality Monitoring Data',
  FLYGRB: '',
  FMMI: '',
  FMYN_WQX:
    'Fort McDowell Yavapai Nation, Arizona (Tribal) || Fort McDowell Yavapai Nation, Arizona (Tribal)',
  FOB: '',
  FOBWV: 'non-profit conservation organization West Virginia',
  FOCW: 'Restore, preserve, and promote the outstanding natural qualities of the Cheat River watershed.',
  FODC: '',
  FONDULAC_WQX: '',
  FORTLWWTP: 'Colorado',
  FORTMOJAVE: '',
  FORTPECK: '',
  FOSCWQ_WQX: '',
  FOUNSD: 'Colorado',
  FPST: 'Fallon Paiute-Shoshone Tribe;',
  FRESHKILLSPARK: 'Freshkills Park',
  FRESHWATER_INSTITUTE: '',
  FRIENDSOFTHEROUGE: '',
  FRIENDS_BAY: '',
  FRWA: 'Farmington River Watershed Association',
  FSAWQP_WQX: '',
  FSCD: 'Freehold Soil Conservation District',
  FTBLKNAP: '',
  'FWC-CREMP_WQX':
    'Florida Fish and Wildlife Conservation Commission, Fish and Wildlife Research Institute',
  'FWC/FWRI_WQX':
    'Water Quality Monitoring Data: Florida Fish and Wildlife Conservation Commission Fish and Wildlife Research Institute',
  FWCLOCAL_WQX: 'Water Quality Monitoring Data',
  FWC_SGMP_WQX:
    'Water Quality Monitoring Data: entered by the Florida Fish and Wildlife Conservation Commission (Org ID FWC/FWRI)',
  FWC_WQMP_WQX:
    'Water Quality Monitoring Data: entered by the Florida Fish and Wildlife Conservation Commission (Org ID FWC/FWRI)',
  FWS_MATTAMUSKEET: '',
  GARNA: '',
  GBMCASSOC2014: '',
  GBNERR: 'Great Bay National Estuarine Research Reserve Monitoring Data',
  GCRI_WQX: '',
  GCWIN: '',
  GEC_WQX: 'Water Quality Monitoring Data',
  GEI: '',
  GEICON_WQX: 'Water Quality Monitoring Data',
  GENESEECSWCD: '',
  GGCWC: 'Volunteer Monitoring Group',
  GIALANDANDWATER: 'Green Iowa AmeriCorps',
  GILLIAM_SWCD: 'Volunteer Monitoring Group',
  GLC_WQX: '',
  GLEC: '',
  GLENDALE_WQX: 'Water Quality Monitoring Data',
  GLEON: 'GLEON Lake Observer mobile app data',
  GLIFWC: 'Great Lakes Indian Fish and Wildlife Commission',
  GNLK01_WQX: '',
  GPC5_WQX:
    'Grand Portage Band of Lake Superior Chippewa (Minnesota Chippewa Tribes)',
  GPELC: '',
  GPORTAGE_WQX:
    'Minnesota Chippewa Tribe, Minnesota (Six component reservations: Bois Forte Band (Nett Lake); Grand Portage Band;)Tribal || Minnesota Chippewa Tribe, Minnesota (Six component reservations: Bois Forte Band (Nett Lake); Grand Portage Band;)Tribal',
  GRANDENVIROSVS: '',
  GRIC_WQX:
    'Gila River Indian Community of the Gila River Indian Reservation, Arizona (Tribal) || Gila River Indian Community of the Gila River Indian Reservation, Arizona (Tribal)',
  GROTONTOWNWATERQUALITY_WQX: '',
  GROUNDWORKDENVER: '',
  GSWA: 'Great Swamp Watershed Association',
  GTBOCI_WQX:
    'Grand Traverse Band of Ottawa and Chippewa Indians, Michigan (Tribal) || Grand Traverse Band of Ottawa and Chippewa Indians, Michigan (Tribal)',
  GTBWATER_WQX: 'Grand Traverse Band of Ottawa & Chippewa Indians;',
  GTC_WQX:
    'Native Village of Georgetown (Tribal) || Native Village of Georgetown (Tribal)',
  GUAM: '',
  GWCO: 'Groundwater Colorado',
  HALEYALDRICH: '',
  HANALEI_WQX: 'Water Quality Monitoring Data',
  HANNAHWQ_WQX:
    'Hannahville Indian Community, Michigan (Tribal) || Hannahville Indian Community, Michigan (Tribal)',
  HARBORWATCH_WQX: '',
  HAWRIVER03030002: 'Haw River Assembly',
  HAYWOOD_WQX: '',
  HBMI_WQX: ' (Tribal)',
  HDRINC_WQX: '',
  HEDINENV_WQX: '',
  HEMPSTEAD_BAY_WQMP: '',
  HEPD_WQX: '',
  HERRERA_ENVIRONMENTAL: '',
  HI301H_WQX: 'Water Quality Monitoring Datta',
  HIA_WQX:
    'Hoonah Indian Association (Tribal) || Hoonah Indian Association (Tribal)',
  HIEPO_WQX: 'Water Quality Monitoring for TMDL Program',
  HIHAWEHWWTP: '',
  HOFSTRAUML: '',
  HOHTRIBE_WQX: '',
  HOOPERDOB_WQX: 'Hooper Lab, Dept. of Biology, Western Washington',
  HOOSIER: '',
  HOPI_WQX: 'Hopi Tribe of Arizona (Tribal) || Hopi Tribe of Arizona (Tribal)',
  HOPTERA_WQX:
    'Hopland Band of Pomo Indians, California (Tribal) || Hopland Band of Pomo Indians, California (Tribal)',
  HO_CHUNK_WQX: '',
  HPUL1EPA_WQX:
    'Habematolel Pomo of Upper Lake, California (Tribal) || Habematolel Pomo of Upper Lake, California (Tribal)',
  HRF: 'Volunteer Monitoring Group',
  HRWRP_RA: 'Water Quality Monitoring Data',
  HSGMN_WQX: 'Groundwater Data',
  HUALAPAI:
    'Hualapai Indian Tribe of the Hualapai Indian Reservation, Arizona (Tribal) || Hualapai Indian Tribe of the Hualapai Indian Reservation, Arizona (Tribal)',
  HUIWAIOLA_WQX: 'The Nature Conservancy - Honolulu',
  HVA: 'Housatonic Valley Association - Housatonic River Watershed',
  HVTEPA_WQX: '',
  HW: 'Peter Hayes, Current VolMon Group',
  IAAFO_WQX: '',
  IAPEST: '',
  IASNAPST_WQX: 'Water Quality Monitoring Data for all the Waters in the state',
  IDAGMN_WQX: 'Illinois Department of Agriculture',
  IDEQ_CDAOFFICE_WQX:
    'Water Quality Monitoring Data for all the Waters in the state',
  IDEQ_WQX: 'Idaho Dept of Environmental Quality',
  IDNRDFW: 'Water Quality Monitoring Data',
  IDWR: '',
  IEC: '',
  'IEC-NYNJCT': '',
  IHS: 'Indian Health Service;  (Tribal) || Indian Health Service (Tribal)',
  IIDFG: '',
  ILRIVERWATCH: 'Illinois RiverWatch Network',
  IL_EPA_WQX: '',
  INDECON: 'Industrial Economics',
  INSPIRE_WQX: '',
  INSTOR_WQX: 'Indiana Department of Environmental Management',
  INSY_ENVIROMENTAL: '',
  INTRMTN_WQX: 'Superfund',
  IOWACITY_WQX: '',
  IOWAGW_WQX: '',
  IOWAST_WQX:
    'Physical, chemical, and biological data from 45 wetlands in northern Iowa',
  IOWATER_WQX: '',
  IOWATROK_WQX: 'Iowa Tribe of Oklahoma',
  IRONMT_WQX: 'Water Quality Monitoring Data',
  IRWA: 'Ipswich River Watershed Association',
  ISDA_WQX: 'Idaho State Department of Agriculture',
  IVYACADEMY_WQX: '',
  IWLA: 'Izaak Walton League - national conservation organization',
  JA: '',
  JAMUL_WQX: ' (Tribal)',
  JCPH_WQX: '',
  JICARILLAAPACHE:
    'Jicarilla Apache Nation, New Mexico (Tribal) || Jicarilla Apache Nation, New Mexico (Tribal)',
  JMU_ISAT_WQX:
    'a James Madison University research team in association with the Virginia Department of Environmental Quality',
  JRSIMPLOT_FMC: 'J.R. Simplot and FMC Corporation for Gay Mine',
  JSKTRIBE_WQX:
    "Jamestown Sklallam Tribe || Jamestown S'Klallam Tribe (Tribal)",
  KARUKDNR_WQX: 'Karuk Tribe (Tribal) || Karuk Tribe (Tribal)',
  KASHIA:
    'Kashia Band of Pomo Indians of the Stewarts Point Rancheria, California (Tribal) || Kashia Band of Pomo Indians of the Stewarts Point Rancheria, California (Tribal)',
  KATRINA6_WQX: 'Water Quality Data',
  KATSPROJ_WQX: 'Water Quality Monitoring Data.',
  KAWNATON_WQX:
    'Kaw Nation, Oklahoma (Tribal) || Kaw Nation, Oklahoma (Tribal)',
  KAWS_WQX: '',
  KBICNRD_WQX: '',
  KBOPWQP: '',
  KBS: 'Kansas Biological Survey',
  KENAI_NWR: '',
  KENAI_WQX: 'Non profit organization',
  KERBERCREEK: 'Kerber Creek watershed for BLM Natural Resource; ',
  KICKAPOO: '',
  KICKAPOO07: 'Kickapoo Tribe in Kansas;',
  KINGCOENVIROLAB: '',
  KINGCOUNTY: '',
  KIOWA_WQX: 'Kiowa Tribe of Oklahoma; Kiowa Tribe of Oklahoma',
  KITSAPCHD_WQX: '',
  KLAMATHTRIBES_WQX: 'Klamath Tribes (Tribal) || Klamath Tribes (Tribal)',
  KNA: 'Test  WQX with M.Z. credentials.',
  KNRD_WQX:
    'Kalispel Indian Community of the Kalispel Reservation (Tribal) || Kalispel Indian Community of the Kalispel Reservation (Tribal)',
  KOOTENAI_TRIBE_OF_IDAHO_WQX: '',
  KS_GEOWATER_CTR: '',
  KWMNDATA_WQX:
    'The Keystone Watershed Monitoring Network (KWMN) is an umbrella organization for volunteer monitors in Pennsylvania. The mission of the KWMN is to promote volunteer monitoring to protect and improve the quality of Pennsylvania watersheds.',
  KWO: 'Water Quality monitoring and wetland',
  KWO2017: 'Kansas Water Office',
  'KY-EPRIVIA': 'www.eprivia.com  Louisville, KY',
  LACITY: '',
  LADEQWPD_WQX: 'Statewide Water Quality Monitoring Network',
  LAJOLLA:
    'La Jolla Band of Luiseno Indians, California (Tribal) || La Jolla Band of Luiseno Indians, California (Tribal)',
  LAKELAND_WQX:
    'Water Quality Monitoring Sampling and Data keeping for city lakes.',
  LANECOUNCILOFGOVERNMENTS: '',
  LAWRENCEBROOKWW_WQX:
    "This is a group that monitors the Lawrence Brook Watershed chain of water bodies in Middlesex County NJ and includes South Brunswick, North Brunswick, East Brunswick, Milltown, and part of New Brunswick in it's sampling area.",
  LCBP: '',
  LCO106_WQX: 'Water Quality Monitoring Data.',
  LCOWIS_WQX:
    'Lac Courte Oreilles Band of Lake Superior Chippewa Indians of Wisconsin',
  LCWCD_WQX:
    'Lincoln Soil and Water Conservation District *Contact - Audrey Sweet',
  LDEQ319: 'Louisiana Department of Environmental Quality',
  LDFWATER2007: 'Water Quality Monitoring Data.',
  LEECHLAK_WQX: '',
  LEIGHROCKS: 'Contact Name: Leigh Lager',
  LEVELOCK: 'Levelock Village (Tribal) || Levelock Village (Tribal)',
  LEWWTP_WQX: 'Water Quality Monitoring Data',
  LFGC: 'Colorado',
  LFMSDD: 'Colorado',
  LFVC: 'Lake Fork Valley Conservancy of the Gunnison River Valley -  Water quality data collected to assess historic mining impacts to water quality in Henson Creek and other tributaries to the Lake Fork of the Gunnison River',
  LFWS: 'Legacy Water Quality Monitoring Data for Lake Fork of the Gunnison River - LFWS reformed as LFVC in 2011',
  LHC: 'The Lake Hopatcong Commission is an independent State agency overseen by an 11-member board of Commissioners.  The Commission is responsible for conducting, managing and coordinating activities for the preservation, restoration and enhancement of Lake Hopatcong and its watershed.  Members of the Commission work as representatives of the lake community, and are dedicated to permanently preserving the natural, historical and recreational resources of the watershed for this generation and beyond.',
  LISICOS: 'Long Island Sound Integrated Coastal Observing System',
  LOCUS_WQX: 'Locus Technologies',
  LONGTOM_WC: 'Former VolMon group',
  LOSCOYOTESBANDOFCAHUILLACUPENO:
    'Los Coyotes Band of Cahuilla and Cupeno Indians, California (Tribal)',
  LOWERARKVALLEYWATERCONSDIST: '',
  LOWERRARITANWATERSHED: '',
  LPBFSAVEOURLAKE: 'Pontchartrain Conservancy',
  LPEPA106: '(Tribal)',
  LPPSR_WQX:
    'Lone Pine Paiute-Shoshone Reservation (Tribal) || Lone Pine Paiute-Shoshone Reservation (Tribal)',
  LQWA: 'Lake Quinsigamond Watershed Association',
  LRBOI_WQX: '',
  LSFOBLM: '',
  LSIOUX_WQX: '',
  LSUAGBG_WQX: 'LSU AgCenter Botanic Gardens at Burden',
  LSWCD_WQX: 'Audrey Sweet, Current VolMon group',
  LTBBWATR_WQX: '',
  LTENV_WQX: '',
  LUMMINSN_WQX:
    'Lummi Tribe of the Lummi Reservation (Tribal) || Lummi Tribe of the Lummi Reservation (Tribal)',
  LWRBRULE: '',
  MAKAH_WQX:
    'Makah Indian Tribe of the Makah Indian Reservation (Tribal) (BEACH) || Makah Indian Tribe of the Makah Indian Reservation (Tribal)',
  MALHEUR_WC: 'Current VolMon group',
  MAMIN_WQX: 'USEPA (Tribal) || USEPA (Tribal)',
  MANZANITA:
    'Manzanita Band of Diegueno Mission Indians of the Manzanita Reservation, California (Tribal) || Manzanita Band of Diegueno Mission Indians of the Manzanita Reservation, California (Tribal)',
  'MARITIME-PLANNING-WQX': '',
  MARSHALL_WQX: 'Marshall University',
  MASSBAYS: '',
  MASSBAYS01: 'Massachusetts Bays National Estuary Program',
  MASSDEP: 'DWM/WPP',
  MASSWATER_WQX:
    'MassWateR is an R-based data analysis tool developed by MassBays NEP, and used by non-profit environmental organizations across Massachusetts to QA/QC, analyze, and format their data for submission to WQX. There are three custom import configurations as well as sample collection methods designed to facilitate MassWateR users interaction with WQX.',
  MATTOLERESTORATIONCOUNCIL: 'Water Quality Monitoring Data',
  MATTOLE_SALMON: '',
  MAULFOSTER_WQX: '',
  MAWRRC_WQX: 'Massachusetts Water Resources Research Center',
  MAWRWMP:
    'Monitoring of physical, chemical and biological attributes of the Westfield River and some of it tributaries',
  MA_DEP: 'Division of Watershed Management (DWM)',
  MBCI_OEP: '',
  MBMG_WQX:
    'The MBMG_WQX organization is for data collected and stored by the Montana Bureau of Mines and Geology.',
  MCA_WQX: 'Mill Creek Alliance:  https://www.themillcreekalliance.org',
  MCD1913FLOOD: '',
  MCHD: '',
  MCNCREEK_WQX: '',
  MCPH_WQX: 'Mason County Public Health',
  MCWCC_WQX: '',
  MDC: '',
  MDDNR:
    'The Department of Natural Resources leads Maryland toward a sustainable future for our environment, society, and economy by preserving, protecting, restoring, and enhancing natural resources. The data represent key measures of water and habitat quality for living resources such as fish, crabs and oysters. The information is used to guide the restoration of the Chesapeake Bay, its tributaries, and Coastal Bays by identifying specific problems and evaluating the success of management initiatives.',
  MDEDAT01_WQX:
    'Technical and Regulatory Services Administration Data  from HMI sampling',
  MDEDAT03_WQX:
    'Primarily Toxics data used for TMDL development and water quality assessment.',
  MDEDAT05_WQX:
    'contains  MBSS Data etc., Core Trend Benthic input by MDE  and DNR',
  MDEDAT06_WQX:
    'Quantitative Analyis section Data, miscellaneous data that MDE aquired.',
  MDEDAT07_WQX:
    "The State monitors fecal coliform levels as a requirement of the National Shellfish Sanitation Program (NSSP). The Department of the Environment is responsible for classifying and managing Maryland's shellfish harvesting areas. The goal of shellfish harvesting area classification and management is to provide maximum utilization of shellfish resources and to reduce the risk of shellfish-borne illness",
  MDEDAT08_WQX:
    'The BEACH Act was signed into law October 10, 2000. The Beach Act addresses coastal recreational waters and public health risk associated with human contact with potential pathogens in sewage-contaminated waters.',
  MDEDAT09_WQX:
    'Data used for Risk Assessment. Primarily fish, shellfish and crab  tissue contaminant information.',
  MDEDAT10_WQX: '',
  MDEQ_AMP_WQX:
    'Adaptive Management Program means a watershed-scale system that protects water quality from the impacts of nutrient sources by: (a) prioritizing phosphorus reduction, as appropriate, while accounting for site specific conditions, (b) allowing for nutrient sources to be addressed incrementally over time by incorporating flexible decision-making which can be adjusted as management actions and other factors become better understood, (c) reasonably balancing all factors impacting a waterbody...',
  MDEQ_MPDES_WQX:
    'The MDEQ_MPDES_WQX organization is for data associated with MPDES permits.',
  MDEQ_REM_WQX:
    "The MDEQ_REM_WQX organization is for data associated with DEQ's Remediation Division.",
  MDEQ_WQ_WQX:
    "The MDEQ_WQ_WQX organization is for data collected by DEQ's Water Quality Planning Bureau (WQPB).",
  MDE_EASP: 'Environmental Assessment and Standard Program Data',
  MDE_FIELDSERVICES_WQX:
    'Data collected by MDEs field office for different surveys, mostly TMDL initiatives.  It mainly consists of physical parameters, chlorophyll, nutrients, BOD and sediments.  There are some coliform (bacteria) data; also, elements associated with mining.',
  MDE_FSP: '',
  MDE_STORMWATER: 'MDE Stormwater data',
  MDE_TMDL: 'TMDL Technical Development Program data',
  MDE_WQPR:
    'Water Quality Monitoring  Data,Maryland Department of the Environment 319 Program',
  MDNR: '',
  MDO: '',
  MDPOINTSOURCE:
    "Discharge monitoring reports (DMRs) and monthly operating reports (MORs) for the 58 major WWTPs, 215 minor WWTPs, and 10 major industrial point sources within the State of Maryland and are stored in MDE's point source database.  This data set contains results for nutrients such as phosphorous and nitrogen that may impact water quality in the Chesapeake Bay.",
  MEC: '',
  MEDEP_WQX: 'Maine Dept of Env Protection.',
  MEIYINWUSUNYPLATTSBURGH: '',
  MENOM_WQX: '',
  MERRIMACK_RIVER_WATERSHED_WQX: '',
  MESKWAKI_DNR:
    'Meskwaki Department of Natural Resources (Tribal) || Meskwaki Department of Natural Resources (Tribal)',
  METC_WQX: 'Metropolitan Council (Minnesota)',
  MHA_NATN: '',
  MHA_WQX:
    'Three Affiliated Tribes of the Fort Berthold Reservation, North Dakota (Tribal) || Three Affiliated Tribes of the Fort Berthold Reservation, North Dakota (Tribal)',
  MIAMITRIBEOFOKLAHOMA: '',
  MIDCOWATERSHED:
    'The Middle Colorado Watershed Council (MCWC) is a 501c(3) nonprofit organization whose mission is to evaluate, protect and enhance the health of the Middle Colorado River Watershed through the cooperative effort of watershed stakeholders',
  MIDDLEDESCHUTES_WC: 'Volunteer Organization',
  MIDDLESPRINGWATERSHED: '',
  MIDDLETOWNUPCW_WQX:
    'Middletown Rancheria of Pomo Indians of California (Tribal) || Middletown Rancheria of Pomo Indians of California (Tribal)',
  MIDEWIN:
    'United States National Grassland operated by the United States Forest Service',
  MIDNITE_2: '',
  MILLERCOORS: 'MillerCoors is a member of SPCURE',
  MITCR_WQX:
    'Mechoopda Indian Tribe of Chico Rancheria, California (Tribal) || Mechoopda Indian Tribe of Chico Rancheria, California (Tribal)',
  MIT_WQX:
    'Muckleshoot Indian Tribe (Tribal) || Muckleshoot Indian Tribe (Tribal)',
  MKIESER: '',
  MLBO_DNR_WQX: '',
  MNDA_PESTICIDE: 'Statewide monitoring, non-facility',
  MNDNR_AGW: 'Statewide ambient groundwater monitoring, non-facility',
  MNISOSE07:
    'Mni Sose Intertribal Water Rights Coalition (Tribal) || Mni Sose Intertribal Water Rights Coalition (Tribal)',
  MNPCA: 'Statewide ambient surface water monitoring, non-facility',
  MNPCA1_WQX: 'Water Quality Monitoring Data for all the Waters in the state',
  MNPCAB_WQX: 'Water Quality Monitoring Data for all the Waters in the state',
  MNPCA_AGW: 'Statewide ambient groundwater monitoring, non-facility',
  MNPCA_BIO:
    'Statewide ambient surface water monitoring to support the biological monitoring program, non-facility',
  MOAPA_WQX:
    'Moapa Band of Paiute Indians of the Moapa River Indian Reservation, Nevada (Tribal) || Moapa Band of Paiute Indians of the Moapa River Indian Reservation, Nevada (Tribal)',
  MOBILEBAYNEP_WQX: '',
  MONT_DEQ_WQX:
    'The MONT_DEQ_WQX organization is a static, historic dataset with the majority of data originating from the Storease database.',
  MONT_PPL_WQX:
    'The MONT_PPL_WQX organization is for data collected by PPL Montana.',
  MOOREINSTITUTEPLASTICPOLLUTION_WQX: '',
  MOORETOWNEPO: 'Mooretown Rancheria (Tribal) || Mooretown Rancheria (Tribal)',
  MORONGO1_WQX: '',
  MOTE_WQX: '',
  MOUNTOLIVETOWNSHIP: '',
  MPSLML: 'Marine Pollution Studies Lab at Moss Landing Marine Laboratories,',
  MRC: 'Monitoring coalition w/ an approved QAPP through the SC Development of Health and Environmental Control',
  'MRRI-NJSEA':
    'Meadowlands Research & Restoration Institute, Our mission is to provide the scientific community, policy makers, and the public with the knowledge and predictive understanding necessary to conserve, protect, and manage the District ecosystems and the services they provide.',
  MRSENVMB_WQX: 'NPDES Monitoring Data',
  MRWA: 'Musconetcong River Watershed Association',
  MSI: 'Mountain Studies Institute (MSI) is an independent not-for-profit mountain research and education center established in 2002 in Silverton, Colorado. MSI develops science that people can use to address environmental issues facing the San Juan Mountains. We conduct and facilitate research, provide educational opportunities and internships, and conduct environmental monitoring. We connect scientists and stakeholders across the San Juan Mountain region to go beyond scientific inquiry to the meaning',
  MSU: '',
  MSUEXT_GC_WQX: 'Montana State University Extension - Gallatin County',
  MSWCD_WQX:
    'Malheur Soil and Water Conservation District (SWCD) *Contact - Gary Faw',
  MT305B_SECONDARYDATA:
    'The MT305b_SecondaryData organization is for data submitted to the Montana Water Quality Planning Bureau during calls for "all existing and readily available water quality-related data and information" per the federal Clean Water Act and 40 CFR 130.7 (5).  These data were not collected by or explicitly for Montana DEQ\'s WQPB.',
  MTNWE:
    'The MTNWE organization is for data collected and managed by NorthWestern Energy.',
  MTVOLWQM_WQX:
    'The MTVOLWQM_WQX organization is for data collected by volunteer organizations, groups, or individuals that are not operating under a DEQ approved QAPP/SAP.',
  MTWTRSHD_WQX:
    'The MTWTRSHD_WQX organization is for data collected externally from DEQ, but using grant monies such as 319 or 106 or managed under a DEQ approved QAPP/SAP.',
  MUSCOGEE_CREEK:
    'The Muscogee (Creek) Nation (Tribal) || The Muscogee (Creek) Nation (Tribal)',
  MUSCONETCONGORG_WQX: '',
  MWA1: 'The Musconetcong Watershed Association (MWA) is a non-profit organization incorporated in 1992 to protect and enhance the Musconetcong River and its related resources. MWA members are part of a network of individuals, families and organizations that care about the Musconetcong River and its watershed.',
  MWRA_WQX: 'MWRA/ Environmental Quality Department',
  MWRDSTOR_WQX:
    'Water Quality Monitoring: 100 East Erie Street, Chicago, IL 60611  (312) 751-5600',
  MWRD_WQX: 'Water Quality Monitoring Data and SPCURE member',
  MWT: '',
  MYRWA: 'Water Quality Monitoring Data',
  NALMS: 'Volunteer',
  NAMBEPBLO_WQX: 'Pueblo of Nambe, NM',
  NANTICOKEWTRALL_WQX: '',
  NARSTEST: '',
  NARS_WQX: '',
  NCADH: 'North Carolina Aquatic Data Hub',
  NCSWCD: '',
  NCUSGS: '',
  NCWA_WQX: 'North Coast Watershed Association',
  NCWCD: 'Water Quality Monitoring Data.',
  NCWQR: '',
  NEIARCD_WQX: '',
  NEIWPCC: '',
  NEKCKGREENTEAMGROUNDWORKNRG: '',
  NEWRIVERCONSERVANCY: 'New River Conservancy',
  NEZPERCETRIBE_WQX: 'Nez Perce Tribe (Tribal) || Nez Perce Tribe (Tribal)',
  NFRIA: 'Water Quality Monitoring Data',
  NGRREC_GREON:
    'Continuous water quality monitoring along the rivers and reservoirs in Illinois and the Mississippi River',
  NIAMLARB1_WQX: '',
  NISQUALLY:
    'Nisqually Indian Tribe (Tribal) || Nisqually Indian Tribe (Tribal)',
  NIT_WQX: 'Narragansett  Indian Tribe',
  NJCSO: 'NJCSO Group',
  NJDEPNJWAP: 'NJDEP, NJ Watershed Ambassador Prog',
  NJDEPRS: 'NJDEP Reference Sites',
  NJDEPVMG: 'NJDEP Volunteer Monitoring Group',
  NJDEP_AMERICORPS:
    'The New Jersey Watershed Ambassadors Program is a community-oriented AmeriCorps environmental program designed to raise awareness about watershed issues in New Jersey. Watershed Ambassadors monitor the rivers of New Jersey by visual and biological volunteer monitoring program. The members also train community volunteers and teach them to use these two volunteer monitoring techniques.',
  NJDEP_BB: '',
  NJDEP_BB_TEST: '',
  NJDEP_BEARS:
    "The purpose of the Bureau of Environmental Analysis and Restoration (BEAR) will be to support the Division's mission through the development of technical tools for implementation by the Division. This will be accomplished through the completion of Established TMDLs and the revision and development of a Stream Corridor Ordinance, Well Head Protection Ordinance and an Enhanced MS4 Ordinance.",
  NJDEP_BFBM:
    "The Bureau is responsible for monitoring the ambient conditions of the state's fresh and ground water resources. This monitoring includes regular statewide sampling through of 115 surface water monitoring stations, 820 benthic macroinvertebrate stream monitoring stations, 100 fish assemblage stream monitoring stations, and 150 ground water stations.",
  NJDEP_BMWM:
    "The Bureau is responsible for water quality monitoring used to classify approximately 700,000 acres of marine and estuarine shellfish waters, In this regard, approximately 15,000 ambient water samples are collected yearly from a 4,000 station sampling network. All of these samples are analyzed at the Bureau's southern regional DEP laboratory. In addition, the bureau oversees both the Beach Monitoring and the Clean Shores programs.",
  NJDEP_BSWP:
    'The Bureau of Surface Water Permitting regulates facilities discharging domestic and industrial wastewater directly into surface waters of the state as part of the NJPDES program.\nPermittees include various industries, federal, state, county, and municip',
  NJDEP_BWQSA:
    'The Bureau of Water Quality Standards and Assessment is responsible for water quality assessments of all waters of the State and the New Jersey Integrated Water Quality Monitoring and Assessment Report.',
  NJDEP_DSREH:
    "The Division of Science, Research and Environmental Health (formerly the Office of Science and previously the Division of Science, Research and Technology) is the New Jersey Department of Environmental Protection's (DEP) primary scientific research and technical support unit. The role of this division, through its studies, evaluations and monitoring efforts, is to provide DEP with a sound technical foundation upon which to base the department's policy and regulatory decisions.",
  NJDEP_OS_TEST: 'Contact Name: Tom McKeon',
  NJDEP_PESTICIDES: '',
  NJHDG:
    'Nine northeastern NJ wastewater treatment agencies working collaboratively on water quality issues in the NY/NJ Harbor Estuary.',
  NJMC: '',
  NJPC: 'The New Jersey Pinelands Commission is an independent state agency whose mission is to "preserve, protect, and enhance the natural and cultural resources of the Pinelands National Reserve, and to encourage compatible economic and other human activities consistent with that purpose."',
  NJRCD:
    'The Resource Conservation and Development Program was initiated in 1962 to help people care for and protect their natural resources to improve the economy, environment, and living standards of an area.  Our mission is to facilitate the transition to sustainable use and protection of human and natural resources in the region through partnerships, education, and innovation.',
  NJWAP: '',
  NJWSA: '',
  NJ_MSU: '',
  NKUWATER_WQX:
    'Water Quality Monitoring Data:Consortia working with local groups including the Licking Watershed Watch.',
  NMBGMR: '',
  NMW_WQX: '',
  NNB: 'Volunteer Monitoring Group',
  NNEPA:
    'Navajo Nation, Arizona, New Mexico & Utah (Tribal) || Navajo Nation, Arizona, New Mexico & Utah (Tribal)',
  NOAA_CORALREEFS_WQX: '',
  NOMEESKIMO_WQX:
    'Nome Eskimo Community (Tribal) || Nome Eskimo Community (Tribal)',
  NOOKSACK_WQX: '',
  NORMANDEAUASSOC: 'Normandeau Associates Inc.',
  NOTTAWHURON_WQX: '',
  NRTHCHEY: 'Environmental Protection Department',
  NRWA_WQX: 'Water Quality Monitoring Data',
  NRWC: '',
  NSEA: 'The Nooksack Salmon Enhancement Association is a community based nonprofit dedicated to restoring wild salmon populations in Whatcom County.',
  NSQS: 'blah',
  NSRWA: 'North and South Rivers Watershed Association',
  NTEMPLE_WQX: 'Water Quality Data',
  NTHRNUTE: '',
  NVC_WQX:
    'Native Village of Council (Tribal) || Native Village of Council (Tribal)',
  NVEPA_WQP:
    'Navajo Nation, Arizona, New Mexico & Utah (Tribal) || Navajo Nation, Arizona, New Mexico & Utah (Tribal)',
  NWIFC_WQX:
    'Northwest Indian Fisheries Commission (Tribal) || Northwest Indian Fisheries Commission (Tribal)',
  NWRSFWS_WQX: '',
  OARS: 'OARS - For the Assabet Sudbury & Concord Rivers',
  OCC: 'The OCC organization is for data associated with the Otter Creek watershed, specifically with the Otter Creek Coal area.',
  OCDWEP_WQX: 'Onondaga County Department of Water Environment Protection',
  OCSN: '',
  OESERLSCA_WQX:
    'Region 10: Oeser Property, Little Squalicum Creek Area, Bellingham, WA',
  OGLALAST: '',
  OHDDAGW:
    'Ambient water quality program in OH Division of Drinking and Ground Waters',
  'OH_KY_IN-WSC': 'Continuous Water Quality Data',
  OISC_WQX:
    'Office of Indiana State Chemist has regulatory authority for use of pesticides, nutrients, feed, and seeds in Indiana',
  OKCONCOM_WQX: 'Water Quality Monitoring Data for all the Waters in the state',
  OKCORCOM_WQX: 'Water Quality data submitted by ODEQ',
  OKDAFF_WQX: 'Water Quality data submitted by ODEQ',
  OKDEQ_WQX: '',
  'OKWRB-GMAP_WQX': 'OKWRB use internally for groundwater monitoring',
  'OKWRB-LAKES_WQX': '',
  'OKWRB-STREAMS_WQX':
    'Oklahoma Water Resources Board Streams and Rivers Monitoring',
  OKWRB_WQX: 'Water Quality',
  OLMS: "Non-profit dedicated to the protection of Ohio's lakes and their watershed",
  ONEIDA_WQX: 'Oneida Nation',
  OOPBLO: 'Pueblo of Ohkay Owingeh, New Mexico',
  ORACWA_WQX: '',
  ORDNRMRLSTD_GI:
    'USEPA Office of Research and Development, National Risk Management Research Laboratory',
  OREGONDEQ: '',
  OREGONODA_WQX: '',
  OSAGENTN: 'The Osage Nation (Tribal) || The Osage Nation (Tribal)',
  OSAGENTN_WQX: 'The Osage Nation (Tribal) || The Osage Nation (Tribal)',
  OST_SHPD: '',
  OST_SHPD_TEST: '',
  'OSU-OOIEA': "Ocean Observatories Initiative's Endurance Array",
  OSU_NREM_WQX: '',
  OTIE: '',
  OTN_WQX: '',
  OTTAWATRIBEOFOK: '',
  OVIWC: '',
  O_MTRIBE_WQX: '',
  P4_PRODUCTION_IDAHO: 'P4 Production LLC, Soda Springs Plant, Idaho',
  PACOG_WQX: '',
  PADDLEFISH: '',
  PADEP319_WQX: 'Department of Environmental Protection 319 Program',
  PADEPLAKE_WQX: '',
  PALABAND:
    'Pala Band of Mission Indians (Tribal) || Pala Band of Mission Indians (Tribal)',
  PALERMOWELLFIELD_CH2M: 'Palermo Wellfield Superfund Site water quality data',
  PALERMOWELLFIELD_WQX: '',
  PASSAMAQUODDYSIPAYIKENV:
    'Passamaquoddy Tribe (Tribal) || Passamaquoddy Tribe (Tribal)',
  PATCMON_WQX: 'Potomac Appalachian Trail Club Volunteer Monitoring - VA,MD; ',
  PAUMATRIBE:
    'Pauma Band of Luiseno Mission Indians of the Pauma &amp; Yuima Reservation, California (Tribal) || Pauma Band of Luiseno Mission Indians of the Pauma &amp; Yuima Reservation, California (Tribal)',
  PBDNR: 'Pokagon Band of Potawatomi Indians Department of Natural Resources;',
  PBWC_WQX: 'Powder Basin Watershed Council *Contact - Christopher Morris',
  PCCB_WQX: 'Polk County Conservation Board (Polk County, Iowa)',
  PCSWD: '',
  PCWA: 'Pompeston Creek Watershed Association',
  PDHP7L: 'Park District of Highland Park',
  PECHANGA_WQX:
    'Pechanga Band of Luiseno Mission Indians of the Pechanga Reservation, California (Tribal) || Pechanga Band of Luiseno Mission Indians of the Pechanga Reservation, California (Tribal)',
  PENOBSCOTINDIANNATIONDNR: 'Penobscot Indian Nation',
  PEORIAWATER: '',
  PGSTNATR_WQX:
    "Port Gamble S'Klallam Tribe (Tribal) || Port Gamble S'Klallam Tribe (Tribal)",
  PHINIZYCENTERFORWATERSCIENCES: '',
  PIBO_MP: '',
  PICAYUNERANCHERIACWA106:
    'Picayune Rancheria of Chukchansi Indians of California (Tribal) || Picayune Rancheria of Chukchansi Indians of California (Tribal)',
  PICEANCE_LDR: 'Piceance Basin Colorado',
  PICURIS_PUEBLO: 'Picuris Pueblo',
  PIIC_WQX: '',
  PIMA_AZ: '',
  PLYMOUTHDMEA: 'Plymouth Department of Marine and Environmental Affairs',
  PNDECS_WQX:
    'Pawnee Nation of Oklahoma (Tribal) || Pawnee Nation of Oklahoma (Tribal)',
  POARCHCRK_WQX: 'Poarch Band of Creek Indians;',
  POLSWATER_WQX: 'Pueblo of Laguna',
  POMO989_WQX: ' (Tribal)',
  PONCA_TRIBE_WQX: '',
  PORTGRAHAM:
    'Port Graham Village Council (Tribal) || Port Graham Village Council (Tribal)',
  PORTLANDHARBORRISS: 'City of Portland',
  POTTERVALLEYTRIBE: '',
  PPNPROGRAM:
    'Pinoleville Pomo Nation, California (Tribal) || Pinoleville Pomo Nation, California (Tribal)',
  PRAIRIEBAND:
    'Prairie Band Potawatomi Nation (Tribal) || Prairie Band Potawatomi Nation (Tribal)',
  PRCI_WQX:
    'Picayune Rancheria of the Chukchansi Indians (Tribal) || Picayune Rancheria of the Chukchansi Indians (Tribal)',
  PRCWA:
    'Non-profit organization dedicated to promoting the restoration and protection of the waters and environment of the Parker River and Plum Island Sound Watersheds',
  PREEM: '',
  PREP: 'Piscataqua Region Estuaries Partnership',
  PREQB_GW_WQX: 'Water Quality Monitoring Data for all the Waters in the state',
  PRINCETONHYDRO: 'Environmental consulting company based in Trenton, NJ',
  PRTWQX:
    'Pit River Tribe, California: XL Ranch, Big Bend, Likely, Lookout, Montgomery Creek and Roaring Creek Rancherias (Tribal) || Pit River Tribe, California: XL Ranch, Big Bend, Likely, Lookout, Montgomery Creek and Roaring Creek Rancherias (Tribal)',
  PR_BEACH_WQX:
    'The purpose of the Puerto Rico Environmental Quality Board is the Environmental Protection of pollution problem in Puerto Rico',
  PR_COAST_WQX: 'Water Quality Monitoring Data for all the Waters in the state',
  PR_LAKES_WQX: '',
  PR_RIVER_WQX: 'Water Quality Monitoring Data',
  PSUCLR: '',
  PTI_ITS_WQX: 'Passamaquoddy Tribe (Tribal) || Passamaquoddy Tribe (Tribal)',
  PTMSC: 'Non-profit marine science education',
  PUEBLOISLETA: 'Pueblo of Isleta;',
  PUEBLOJEMEZ: 'Pueblo of Jemez',
  PUEBLOOFTESUQUE: 'Pueblo Of Tesuque || Pueblo Of Tesuque (Tribal)',
  PUEBLOWMD: 'Colorado',
  PUEBLO_POJOAQUE: 'Pueblo of Pojoaque Environment Department',
  PUEBLO_SANTAANA: '',
  PUJ: '',
  PUR_WQX: 'Joe Carnes, Current VolMon group',
  PUYALLUP_WQX:
    'Puyallup Tribe of Indians (Tribal) || Puyallup Tribe of the Puyallup Reservation (Tribal)',
  PYRAMIDLAKE:
    'Pyramid Lake Paiute Tribe of the Pyramid Lake Reservation, Nevada (Tribal) || Pyramid Lake Paiute Tribe of the Pyramid Lake Reservation, Nevada (Tribal)',
  QIN_WQX: 'Quinault Indian Nation (Tribal) || Quinault Indian Nation (Tribal)',
  QTEO_WQX: '(Tribal)',
  QUAPAWTR_WQX:
    'The Quapaw Tribe of Indians (Tribal) || The Quapaw Tribe of Indians (Tribal)',
  QUECHAN_WQX:
    'Quechan Tribe of the Fort Yuma Indian Reservation, California &amp; Arizona (Tribal) || Quechan Tribe of the Fort Yuma Indian Reservation, California &amp; Arizona (Tribal)',
  QUILEUTE_WQX: '',
  QVIR: 'Quartz Valley Indian Community of the Quartz Valley Reservation of California (Tribal) || Quartz Valley Indian Community of the Quartz Valley Reservation of California (Tribal)',
  R0910: '',
  R10BLACKBUTTEMINE:
    'The Black Butte Mine is a former mercury mine located in southern Lane County in the Coast Fork Willamette River Basin.',
  R10BOOMSNUB:
    'Boomsnub -  BOC Gases Superfund Site Data 1987-2013 Loaded by EPA Region 10',
  R10BUNKER:
    "Bunker Hill Mining and Metallurgical Complex and Coeur d'Alene Basin, Kellogg, ID",
  R10DUWAMISH:
    "The Lower Duwamish Waterway Superfund site is a 5.5 mile stretch of the Duwamish River that flows into Elliott Bay in Seattle, Washington. The waterway is flanked by industrial corridors, as well as the South Park and Georgetown neighborhoods. The site was added to EPA's National Priorities List in 2001. Pollutants in the sediments include polychlorinated biphenyls or PCBs, dioxins/furans, carcinogenic polycyclic aromatic hydrocarbons or cPAHs, and arsenic.",
  R10ELKHEADMINE: 'Elkhead Mine Soil Sampling, Douglas County OREGON',
  R10ERU10EK: '',
  R10MIDNITE:
    'EPA Region 10 Superfund Midnite Mine Site || Spokane Tribe of the Spokane Reservation (Tribal)',
  R10NPDES: 'Monitoring data collected by or for NPDES-permitted facilities.',
  R10NWPIPEANDCASING:
    'Northwest Pipe and Casing Company-Hall Process Company Superfund Site, Milwaukie, OR; RI and Post-RI data set assembled by Weston and delivered to EPA in Access97 format, date range 7/1/88 - 4/6/99.',
  R10OEA:
    'Various studies performed by or for US EPA Region 10, Office of Environmental Assessment',
  R10PORTLANDHARBOR:
    'Portland Harbor is located in and along the Willamette River in Portland, Oregon. More than a century of historical industrial use has resulted in Willamette River sediments being contaminated with many hazardous substances, such as heavy metals, polychlorinated biphenyls (PCBs), polynuclear aromatic hydrocarbons (PAH), dioxin/furans, and pesticides. The investigation area currently extends from the Columbia Slough to the Fremont Bridge.',
  R10SUMASMOUNTAIN:
    'Investigation of asbestos contamination; sampling along Swift Creek and the Sumas River, near the town of Nooksack, in Whatcom County, Washington.',
  R10SUPERFUNDHISTORICAL: 'EPA Region 10 Superfund Historical Data',
  R10UPPERCOLUMBIA:
    'Remedial Investigation and Feasibility Study (RI/FS) of hazardous waste contamination in the Columbia River from the U.S./Canada border to the Grand Coulee Dam. River and lake sediment contamination includes heavy metals such as cadmium, copper, lead, mercury and zinc, and dioxins and furans.',
  R10YROADLANDFILLS:
    'Y-Road Landfills Superfund Site Inspection Groundwater Monitoring Data, Bellingham, WASHINGTON, May 2004',
  R2_LAB_WQX: '',
  R4ATHENS_WQX: '',
  R4WPD: '',
  R8MONTWQ:
    'The R8MONTWQ organization is for data collected under EPA Region 8 projects.  The EPA Montana office is the "owner" of this organziation.',
  R9VOL_WQX: 'Water Quality Monitoring Data',
  RAMONA:
    'Ramona Band of Cahuilla, California (Tribal) || Ramona Band of Cahuilla, California (Tribal)',
  RCA: '',
  'RCE WRP':
    'The Rutgers Cooperative Extension (RCE) is an integral part of the School of Environmental and Biological Sciences, the New Jersey Agriculture Experiment Station (NJAES), and Rutgers, The State University of New Jersey.  RCE focuses on issues and needs relating to agriculture and the environment; management of natural resources; food safety, quality, and health; family stability; economic security; and youth development.',
  RCESLM:
    'Ramsey County Environmental Services, Lake Management Surface Water Quality',
  'REDCLAYSTATEPARK-TN': '',
  REDCLIFF_WQX: '',
  REDDINGRANCHERIA_WQX:
    'Redding Rancheria, California (Tribal) || Redding Rancheria, California (Tribal)',
  REDLAKE_WQX: '',
  REVIVETHESANJOAQUIN_WQX: '',
  RFC: 'Founded in November 1996, Roaring Fork Conservancy is the watershed conservation organization in the Roaring Fork Valley that brings people together to protect our rivers. As an independent, not-for-profit 501(c)3 organization our mission is to inspire people to explore, value, and protect the Roaring Fork Watershed. From Aspen to Glenwood Springs, Meredith to Marble, Roaring Fork Conservancy is focused on: water quantity and water quality.',
  RGHRP: '',
  RHA: 'Raritan Headwaters Association',
  RIDEM: 'RIDEM',
  RITA6_WQX: 'Hurricane Rita Water Quality Data',
  RIVERKEEPER:
    'Riverkeeper is a member-supported watchdog organization dedicated to defending the Hudson River and its tributaries and protecting the drinking water supply of nine million New York City and Hudson Valley residents.',
  RIVERSUNLIMITED: 'Volunteers',
  RM11E_SUPRIFS:
    'This data was collected as part of the Supplemental Remedial Investigation/Feasibility Study (RI/FS) conducted along the east side of the Willamette River between approximately River Mile (RM) 10.9 and RM 11.6 (referred to as RM11E) in Portland, Oregon. The results were uploaded by GSI Water Solutions, Inc. on behalf of the RM11E Group,  including Cargill, Inc., CBS Corporation, the City of Portland, DIL Trust, Glacier Northwest, Inc., and PacifiCorp.',
  ROBINSONRANCHERIAENVIRONMENTAL:
    'Robinson Rancheria (Tribal) || Robinson Rancheria (Tribal)',
  ROCKBRIDGE_WQX: '',
  ROSEBUDSIOUXTRIBE: 'Rosebud Sioux Tribe',
  ROUNDVALLEY:
    'Round Valley Indian Tribes, Round Valley Reservation, California (Tribal) || Round Valley Indian Tribes, Round Valley Reservation, California (Tribal)',
  RPI: '',
  RPI_SCALE: '',
  RREPA_WQX:
    'Resighini Rancheria, California (Tribal) || Resighini Rancheria, California (Tribal)',
  RRK_WQX: 'Rogue Riverkeeper',
  RRWC_WQX:
    'Sarah Sauter, Current VolMon group, Includes Little Butte/Upper Rogue and Middle Rogue Watershed Council data from LASAR',
  RTI: 'http://www.rti.org/',
  RU_MUSC: 'Water Quality Monitoring Project for Musconetcong River',
  RVCG: 'Greg Stabach, Current VolMon group',
  RVRPOMO: '',
  SACFOXMO:
    'Sac & Fox Nation of Missouri in Kansas and Nebraska (Tribal) || Sac & Fox Nation of Missouri in Kansas and Nebraska (Tribal)',
  SACWSD_WQX: 'Water Quality Monitoring Data',
  SAGIN01_WQX:
    'Saginaw Chippewa Planning Department (MI); Water Qulaity Monitoring Data.',
  SAINTVSD: 'Colorado',
  SALTCHUCK_WQX: '',
  SAMISHINDIAN_WQX: '',
  SANBERNARDINONATIONALFOREST: '',
  SANCARLOSAPACHETRIBE:
    'San Carlos Apache Tribe of the San Carlos Reservation, Arizona (Tribal) || San Carlos Apache Tribe of the San Carlos Reservation, Arizona (Tribal)',
  SANDIAWQ_WQX: 'Pueblo of Sandia Water Quality Program (New Mexico)',
  SANFELIPE_WQX: 'San Felipe Pueblo, NM',
  SANILDEFONSODECP:
    'San Ildefonso Pueblo, NM (Tribal) || San Ildefonso Pueblo, NM (Tribal)',
  SANMANUEL:
    'San Manuel Band of Mission Indians, California (Tribal) || San Manuel Band of Mission Indians, California (Tribal)',
  SANMATEORCD: 'San Mateo Resource Conservation District',
  SANPASQUAL:
    'San Pasqual Band of Diegueno Mission Indians of California (Tribal) || San Pasqual Band of Diegueno Mission Indians of California (Tribal)',
  SANTACLARAPBLO: 'Pueblo of Santa Clara',
  SANTAROSA:
    'Santa Rosa Indian Community of the Santa Rosa Rancheria, California || Santa Rosa Indian Community of the Santa Rosa Rancheria, California (Tribal)',
  SANTEEWATER:
    'Santee Sioux Nation of Nebraska (Tribal) || Santee Sioux Nation of Nebraska (Tribal)',
  SAUKSUIATTLE:
    'Sauk-Suiattle Indian Tribe || Sauk-Suiattle Indian Tribe (Tribal)',
  SAULTSTEMARIE: '',
  SBITENV_WQX:
    'Shoaltwater Bay Tribe (Washington) (Tribal) || Shoalwater Bay Indian Tribe of the Shoalwater Bay Indian Reservation (Tribal)',
  SBMWA: 'Stony Brook-Millstone Watershed Association',
  SBS: '',
  SBWA: 'South Branch Watershed Assoc',
  SBWA1: 'South Branch Watershed Association-WQDE version phone-908-782-0422',
  SBWC_WQX: 'Pat Welle, Current VolMon group',
  'SC&LRWC': '',
  'SC-NJ': 'Sourland Conservancy, Water Quality Monitoring',
  SCAPED: '',
  SCCRK: 'South Carolina Congaree RiverKeeper',
  SCCWK: 'South Carolina Charleston WaterKeeper',
  SCDHSECOLOGY: '',
  SCEQ: '',
  SCI: '',
  SCWA: '',
  SDCKWMG_WQX: 'Water Quality Monitoring Data',
  SDDENR_WQX: 'Department of Natural Resources',
  SDGEO_WQX: 'Water Quality',
  SDJSA:
    'The Silverthorne/Dillon Joint Sewer Authority is a municipal wastewater treatment facility serving the Towns of Silverthorne and Dillon as well as the areas of Dillon Valley, Buffalo Mountain and Mesa Cortina.',
  SEAQ: '',
  SEATTLERIVER_WQX:
    'river sediment chemistry results collected for the City of Seattle.',
  SELDOVIA:
    'Seldovia Village Tribe (Tribal) || Seldovia Village Tribe (Tribal)',
  SENECA_WQX: '',
  SFBED_WQX: 'South Fork Band Environmental Department',
  SFEI: '',
  SFNOES_WQX: ' (Tribal)',
  SHELLYAB_WQX: 'Water Quality Monitoring Data.',
  SHINGLESPRINGS_WQX: 'Shingle Springs Band of Miwok Indians UNREGISTERED',
  SHOPAITR_WQX:
    'Shoshone-Paiute Tribes of the Duck Valley Reservation, Nevada (Tribal) || Shoshone-Paiute Tribes of the Duck Valley Reservation, Nevada (Tribal)',
  SHOSHONE_BANNOCK: 'Shoshone Bannock Tribes',
  SHOSHONE_BANNOCK_WQX:
    'Shoshone-Bannock Tribes of the Fort Hall Reservation (Tribal) || Shoshone-Bannock Tribes of the Fort Hall Reservation (Tribal)',
  SIR_WQX:
    'Susanville Indian Rancheria, California (Tribal) || Susanville Indian Rancheria, California (Tribal)',
  SITC_SF:
    'Swinomish Indian Tribal Community Shellfish (Tribal) || Swinomish Indian Tribal Community (Tribal)',
  SIUSLAW: 'Kyle Terry, Current VolMon group',
  SIUSLAW_WQX: 'Ecotrust (Tribal) || Ecotrust (Tribal)',
  SJBEP:
    'San Juan Bay Estuary Program: a 501c3 nonprofit corporation for the National Estuary Program.',
  SJICD_WA:
    'Resource data to provide landowners and residents with technical and financial assistance to meet regional natural resource conservation goals',
  SJLWT: '',
  SKAGITCOUNTY_WQX: 'Surface Water Quality Monitoring Program',
  SKAGITWG_WQX: 'Upper Skagit Indian Tribe of Washington',
  SKAGWAYTRADITIONALCOUNCIL_WQX: '',
  SKOKDATA_WQX: '',
  SKYHORSETECH:
    'Surface vehicle collecting water sampling data on the Raritan River in NJ. Partnering with the Lower Raritan Watershed.',
  SLCOWS: 'Salt Lake County Watershed',
  SLPWA: 'Water quality monitoring for Seneca Lake, New York',
  SLU_WQX: 'EPA Urban Waters Grant - St. Louis University',
  SMAST: 'https://www.umassd.edu/smast/',
  SMENVIRONMENTAL_WQX:
    'San Manuel Band of Mission Indians, California (Tribal) || San Manuel Band of Mission Indians, California (Tribal)',
  SMIE: 'Water Quality Monitoring Data',
  SMSCGOV_WQX: 'Shakopee Mdewakanton (MN)',
  SMWC: 'The San Miguel Watershed Coalition is a 501(c)(3) non-profit organization, governed by a 10 person board. The San Miguel Watershed Coalition was formed around 1998, to enable a collaborative forum for all residents, businesses, landowners, land managers and non-profit organizations to discuss and influence the future of the watershed.',
  SNEPO_WQX:
    'The Seminole Nation of Oklahoma (Tribal) || The Seminole Nation of Oklahoma (Tribal)',
  SNOCODCNR_SWM: '',
  SNOQUALM_WQX: 'Snoqualmie Tribe || Snoqualmie Indian Tribe (Tribal)',
  SNSA_WQX: 'Water Quality Monitoring Data',
  SOBOBA_WQX: 'Soboba Band of Luiseno Indians, California (Tribal)',
  SOKAOGON_WQX: '',
  SONOMAWATER_WQX: '',
  SOUTHSANTIAM_WC: 'Eric Anderson, Current VolMon group',
  SOUTHUTE: '',
  SOU_WQX: 'Southern Oregon University',
  SPC: 'Volunteer Monitoring Group',
  SPIRITLK: '',
  SQUAXIN: '',
  SRA: 'staging',
  SRBCI:
    'Santa Rosa Band of Cahuilla Indians (Tribal) || Santa Rosa Band of Cahuilla Indians (Tribal)',
  SRCD: 'Biomonitoring Program that monitors chemical, physical and biological aspects of local creeks',
  SRCENV_WQX: '',
  SRMTAKNY_WQX:
    'Saint Regis Mohawk Tribe (Tribal) || Saint Regis Mohawk Tribe (Tribal)',
  SRMTWRP_WQX:
    'Saint Regis Mohawk Tribe (Tribal) || Saint Regis Mohawk Tribe (Tribal)',
  SRPMIC: '',
  SRPMIC_WQX:
    'Salt River Pima-Maricopa Indian Community of the Salt River Reservation, Arizona (Tribal) || Salt River Pima-Maricopa Indian Community of the Salt River Reservation, Arizona (Tribal)',
  SRRTFF: 'Reporting of toxic compounds in the Spokane River',
  SRR_WQX:
    'Tolowa Dee-ni Nation (Smith River Rancheria), California (Tribal) || Tolowa Dee-ni Nation (Smith River Rancheria), California (Tribal)',
  SRSTEPA: '',
  SSCW: 'Salem Sound Coastwatch',
  SSD: 'Colorado',
  SSWCD: 'Seth Mead, Current VolMon group',
  STANDARD_WQX: 'Water Quality Data',
  STANDLEY:
    'Water Quality Data for Upper Clear Creek Watershed from Georgetown to South Platte River',
  STCROIX_WQX: '',
  STF: 'Water Quality Data collected for a voluntary group of private, local, regional, state, and federal interests committed to reducing selenium in locally affected water ways while maintaining the economic viability and agricultural heritage of our areas.',
  STF_WQX:
    'Seminole Tribe of Florida (Tribal) || Seminole Tribe of Florida (Tribal)',
  STJOHNSRIVERKPR_WQX: '',
  STOCKBRIDGE_MUNSEE: '',
  STOI: 'Spokane Tribe of the Spokane Reservation (Tribal) || Spokane Tribe of the Spokane Reservation (Tribal)',
  STORLVD_WQX: 'Water Quality Monitoring Data',
  STROUD_WQX: 'Water Quality Monitoring Data',
  STS: 'NGO',
  ST_CROIX_WQX:
    'St. Croix Chippewa Indians of Wisconsin (Tribal) || St. Croix Chippewa Indians of Wisconsin (Tribal)',
  SUMFS: 'Stockton University Marine Field Station',
  SUMMITLAKETRIBE: 'summitlaketribe.org',
  SUNENCO: 'Suncor Energy (USA) Inc. (Colorado)',
  SUQUAMISH:
    'Suquamish Tribe (Tribal) || Suquamish Indian Tribe of the Port Madison Reservation (Tribal)',
  SVR: '',
  SWFMDDEP_WQX: 'Water Quality Monitoring Data',
  SWINOMISH:
    'Swinomish Indian Tribal Community (Tribal) || Swinomish Indian Tribal Community (Tribal)',
  SWO_OEP: '',
  SWQC: "The Summit Water Quality Committee (SWQC) is a watershed organization formalized by intergovernmental agreement.  Members include the Towns, County and major municipal dischargers (permits # CO-0021598, CO-0020451, CO-0020826, CO-0029955, CO-0021539) in Summit County Colorado. SWQC's focus is on providing definitive environmental assessments of the Blue River Watershed, including Dillon and Green Mountain Reservoirs and promoting pollution control.",
  SWRCB: '',
  SYCEO_WQX: '',
  TABLEMOUNTAINRANCHERIA_WQX:
    'Table Mountain Rancheria of California (Tribal) || Table Mountain Rancheria of California (Tribal)',
  TAKSHANUK: 'Takshanuk Watershed Council Water Quality Monitoring',
  TAMUCC: 'Texas A&M University-Corpus Christi',
  TAOSPBLO_WQX: 'Pueblo of Taos',
  TAOS_FISHERIES_BLM: '',
  TCEQMAIN:
    'The Texas Commission on Environmental Quality (TCEQ) is the environmental agency for the state',
  TDECDOE_WQX: 'DOE Oversight Office',
  TDECWPC_WQX: 'WPC Division',
  TDECWR_WQX: '',
  TECK_AMERICAN: '',
  TEPA29: '',
  TESTGCSWQX: '',
  TESTORG_2999: 'TESTORG_2999; ',
  TEST_SD: '',
  TETRATECH: '',
  TGENVIRO: '',
  THD_LAB: 'Tennessee Department of Health Division of Laboratory Services',
  THORNTON_WQX: 'Water Quality Monitoring Data',
  THURSTONCOUNTY: 'Thurston County PHSS',
  TILLAMOOK_EP: 'York Johnson, Current VolMon group',
  TIMBISHA:
    'Death Valley Timbi-sha Shoshone Tribe (Tribal) || Death Valley Timbi-sha Shoshone Tribe (Tribal)',
  TIMSSD: 'Timpanogos Special Service District',
  TJRI: 'Town of Jamestown Rhode Island',
  TLBP_WQX: 'Tenmile Lakes Basin Partnership',
  TLGVWQMPROGRAM: '',
  'TLINGIT-HAIDA':
    'Central Council of the Tlingit & Haida Indian Tribes of Alaska (Tribal) || Central Council of the Tlingit & Haida Indian Tribes of Alaska (Tribal)',
  TMBLM_WQX: 'Bureau of Land Management, Tillamook Field Office (OR/WA)',
  TMDCI: '',
  TMTC_WQX:
    'Tuolumne Band of Me-Wuk Indians of the Tuolumne Rancheria of California (Tribal) || Tuolumne Band of Me-Wuk Indians of the Tuolumne Rancheria of California (Tribal)',
  TNCAZ_WQX: 'The Nature Conservancy water quality monitoring',
  TNCNJ_WQX: 'The Nature Conservancy',
  "TOHONOO'ODHAMNATION":
    "Tohono O'odham Nation of Arizona (Tribal) || Tohono O'odham Nation of Arizona (Tribal)",
  TOMWC: '',
  TONKAWA1:
    'Tonkawa Tribe of Indians of Oklahoma (Tribal) || Tonkawa Tribe of Indians of Oklahoma (Tribal)',
  TONKAWA_WQX:
    'Tonkawa Tribe of Indians of Oklahoma (Tribal) || Tonkawa Tribe of Indians of Oklahoma (Tribal)',
  TPCHD_WQX: '',
  TPEO_WQX:
    'Pueblo of Taos, New Mexico (Tribal) || Pueblo of Taos, New Mexico (Tribal)',
  TREX: 'Tribal Environmental Exchange Network (Tribal) || Tribal Environmental Exchange Network (Tribal)',
  TRILWWTF: 'Colorado',
  TRINIDADRANCHERIAEPA:
    'Cher-Ae Heights Indian Community of the Trinidad Rancheria, California (Tribal) || Cher-Ae Heights Indian Community of the Trinidad Rancheria, California (Tribal)',
  TRTUL_WQX: '',
  TRUEELEMENTS_QI_WQX: '',
  TSWQC_WQX:
    'The TSWQC_WQX organization is for data collected under the direction of the Tri-State Water Quality Council.',
  TTFFX: '',
  TU: 'Conservation of freshwater streams, rivers, and associated upland habitats for trout, salmon, other aquatic species, and people',
  TUMWATER: 'City of Tumwater - Public Works',
  TURTLEMT: 'Archie Gronvold 106 Coordinator',
  TWI: 'Stony Brook-Millstone and the Central Delaware River Watersheds',
  TWWWTF: 'Colorado',
  TXSTRMTM_WQX: '',
  TYSON: '',
  UAEFMD_WQX: 'Edge-of Field monitoring data',
  'UB-SIAT-PE_WQX': 'University of Baltimore',
  UC_REGION_USBOR_WQX: '',
  UDAF: 'Utah Department of Agriculture and Food',
  UDWC_WQX: '',
  UFMILTON_WQX: 'University of Florida Watershed Management Lab',
  UH_CLEARLAKE: '',
  UMC: '',
  UMCRWWTF: 'Colorado',
  UMIT: '',
  UMMP: 'THE UMMP IS A VOLUNTEER RIVER QUALITY MONITORING PROGRAM MANAGED BY THE UPPER MERRIMACK RIVER LOCAL ADVISORY COMMITTEE.  ESTABLISHED IN 1995, THE UMMP MONITORS RIVER QUALITY AT 11 SITES FROM FRANKLIN TO BOW ON THE PEMI, WINNI, CONTOOCOOK AND MERRI RIVERS',
  UMR: '',
  UMRBA_WQX: '',
  UMRR_LTRM: '',
  UMT_FLATHEADBIOSTATION: '',
  UNI: '',
  UPPERSKAGIT:
    'Upper Skagit Indian Tribe (Tribal) || Upper Skagit Indian Tribe (Tribal)',
  URIWW:
    'Current (and historical) information on the water quality of surface water resources throughout Rhode Island, including lakes, ponds, reservoirs, rivers, streams and the marine environment.',
  URS: '',
  URWA: 'Upper Raritan Watershed Association',
  'USACE-STL-EC-E': '',
  USACENWP_WQX: '',
  USACENWS_WQX:
    'U.S. Army Corps of Engineers, Seattle District Water Management Section',
  USACESPK: '',
  USACE_WQX: 'Erich Emery - Great Lakes and Ohio River Division',
  USACOEND: 'US Army Corps of Engineers Nashville District',
  USACOERID: '',
  USBR: 'Utah Branch of United States Beau of Reclamation',
  'USBR-WCAO': 'Bureau of Reclamation Western Colorado Area Office',
  USCOEKY: 'US Army Corps of Engineers District',
  USDACA: '',
  USDAFORESTSVCREGION9: '',
  USEPAREGION9: 'USEPA Region 9',
  USEPA_CORALREEFS_WQX: '',
  USEPA_REGION8: '',
  USET_WQX:
    'United South and Eastern Tribes, Inc. (Tennessee) (Tribal) || United South and Eastern Tribes, Inc. (Tennessee) (Tribal)',
  USFS0614_WQX: 'Water Quality Data',
  USFSEASTERN: '',
  USFSPRESCOTT: '',
  USFSWHITEMT: '',
  USFWS_ALASKA: 'US Fish and Wildlife Service - Alaska Region',
  USFWS_NM_WQX: 'Water Quality Monitoring Data',
  USGS: 'Missouri Department of Natural Resources',
  'USGS-AK': 'USGS Alaska Water Science Center',
  'USGS-AR': '',
  'USGS-MN': 'USGS Minnesota Water Science Center',
  USGSNC: '',
  USIOUX_WQX: '',
  USVI: 'Water Quality Monitoring Data BEACHES',
  USVIST_WQX: 'Water Quality Monitoring Data for all the Waters in the state',
  UT0024384_WQX:
    'At South Valley Water Reclamation Facility, our goal is to treat the wastewater that comes to our facility adequately to ensure the water discharged from our facility has no negative affects on the environment or to the Jordan River.',
  UTAHDWQ_WQX: 'Ambient Water Quality Monitoring Data',
  UTAHGS: 'Utah Geological Survey',
  UTDWR: 'Utah Division of Wildlife Resources',
  UTEMTN: '',
  UTOGM_WQX: 'Utah Division of Oil, Gas, and Mining',
  UTRRVA05: '',
  UTTCHD: 'Utah - TriCounty Health Department',
  'UU-SWQ': '',
  UVAVTSSS_WQX:
    'University of Virginia: Shenandoah Watershed Study and Virginia Trout Stream Sensitivity Study',
  UWFCEDB_WQX:
    'Center for Environmental Diagnostics and Bioremediation, University of West Florida',
  UWP: '',
  UWT_CUW: 'University of Washington Tacoma at Center for Urban Waters',
  U_NH01:
    "THE UNIVERSITY OF NEW HAMPSHIRE'S JACKSON ESTUARINE LABORATORY (JEL) IS LOCATED FIVE MILES FROM THE DURHAM CAMPUS ON THE SHORES OF GREAT BAY ESTUARY AT ADAMS POINT (SEE DIRECTIONS, FACILITIES). RESIDENT FACULTY MEMBERS CONDUCT RESEARCH THAT COVERS A WIDE RANGE OF FIELDS AND IS SUPPORTED BY A VARIETY OF PRIVATE, STATE AND FEDERAL AGENCIES. STUDENTS, POST-DOCTORAL FELLOWS AND VISITING SCIENTISTS ARE ALSO ACTIVE IN JEL RESEARCH -CONTACT IS ADMIN/PROGRAM SUPPORT ASSISTANT",
  VADEP319: 'VA Department of Environmental Quality 319 Grants Monitoring',
  VALENCIA_WQX: 'Water Quality Monitoring Data',
  VBKI_WQX:
    'Viejas (Baron Long) Group of Capitan Grande Band of Mission Indians of the Viejas Reservation, California (Tribal) || Viejas (Baron Long) Group of Capitan Grande Band of Mission Indians of the Viejas Reservation, California (Tribal)',
  VERMONTANR: '',
  VERSAR: '',
  VM_SDCWC_AW: 'Paul Robertson, Current VolMon group',
  VM_SWC: 'Kyle Terry, Current VolMon group',
  VOS1_WQX: 'Village of Solomon (Tribal) || Village of Solomon (Tribal)',
  'VT2009,': '',
  VWIN: 'Water Quality Monitoring Data',
  W3STON2024WQX: '',
  WALKER_PAIUTE:
    'Walker River Paiute Tribe of the Walker River Reservation, Nevada (Tribal) || Walker River Paiute Tribe of the Walker River Reservation, Nevada (Tribal)',
  WALLAWALLA_WC: 'Current VolMon group',
  WARMSPRINGS09:
    'Confederated Tribes of the Warm Springs Reservation of Oregon (Tribal) || Confederated Tribes of the Warm Springs Reservation of Oregon (Tribal)',
  WASDNR_WQX: '',
  WASHNVCA_WQX: '',
  WASIT:
    'STILLAGUAMISH TRIBE OF INDIANS (Tribal) || Stillaguamish Tribe of Indians of Washington (Tribal)',
  WATERANDAIR: 'www.waterandair.com',
  WATERKEEPER:
    'Waterkeeper Alliance is a worldwide network of environmental organizations founded in 1999, in response to a growing movement of organizations with such names as Riverkeeper, Baykeeper and Soundkeeper.',
  WATERLDF_WQX:
    'Lac du Flambeau Band of Lake Superior Chippewa Indians of the Lac du Flambeau Reservation of Wisconsin (Tribal) || Lac du Flambeau Band of Lake Superior Chippewa Indians of the Lac du Flambeau Reservation of Wisconsin (Tribal)',
  WATERQUALITYPORTAL: 'www.waterqualitydata.us',
  WAYNE_STATE_UNIVERSITY: '',
  WA_ECOLOGY: 'Washington State Government',
  WBNERR:
    'https://waquoitbayreserve.org/research-monitoring/waquoit-baywatchers/',
  WCD: 'A local unit of government in Washington County, Minnesota dedicated to soil and water conservation',
  WC_WQX: '',
  WDEP_WQX:
    'Wichita Department of Environmental Programs (Tribal) || Wichita Department of Environmental Programs (Tribal)',
  WDFW: 'Washington Department of Fish and Wildlife;',
  WEARTH_WQX:
    'Minnesota Chippewa Tribe, Minnesota (White Earth Band) (Tribal) || Minnesota Chippewa Tribe, Minnesota (White Earth Band) (Tribal)',
  WENATCHEEPCBINV_WQX: '',
  WETLAB:
    'Western Environmental Testing Laboratory (Tribal) || Western Environmental Testing Laboratory (Tribal)',
  WFWQC_UT: 'Wasatch Front Water Quality Council Utah',
  WHATCOMCD: '',
  WHATCOM_WQX: 'Whatcom County Public Works',
  WHITEMOUNTAIN_WQX:
    'White Mountain Apache Tribe of the Fort Apache Reservation, Arizona (Tribal) || White Mountain Apache Tribe of the Fort Apache Reservation, Arizona (Tribal)',
  WICHITAEPA_WQX:
    'Wichita and Affiliated Tribes (Wichita, Keechi, Waco & Tawakonie), Oklahoma (Tribal) || Wichita and Affiliated Tribes (Wichita, Keechi, Waco & Tawakonie), Oklahoma (Tribal)',
  WIDATCP_WQX:
    'Wisconsin Department of Agriculture, Trade and Consumer Protection',
  WIDNR_WQX: 'Wisconsin Department of Natural Resources.',
  WILDFISHCONSERVANCY_WA: '',
  WILLOWCREEK: 'CDSN - Willow Creek Reclamation Committee',
  WINDWARDENV_WQX: 'WindwardEnvironmental',
  WINNEBAGO07:
    'Winnebago Tribe of Nebraska (Tribal) || Winnebago Tribe of Nebraska (Tribal)',
  WINNEBAGO07_WQX:
    'Winnebago Tribe of Nebraska (Tribal) || Winnebago Tribe of Nebraska (Tribal)',
  WIYOT_WQX:
    'Wiyot Tribe, California (Tribal) || Wiyot Tribe, California (Tribal)',
  WI_MMSD: '',
  WLA: '',
  WMHMD: 'Colorado',
  WNENVDPT_WQX: '',
  WOOD: 'Energy services company submitting sediment data for a dredging project.',
  WQXPQRC: '',
  WQXTEST: 'Tribal',
  WQXWEBTRAINING:
    'Will be used to store the historical GLENDA data that will be added to the WQX in the future.',
  WQXWEBTRAINING1: 'Volunteer',
  WQXWEBTRAINING10: 'Volunteer',
  WQXWEBTRAINING11: 'Volunteer',
  WQXWEBTRAINING12: '',
  WQXWEBTRAINING13: '',
  WQXWEBTRAINING14: '',
  WQXWEBTRAINING15: '',
  WQXWEBTRAINING16: '',
  WQXWEBTRAINING17: '',
  WQXWEBTRAINING18: '',
  WQXWEBTRAINING19: '',
  WQXWEBTRAINING2: 'Poarch Band of Creek Indians;',
  WQXWEBTRAINING21: '',
  WQXWEBTRAINING22: 'Northern Basin WVDEP NPS program',
  WQXWEBTRAINING23: '',
  WQXWEBTRAINING24:
    'Community based non profit organization dedicated to restoring wild salmon runs in Whatcom County',
  WQXWEBTRAINING25: '',
  WQXWEBTRAINING26: '',
  WQXWEBTRAINING27: '',
  WQXWEBTRAINING28: '',
  WQXWEBTRAINING29: '',
  WQXWEBTRAINING3: 'Volunteer',
  WQXWEBTRAINING30: '',
  WQXWEBTRAINING4:
    'Will be used to store the historical GLENDA data that will be added to the WQX in the future.',
  WQXWEBTRAINING5: 'Volunteer',
  WQXWEBTRAINING6: 'Volunteer',
  WQXWEBTRAINING7: 'Volunteer',
  WQXWEBTRAINING8: 'Volunteer',
  WQXWEBTRAINING9: 'Volunteer',
  WRDM18: 'Chesapeake Commons',
  WREQC_WQX: '',
  WRFOBLM: '',
  WRWMG: '',
  WRWQMP: '',
  WSDANRAS: 'Washington State Department of Agriculture',
  WSDA_WQX:
    'Washington State Department of Agriculture, Dairy Nutrient Management Program',
  WSG: 'The WSG mission is to help people and marine life thrive by supplying research, technical expertise and educational activities that support the responsible use and conservation of ocean and coastal ecosystems.',
  WSSC_WQX: 'Water Quality Monitoring',
  WTGHA: 'Tribal',
  WU: '',
  WVDEPNPS: '',
  WVDEP_WIB_WQX:
    'West Virginia Department of Environmental Protection Watershed Improvement Branch',
  WVDEP_WQX: 'State of WV Ambient Surface Water Quality Programs',
  WVSU_AERS:
    'High frequency data in three locations along the Kanawha River, WV measuring temperature, pH, DO, NO3, Cl, ORP, specific conductance, turbidity',
  WVSU_WQX: 'West Virginia State University',
  WVU_WQX: 'West Virginia University',
  WWMD_VA: 'Tribal',
  WWMD_VA_WQX: 'Water Quality Monitoring Data',
  WWP: '',
  WWSD: 'Colorado',
  WWXINCOG: '',
  WYDEQ_WATERSHED: '',
  WYDEQ_WQX: 'Water Quality Monitoring Data for all the Waters in the state',
  WYOMING_EXTERNAL: '',
  YAKAMA_WQX:
    'Confederated Tribes and Bands of the Yakama Nation (Tribal) || Confederated Tribes and Bands of the Yakama Nation (Tribal)',
  YAKIMAVLYDAIRIES_WQX: 'c/o  Inland Earth Sciences Corp.',
  YAN_WQX:
    'Yavapai-Apache Nation of the Camp Verde Indian Reservation, Arizona (Tribal) || Yavapai-Apache Nation of the Camp Verde Indian Reservation, Arizona (Tribal)',
  YERINGTON_WQX:
    'Yerington Paiute Tribe of the Yerington Colony & Campbell Ranch, Nevada (Tribal) || Yerington Paiute Tribe of the Yerington Colony & Campbell Ranch, Nevada (Tribal)',
  YOMBA:
    'Yomba Shoshone Tribe of the Yomba Reservation, Nevada (Tribal) || Yomba Shoshone Tribe of the Yomba Reservation, Nevada (Tribal)',
  YPIT_WQX:
    'Yavapai Prescott Indian Tribe, Arizona (Tribal) || Yavapai Prescott Indian Tribe, Arizona (Tribal)',
  YRITWC:
    'Yukon River Inter-Tribal Watershed Council (Tribal) || Yukon River Inter-Tribal Watershed Council (Tribal)',
  YUROKTEP_WQX:
    'Yurok Tribe of the Yurok Reservation, California (Tribal) || Yurok Tribe of the Yurok Reservation, California (Tribal)',
  ZENDERGROUP_WQX: '',
  ZIAPUEBLO_WQX: ''
}
