export default {
  "Air Sampler": "",
  "Benthic Corer": "Sediment Corers are used to sample the organisms that live on or just below the surface of the ocean floor (the benthos), while displaying the structure of the sediment. With benthic corers, scientists obtain samples containing organisms (including the very small ones, microbes) found in the benthos. Corers work by boring a large tube into the benthos and then bringing up a column, or core, of sediment intact within the tube.",
  "Benthic Dredge": "The marine biology dredge is used to sample organisms living on a rocky bottom or burrowing within the smooth muddy floor of the ocean (benthic) species).The dredge is pulled by a boat and operates at any depth on a cable or line, generally with a hydraulic winch. The dredge digs into the ocean floor and bring the animals to the surface where they are caught in a net that either follows behind or is a part of the digging apparatus.",
  "Benthic Grab": "An instrument to sample sediment in water environments. Usually it is a clamshell bucket made of stainless steel. The Hamon grab is the recommended tool for sampling the benthic macro-infauna from coarse substrata. This grab consists of a rectangular frame forming a stable support for a sampling bucket attached to a pivoted arm. This type of grab is not recommended for use on coarser substrata.",
  "Diatometer": "A dilatometer is a scientific instrument that measures volume changes caused by a physical or chemical process. A familiar application of a dilatometer is the mercury-in-glass thermometer,",
  "Electroshock": "As the name implies, electrofishing uses electricity to catch fish. Electrofishing uses direct current electricity flowing between a submerged cathode and anode. This affects the movement of the fish so that they swim toward the anode, where they can be caught. If the fish happen to be surfacing, some electricity does penetrate the water, right at the strike point. Electrofishing is a common technique used by fisheries biologists to sample fish populations in bodies of freshwater.",
  "Miscellaneous/Other": "Other",
  "Net/Horizontal Tow": "nets are a modification on the standard trawl used to collect planktonic organisms, of nearly any size, intact. Towed by a research vessel, plankton nets have a long funnel shape that allows them to catch differently sized plankton simply by changing the mesh size of the net. At the end of the funnel is a collection cylinder called a cod-end.",
  "Net/Non-Tow": "",
  "Net/Vertical Tow": "The ring net consists of a fine-meshed bag attached at its mouth, or opening, to a metallic ring. The net itself is terminated in a bottle or jar where the unfiltered plankton and other particulate matter are collected. The net is usually deployed vertically for non-quantitative purposes from a platform, such as a vessel or pier. It may also be towed, although lacking in devices for controlling its passage through the water column. Towing applications are mainly non-quantitative.",
  "Soil Sampler": "",
  "Suspended Sediment Sampler": "The purpose of a suspended sediment sampler is to collect a representative sample of the water-sediment mixture moving in the stream near the sampler intake.",
  "Trap/Substrate": "",
  "Water Sampler": "The water sampler collects 1 or more actual samples of water for analysis in the lab after recovery of the package."
}