export default {
  "Bedrock, Carbonate": "A class of sedimentary rocks composed primarily of carbonate minerals.",
  "Bedrock, Fractured": "",
  "Bedrock, Interbedded sandstone/carbonate": "",
  "Bedrock, Interbedded sandstone/shale": "",
  "Bedrock, Interbedded sandstone/shale/carbonate": "",
  "Bedrock, Interbedded sediments": "",
  "Bedrock, Interbedded siltstone/carbonate/gypsum": "",
  "Bedrock, Massive sandstone": "",
  "Bedrock, Soluble Carbonate - Karst": "",
  "Bedrock, Soluble gypsum/dolomite with shale interb": "",
  "Geologic": "A formation is a body of strata of predominantly one type. The concept of formally defined layers or strata is central to the geologic discipline of stratigraphy",
  "Hydrogeologic": "Is the area of geology that deals with the distribution and movement of groundwater in the soil and rocks of the Earth's crust (commonly in aquifers).",
  "Mixed": "a eformulate coalition formation in a mixed-motive situation as a process in which two group members join their resources",
  "Sediment, Alluvium/Terrace": "",
  "Sediment, Isolated Terrace": "",
  "Sediment, Terrace": "",
  "Sediment, Unconsolidated": "a well report/boring was sufficient to describe the surficial materials (soil) or to describe  unconsolidated rock, sediments in an undefined area. most commonly reported on monitoring well construction reports.",
  "Soil Horizon": "A layer parallel to the soil surface, whose physical, chemical and biological characteristics differ from the layers above and beneath."
}