export default {
  if: {
    properties: {
      CharacteristicName: {
        enum: [
          '(+)-cis-Permethrin',
          '(-)-cis-Permethrin',
          '(RS)-AMPA (Aminomethyl phosphonic acid)',
          '.alpha.-Endosulfan',
          '.alpha.-Hexachlorocyclohexane',
          '.beta.-Endosulfan',
          '.beta.-Hexachlorocyclohexane',
          '.beta.-Sitosterol',
          '.delta.-Hexachlorocyclohexane',
          '1,1,1,2-Tetrachloroethane',
          '1,1,1,3,3,3-Hexafluoro-2-propanol',
          '1,1,1-Trichloro-2-propanone',
          '1,1,1-Trichloroethane',
          '1,1,1-Trichloropropane',
          '1,1,2,2-Tetrachloroethane',
          '1,1,2-Trichloroethane',
          '1,1-Dichloroethane',
          '1,1-Dichloroethene',
          '1,1-Dichloropropene',
          '1,2,3,4,6,7,8,9-Octachlorodibenzo-p-dioxin',
          '1,2,3,4,6,7,8,9-Octachlorodibenzofuran',
          '1,2,3,4,6,7,8-Heptachlorodibenzo-p-dioxin',
          '1,2,3,4,6,7,8-Heptachlorodibenzofuran',
          '1,2,3,4,7,8,9-Heptachlorodibenzofuran',
          '1,2,3,4,7,8-Hexachlorodibenzo-p-dioxin',
          '1,2,3,4,7,8-Hexachlorodibenzofuran',
          '1,2,3,6,7,8-Hexachlorodibenzo-p-dioxin',
          '1,2,3,6,7,8-Hexachlorodibenzofuran',
          '1,2,3,7,8,9-Hexachlorodibenzo-p-dioxin',
          '1,2,3,7,8,9-Hexachlorodibenzofuran',
          '1,2,3,7,8-Pentachlorodibenzo-p-dioxin',
          '1,2,3,7,8-Pentachlorodibenzofuran',
          '1,2,3-Trichloro-4-nitrobenzene',
          '1,2,3-Trichlorobenzene',
          '1,2,3-Trichloropropane',
          '1,2,4,5-Tetrachlorobenzene',
          '1,2,4-Trichlorobenzene',
          '1,2,4-Triethylbenzene',
          '1,2,4-Trimethylbenzene',
          '1,2-Dibromo-3-chloropropane',
          '1,2-Dichloroethane',
          '1,2-Dichloropropane',
          '1,2-Dimethylnaphthalene',
          '1,2-Diphenylhydrazine',
          '1,2-Naphthoquinone',
          '1,3,4,6,7,8-Hexahydro-4,6,6,7,8,8-hexamethylcyclopenta[g]-2-benzopyran',
          '1,3,5-Trimethylbenzene',
          '1,3,5-Trinitrobenzene',
          '1,3,5-Trithiane',
          '1,3-Butadiene',
          '1,3-Diamino-5,6-dihydrobenzo[f]quinazoline',
          '1,3-Dichlorobenzene',
          '1,3-Dichloropropane',
          '1,4-Dichloro-cis-2-butene',
          '1,4-Dioxane',
          '1,5-Naphthalenediamine',
          '1,6-Dimethylnaphthalene',
          '1,7-Dimethylxanthine',
          '1-Acetyl-2-thiourea',
          '1-Chloro-2-methyl-3-nitrobenzene',
          '1-Chloro-3,4-dintrobenzene',
          '1-Chlorobutane',
          '1-Chloronaphthalene',
          '1-Heptadecene',
          '1-Methylfluorene',
          '1-Methylnaphthalene',
          '1-Methylphenanthrene',
          '1-Methylpyrene',
          '1-Naphthalenamine',
          '11-DECYL TETRACOSANE',
          '13C1-D2-Hydrochlorothiazide',
          '13C1-D3-Erythromycin-H2O',
          '13C3-Flumequine',
          '13C3-PFBA',
          '13C3-PFPeA',
          '13C4-Cloxacillin',
          '13C6-Ibuprofen',
          '13C6-Sulfachloropyridazine',
          '13C6-Triclosan',
          '17.alpha.-Estradiol',
          '17alpha-Dihydroequilin',
          "2',3,4,5,6'-Pentachlorobiphenyl",
          "2',3,4-Trichlorobiphenyl",
          "2,2',3',4,5-Pentachlorobiphenyl",
          "2,2',3',4,6-Pentachlorobiphenyl",
          "2,2',3,3',4',5,6-Heptachlorobiphenyl",
          "2,2',3,3',4,4',5,5',6-Nonachlorobiphenyl",
          "2,2',3,3',4,4',5,5'-Octachlorobiphenyl",
          "2,2',3,3',4,4',5,6'-Octachlorobiphenyl",
          "2,2',3,3',4,4',5,6,6'-Nonachlorobiphenyl",
          "2,2',3,3',4,4',5,6-Octachorobiphenyl",
          "2,2',3,3',4,4',5-Heptachlorobiphenyl",
          "2,2',3,3',4,4',6,6'-Octachlorobiphenyl",
          "2,2',3,3',4,4',6-Heptachlorobiphenyl",
          "2,2',3,3',4,4'-Hexachlorobiphenyl",
          "2,2',3,3',4,5',6,6'-Octachlorobiphenyl",
          "2,2',3,3',4,5',6-Heptachlorobiphenyl",
          "2,2',3,3',4,5'-Hexachlorobiphenyl",
          "2,2',3,3',4,5,5',6,6'-Nonachlorobiphenyl",
          "2,2',3,3',4,5,5',6-Octachlorobiphenyl",
          "2,2',3,3',4,5,5'-Heptachlorobiphenyl",
          "2,2',3,3',4,5,6'-Heptachlorobiphenyl",
          "2,2',3,3',4,5-Hexachlorobiphenyl",
          "2,2',3,3',4,6'-Hexachlorobiphenyl",
          "2,2',3,3',4,6,6'-Heptachlorobiphenyl",
          "2,2',3,3',4,6-Hexachlorobiphenyl",
          "2,2',3,3',4-Pentachlorobiphenyl",
          "2,2',3,3',5,5',6,6'-Octachlorobiphenyl",
          "2,2',3,3',5,5',6-Heptachlorobiphenyl",
          "2,2',3,3',5,5'-Hexachlorobiphenyl",
          "2,2',3,3',5,6'-Hexachlorobiphenyl",
          "2,2',3,3',5,6,6'-Heptachlorobiphenyl",
          "2,2',3,3',5,6-Hexachlorobiphenyl",
          "2,2',3,3',5-Pentachlorobiphenyl",
          "2,2',3,3',6,6'-Hexachlorobiphenyl",
          "2,2',3,3',6-Pentachlorobiphenyl",
          "2,2',3,3'-Tetrachlorobiphenyl",
          "2,2',3,4',5,5',6-Heptachlorobiphenyl",
          "2,2',3,4',5,5'-Hexachlorobiphenyl",
          "2,2',3,4',5,6'-Hexachlorobiphenyl",
          "2,2',3,4',5,6,6'-Heptachlorobiphenyl",
          "2,2',3,4',5,6-Hexachlorobiphenyl",
          "2,2',3,4',5-Pentachlorobiphenyl",
          "2,2',3,4',6,6'-Hexachlorobiphenyl",
          "2,2',3,4'-Tetrachlorobiphenyl",
          "2,2',3,4,4',5',6-Heptabromodiphenyl ether",
          "2,2',3,4,4',5',6-Heptachlorobiphenyl",
          "2,2',3,4,4',5,5',6-Octachlorobiphenyl",
          "2,2',3,4,4',5,5'-Heptachlorobiphenyl",
          "2,2',3,4,4',5,6'-Heptachlorobiphenyl",
          "2,2',3,4,4',5,6,6'-Octachlorobiphenyl",
          "2,2',3,4,4',5,6-Heptachlorobiphenyl",
          "2,2',3,4,4',5-Hexachlorobiphenyl",
          "2,2',3,4,4',6,6'-Heptachlorobiphenyl",
          "2,2',3,4,4',6-Hexachlorobiphenyl",
          "2,2',3,4,4'-Pentachlorobiphenyl",
          "2,2',3,4,5',6-Hexachlorobiphenyl",
          "2,2',3,4,5,5'-Hexachlorobiphenyl",
          "2,2',3,4,5,6,6'-Heptachlorobiphenyl",
          "2,2',3,4,5,6-Hexachlorobiphenyl",
          "2,2',3,4,5-Pentachlorobiphenyl",
          "2,2',3,4,6'-Pentachlorobiphenyl",
          "2,2',3,4,6,6'-Hexachlorobiphenyl",
          "2,2',3,4,6-Pentachlorobiphenyl",
          "2,2',3,5'-Tetrachlorobiphenyl",
          "2,2',3,5,5'-Pentachlorobiphenyl",
          "2,2',3,5,6'-Pentachlorobiphenyl",
          "2,2',3,5,6,6'-Hexachlorobiphenyl",
          "2,2',3,5,6-Pentachlorobiphenyl",
          "2,2',3,5-Tetrachlorobiphenyl",
          "2,2',3,6'-Tetrachlorobiphenyl",
          "2,2',3,6,6'-Pentachlorobiphenyl",
          "2,2',3,6-Tetrachlorobiphenyl",
          "2,2',3-Trichlorobiphenyl",
          "2,2',4,4',5',6-Hexachlorobiphenyl",
          "2,2',4,4',5,5'-Hexachlorobiphenyl",
          "2,2',4,4',5-Pentabromodiphenyl ether***retired***use BDE-099",
          "2,2',4,4',6,6'-Hexachlorobiphenyl",
          "2,2',4,4',6-Pentabromodiphenyl ether***retired***use BDE-100",
          "2,2',4,4'-Tetrachlorobiphenyl",
          "2,2',4,5'-Tetrachlorobiphenyl",
          "2,2',4,5-Tetrachlorobiphenyl",
          "2,2',4,6,6'-Pentachlorobiphenyl",
          "2,2',4,6-Tetrachlorobiphenyl",
          "2,2',4-Trichlorobiphenyl",
          "2,2',5,5'-Tetrachlorobiphenyl",
          "2,2',5-Trichlorobiphenyl",
          "2,2',6,6'-Tetrachlorobiphenyl",
          "2,2',6-Trichlorobiphenyl",
          "2,2'-Biquinoline",
          "2,2'-Dichlorobiphenyl",
          "2,3',4,4',5,5'-Hexachlorobiphenyl",
          "2,3',4,4',5-Pentachlorobiphenyl",
          "2,3',4,4'-Tetrachlorobiphenyl",
          "2,3',4,5'-Tetrachlorobiphenyl",
          "2,3',4,5,5'-Pentachlorobiphenyl",
          "2,3',4,5-Tetrachlorobiphenyl",
          "2,3',4-Trichlorobiphenyl",
          "2,3',5',6-Tetrachlorobiphenyl",
          "2,3',5,5'-Tetrachlorobiphenyl",
          "2,3',5-Trichlorobiphenyl",
          "2,3',6-Trichlorobiphenyl",
          "2,3'-Dichlorobiphenyl",
          "2,3,3',4',5',6-Hexachlorobiphenyl",
          "2,3,3',4',5,5'-Hexachlorobiphenyl",
          "2,3,3',4',5-Pentachlorobiphenyl",
          "2,3,3',4',6-Pentachlorobiphenyl",
          "2,3,3',4'-Tetrachlorobiphenyl",
          "2,3,3',4,4',5',6-Heptachlorobiphenyl",
          "2,3,3',4,4',5,5',6-Octachlorobiphenyl",
          "2,3,3',4,4',5,5'-Heptachlorobiphenyl",
          "2,3,3',4,4',5,6-Heptachlorobiphenyl",
          "2,3,3',4,4',5-Hexachlorobiphenyl",
          "2,3,3',4,4',6-Hexachlorobiphenyl",
          "2,3,3',4,4'-Pentachlorobiphenyl",
          "2,3,3',4,5',6-Hexachlorobiphenyl",
          "2,3,3',4,5,5',6-Heptachlorobiphenyl",
          "2,3,3',4,5,5'-Hexachlorobiphenyl",
          "2,3,3',4,5-Pentachlorobiphenyl",
          "2,3,3',4,6-Pentachlorobiphenyl",
          "2,3,3',5'-Tetrachlorobiphenyl",
          "2,3,3',5,5',6-Hexachlorobiphenyl",
          "2,3,3',5,5'-Pentachlorobiphenyl",
          "2,3,3',5,6-Pentachlorobiphenyl",
          "2,3,3',5-Tetrachlorobiphenyl",
          "2,3,3',6-Tetrachlorobiphenyl",
          "2,3,3'-Trichlorobiphenyl",
          "2,3,4',6-Tetrachlorobiphenyl",
          "2,3,4'-Trichlorobiphenyl",
          "2,3,4,4',5-Pentachlorobiphenyl",
          "2,3,4,4'-Tetrachlorobiphenyl",
          '2,3,4,5-Tetrachlorobiphenyl',
          '2,3,4,5-Tetrachloronitrobenzene',
          '2,3,4,6,7,8-Hexachlorodibenzofuran',
          '2,3,4,6-Tetrachlorophenol',
          '2,3,4,7,8-Pentachlorodibenzofuran',
          '2,3,4-Trichlorobiphenyl',
          '2,3,5-Trichlorobiphenyl',
          '2,3,6-Trichlorobiphenyl',
          '2,3,6-Trimethylnaphthalene',
          '2,3,7,8-Tetrachlorodibenzo-p-dioxin',
          '2,3,7,8-Tetrachlorodibenzofuran',
          '2,3-Dichlorobiphenyl',
          '2,3-Dichloronitrobenzene',
          '2,3-Dimethylphenol',
          "2,4',5-Trichlorobiphenyl",
          "2,4',6-Trichlorobiphenyl",
          "2,4'-Dichlorobiphenyl",
          '2,4,5-T',
          '2,4,5-Trichlorobiphenyl',
          '2,4,5-Trichloronitrobenzene',
          '2,4,5-Trichlorophenol',
          '2,4,5-Trichlorophenyl 4-nitrophenyl ether',
          '2,4,6-Trichlorophenol',
          '2,4,6-Trichlorophenyl 4-nitrophenyl ether',
          '2,4-D',
          '2,4-D esters',
          '2,4-DB',
          '2,4-Dibromophenyl 4-nitrophenyl ether',
          '2,4-Dichlorobiphenyl',
          '2,4-Dichlorophenol',
          '2,4-Dichlorophenyl 3-methyl-4-nitrophenyl ether',
          '2,4-Dimethylphenol',
          '2,4-Dinitrochlorobenzene',
          '2,4-Dinitrophenol',
          '2,4-Dinitrotoluene',
          '2,5-Dichlorobiphenyl',
          '2,5-Dichloronitrobenzene',
          '2,5-Dimethylphenol',
          '2,5-Dinitrophenol',
          '2,6-Dichlorobiphenyl',
          '2,6-Dichlorophenol',
          '2,6-Dichlorophenyl 4-nitrophenyl ether',
          '2,6-Dimethylnaphthalene',
          '2,6-Dimethylphenol',
          '2,6-Dinitrotoluene',
          '2,6-Xylidine',
          '2-(Chloromethyl)pyridine hydrochloride',
          '2-(Dimethylamino)-N-hydroxy-2-oxoethanimidothioic acid methyl ester',
          '2-Amino-4,6-dinitrotoluene',
          '2-Butyl-2-methyl-1,3-dioxane',
          '2-Chloroacrylonitrile',
          '2-Chlorobiphenyl',
          '2-Chloroethyl vinyl ether',
          '2-Chloronaphthalene',
          '2-Chlorophenyl 4-nitrophenyl ether',
          '2-Ethylnaphthalene',
          '2-Hexanone',
          '2-Methybenzothiazole',
          '2-Methylanthracene',
          '2-Methylnaphthalene',
          '2-Methylpyridine',
          '2-Naphthalenamine',
          '2-Nitropropane',
          '2-Phenylethyl tert-butyl ether',
          '2-Propanol, 1,1,1,3,3,3-hexafluoro-2-methyl-',
          '2-chlorovinyl arsonous acid',
          '2-methyloctacosane',
          "3,3',4,4',5,5'-Hexachlorobiphenyl",
          "3,3',4,4',5-Pentachlorobiphenyl",
          "3,3',4,4'-Tetrachlorobiphenyl",
          "3,3',4,5'-Tetrachlorobiphenyl",
          "3,3',4,5,5'-Pentachlorobiphenyl",
          "3,3',4,5-Tetrachlorobiphenyl",
          "3,3',4-Trichlorobiphenyl",
          "3,3',5,5'-Tetrachlorobiphenyl",
          "3,3',5-Trichlorobiphenyl",
          "3,3'-Dichlorobenzidine",
          "3,3'-Dichlorobiphenyl",
          "3,3'-Dimethylbenzidine",
          "3,4',5-Trichlorobiphenyl",
          "3,4,4',5-Tetrachlorobiphenyl",
          "3,4,4'-Trichlorobiphenyl",
          '3,4,5-Trichlorobiphenyl',
          '3,4-Dichlorobiphenyl',
          '3,4-Dichloronitrobenzene',
          '3,4-Dinitrochlorobenzene',
          '3,5-Dichlorobenzoic acid',
          '3,5-Dichlorobiphenyl',
          '3,5-Dimethylphenol',
          '3-Amino-9-ethylcarbazole',
          '3-Chlorobiphenyl',
          '3-Chlorophenyl 4-nitrophenyl ether',
          '3-Chloropropionitrile',
          '3-Hydroxycarbofuran',
          '3-Methylcholanthrene',
          '3-Methylindole',
          "4,4'-Methylenebis[N,N-dimethylaniline]",
          '4,6-Dinitro-o-cresol',
          '4-(Hydroxymethyl)pendimethalin',
          '4-Amino-2,6-dinitrotoluene',
          '4-Aminobiphenyl',
          '4-Androstenedione',
          '4-Bromophenyl phenyl ether***retired***use BDE-003',
          '4-Chloro-1,2-phenylenediamine',
          '4-Chloro-2-nitroaniline',
          '4-Chloro-m-phenylenediamine',
          '4-Chlorobiphenyl',
          '4-Dimethylaminoazobenzene',
          '4-Epianhydrochlortetracycline (EACTC)',
          '4-Epianhydrochlortetracycline (EATC)',
          '4-Epichlortetracycline',
          '4-Heptafluorobutyryloxyhexadecane',
          '4-Nitrobiphenyl',
          '4-Nitroquinoline 1-oxide',
          '4-epi-Oxytetracycline',
          '4-epitetracycline (ETC)',
          '4H-Cyclopenta[def]phenanthrene',
          '5-Chloro-o-toluidine',
          '5-Nitro-o-toluidine',
          '5-Nitroacenaphthene',
          '5-Tolyltriazole',
          '7,12-Dimethylbenz[a]anthracene',
          'AHTN',
          'Acenaphthene',
          'Acenaphthylene',
          'Acetamidofluorene',
          'Acetaminophen',
          'Acetate ion',
          'Acetic acid, fluoro-, methyl ester',
          'Acetochlor',
          'Acetone',
          'Acetonitrile',
          'Acetophenone',
          'Acifluorfen',
          'Acridine',
          'Acrolein',
          'Acrylonitrile',
          'Actinides',
          'Alachlor',
          'Albuterol',
          'Aldicarb',
          'Aldicarb sulfone',
          'Aldicarb sulfoxide',
          'Aldrin',
          'Allyl Alcohol',
          'Allyl chloride',
          'Alpha emitting isotopes',
          'Alpha radiation',
          'Aluminum',
          'Ametryn',
          'Ammonia',
          'Ammonia and ammonium',
          'Ammonia-nitrogen',
          'Ammonium',
          'Ammonium ion (NH4+) protolyte',
          'Ammonium nitrate',
          'Anhydrotetracycline (ATC)',
          'Aniline',
          'Anthracene',
          'Anthraquinone (8CI)',
          'Antimony',
          'Aquatic Bacteria',
          'Aroclor 1016',
          'Aroclor 1221',
          'Aroclor 1232',
          'Aroclor 1242',
          'Aroclor 1248',
          'Aroclor 1254',
          'Aroclor 1260',
          'Arsenic',
          'Arsenic ion (3+)',
          'Arsenic ion (5+)',
          'Atraton',
          'Atrazine',
          'Atrazine + N-Dealkylated Metabolites',
          'Azinphos-methyl',
          'Azinphosmethyl oxon',
          'Azithromycin',
          'Azobenzene',
          'BDE-003',
          'BDE-153',
          'BDE-154',
          'Bacteria, complex with amylase and proteinase',
          'Barium',
          'Bentazon',
          'Benz[a]anthracene',
          'Benzanthrone',
          'Benzene',
          'Benzene, 1,2,3-trimethoxy-',
          'Benzene, 1,3-dichloro-5-nitro-',
          'Benzene, 1-bromo-2-chloro-',
          'Benzene, 1-bromo-3-chloro-',
          'Benzene, 1-bromo-4-phenoxy-***retired***use BDE-003',
          'Benzene, 1-chloro-4-methyl-2-nitro-',
          "Benzene, 2,4-dibromo-1-(2,4-dibromophenoxy)-***retired***use 2,2',4,4'-Tetrachlorobiphenyl",
          'Benzene, 4-chloro-1-methyl-2-nitro-',
          'Benzene, pentamethyl-',
          'Benzenesulfonamide, 4-amino-N-2-pyrimidinyl-',
          'Benzidine',
          'Benzo(b)fluoranthene',
          'Benzo[a]pyrene',
          'Benzo[b,j,k]fluoranthene',
          'Benzo[c]cinnoline',
          'Benzo[ghi]perylene',
          'Benzo[k]fluoranthene',
          'Benzoic acid',
          'Benzophenone',
          'Benzyl alcohol',
          'Beryllium',
          'Bioaccumulation',
          'Biopermethrin',
          'Bis(2-butoxyethyl) phthalate',
          'Bis(2-chloro-1-methylethyl) ether',
          'Bis(2-chloroethoxy)methane',
          'Bis(2-chloroethyl) ether',
          'Bis(2-chloroisopropyl) ether',
          'Bis(2-ethylhexyl) phthalate***retired***use Di(2-ethylhexyl) phthalate',
          'Bismuth',
          'Bismuth-210',
          'Boron',
          'Brevetoxins',
          'Bromacil',
          'Bromate',
          'Bromide',
          'Bromoacetic acid',
          'Bromoacetone',
          'Bromobenzene',
          'Bromochloroacetic acid',
          'Bromochloromethane',
          'Bromoxynil',
          'Butachlor',
          'Butane, 2-ethoxy-2-methyl-',
          'Butyl benzyl phthalate',
          'Butylate',
          'C.I. Basic Red 1',
          'C1-C4 Fluoranthenes',
          'C1-C4 Phenanthrenes',
          'CFC-11',
          'CFC-12',
          'Cacodylic acid',
          'Cadmium',
          'Caffeine',
          'Campesterol (6CI)',
          'Camphor',
          'Carbadox',
          'Carbamate pesticides',
          'Carbamazepine',
          'Carbaryl',
          'Carbazole',
          'Carbofuran',
          'Carbon',
          'Carbon disulfide',
          'Carbon tetrachloride',
          'Carboxin',
          'Cerium',
          'Cesium',
          'Cesium, total beta radioactivity',
          'Cesium-134',
          'Cesium-137',
          'Chemiluminesence',
          'Chloramben',
          'Chloramben methyl ester',
          'Chloramines, Total',
          'Chlorate',
          'Chlordane',
          'Chloride',
          'Chlorine',
          'Chlorite',
          'Chloroacetic acid',
          'Chlorobenzene',
          'Chlorobenzilate',
          'Chlorodibromomethane',
          'Chloroethane',
          'Chloroform',
          'Chloromethane',
          'Chloroneb',
          'Chlorophyll a',
          'Chlorophyll b',
          'Chlorophyll c1',
          'Chlorophyll c1 + c2',
          'Chlorophyll c2',
          'Chloroprene',
          'Chlorothalonil',
          'Chlorpropham',
          'Chlorpyrifos',
          'Chlortetracycline',
          'Chlorthal',
          'Chlorthal-dimethyl',
          'Cholesterol',
          'Chromium',
          'Chromium(III)',
          'Chromium(VI)',
          'Chrysene',
          'Cimetidine',
          'Cobalt',
          'Cobalt-60',
          'Codeine',
          'Coliphage',
          'Color',
          'Copper',
          'Coprosterol',
          'Cotinine',
          'Coumaphos',
          'Cumene',
          'Cyanazine',
          'Cyanide, available',
          'Cyanides',
          'Cycloate',
          'Cyclonite',
          'Cyclotetramethylenetetranitramine',
          'Cylindrospermopsin',
          'Cymene',
          'D-Limonene',
          'D2-Virginiamycin M1',
          'D3-1,7-Dimethylxanthine',
          'D3-Carbadox',
          'D3-Cefotaxime',
          'D3-Clarithromycin',
          'D3-Digoxigenin',
          'D3-Digoxin',
          'D3-Lincomycin',
          'D3-Naproxen',
          'D3-Norgestimate',
          'D3-Ofloxacin',
          'D3-Tylosin',
          'D4-Sulfadiazine',
          'D4-Sulfamerazine',
          'D4-Sulfamethizole',
          'D4-Sulfanilamide',
          'D4-Sulfathiazole',
          'D5-Amphetamine',
          'D5-Diphenhydramine',
          'D5-Enrofloxacin',
          'D5-Miconazole',
          'D5-Norfloxacin',
          'D5-Oxacillin',
          'D5-Oxolinic Acid',
          'D5-Penicillin G',
          'D5-Penicillin V',
          'D5-Triamterene',
          'D6-2-Hydroxy-ibuprofen',
          'D6-Dehydronifedipine',
          'D6-Ranitidine',
          'D6-Sulfadimethoxine',
          'D7-Roxithromycin',
          'D8-Sarafloxacin',
          'DCPA mono-acid degradate',
          'Dacthal Acid Metabolites',
          'Dalapon',
          'Decabromodiphenyl ether***retired***use Decabromodiphenyl oxide',
          'Decachlorobiphenyl',
          'Decanal',
          'Dehydronifedipine',
          'Demeton-O',
          'Demeton-S',
          'Desmosterol',
          'Di(2-ethylhexyl) adipate',
          'Di(2-ethylhexyl) phthalate',
          'Di-n-octyl phthalate',
          'Diazinon',
          'Dibenz[a,h]anthracene',
          'Dibenz[a,j]acridine',
          'Dibenzofuran',
          'Dibenzothiophene',
          'Dibenzyl phthalate',
          'Dibromoacetic acid',
          'Dibromomethane',
          'Dibutyl phthalate',
          'Dicamba',
          'Dichloroacetic acid',
          'Dichlorobromomethane',
          'Dichlorodifluoromethane***retired***use CFC-12',
          'Dichlorofenthion',
          'Dichlorprop',
          'Dichlorvos',
          'Dicofol',
          'Dieldrin',
          'Diethyl phthalate',
          'Dihexyl phthalate',
          'Dihydrosafrole',
          'Diisopropyl methylphosphonate',
          'Dilantin',
          'Diltiazem',
          'Dimethoate',
          'Dimethyl phthalate',
          'Dimethyl sulfone',
          'Dinitramine',
          'Dinonyl phthalate',
          'Dinoseb',
          'Dipentyl phthalate',
          'Diphenamid',
          'Diphenyl isophthalate',
          'Diphenyl phthalate',
          'Diphenylamine',
          'Diquat',
          'Disulfoton',
          'Diuron',
          'Dysprosium',
          'Endosulfan sulfate',
          'Endrin',
          'Endrin aldehyde',
          'Endrin ketone',
          'Enterococcus',
          'Equilenin',
          'Erbium',
          'Ergosterol',
          'Erythritol anhydride',
          'Erythromycin',
          'Erythromycin-anhydro',
          'Escherichia coli',
          'Estradiol',
          'Estriol',
          'Estrone',
          'Ethanamine, 2-(diphenylmethoxy)-N,N-dimethyl-',
          'Ethanimidothioic acid, N-hydroxy-, methyl ester',
          'Ethinyl estradiol',
          'Ethion',
          'Ethoprop',
          'Ethyl diethanolamine',
          'Ethyl ether',
          'Ethyl methacrylate',
          'Ethyl methanesulfonate',
          'Ethyl tert-butyl ether',
          'Ethylbenzene',
          'Ethylene dibromide',
          'Etridiazole',
          'Europium',
          'Europium-154',
          'Fecal Coliform',
          'Fenamiphos',
          'Fenarimol',
          'Fensulfothion',
          'Fenthion',
          'Fenuron',
          'Ferric ion',
          'Ferrous ion',
          'Flufenacet ESA',
          'Flumetralin',
          'Fluoranthene',
          'Fluorene',
          'Fluoride',
          'Fluoxetine',
          'Fluridone',
          'Formate',
          'Gadolinium',
          'Gallium',
          'Gamma emitting isotopes',
          'Gemfibrozil',
          'Giardia',
          'Glyoxal',
          'Glyphosate',
          'Gold',
          'HAA5',
          'Hafnium',
          'Halowax 1000',
          'Halowax 1001',
          'Halowax 1013',
          'Halowax 1014',
          'Halowax 1099',
          'Heptachlor',
          'Heptachlor epoxide',
          'Herbicides',
          'Hexabromobiphenyl',
          'Hexachlorobenzene',
          'Hexachlorobutadiene',
          'Hexachlorocyclopentadiene',
          'Hexachloroethane',
          'Hexachloropropene',
          'Hexamethylenetriperoxidediamine',
          'Hexane Extractable Material (HEM)',
          'Hexavalent chromium compounds',
          'Hexazinone',
          'Holmium',
          'Human Enteric viruses',
          'Hydrobromic acid',
          'Imidacloprid',
          'Indeno[1,2,3-cd]pyrene',
          'Indole',
          'Inorganic carbon',
          'Inorganic monomeric aluminum',
          'Inorganic nitrogen (NO2, NO3, & NH3)',
          'Inorganic nitrogen (ammonia, nitrate and nitrite)***retired***use Inorganic nitrogen (NO2, NO3, & NH3)',
          'Inorganic nitrogen (nitrate and nitrite) ***retired***use Nitrate + Nitrite',
          'Inorganic phosphorus',
          'Iridium',
          'Iridium-192',
          'Iron',
          'Iron-55',
          'Isoborneol',
          'Isobutanol',
          'Isodrin',
          'Isophorone',
          'Isoquinoline',
          'Isosafrole',
          'Kjeldahl nitrogen',
          'Lactonitrile',
          'Lanthanum',
          'Lauryl acrylate',
          'Lead',
          'Lincomycin',
          'Lindane',
          'Linuron',
          'Lithium',
          'Longifolene',
          'Lutetium',
          'MCPA',
          'Malachite green',
          'Malathion',
          'Malononitrile',
          'Manganese',
          'Mecoprop',
          'Merphos',
          'Mestranol',
          'Metalaxyl',
          'Metformin',
          'Methacrylonitrile',
          'Methiocarb',
          'Methomyl',
          'Methoxychlor',
          'Methoxyethylmercuric acetate',
          'Methyl acetate',
          'Methyl bromide',
          'Methyl ethyl ketone',
          'Methyl iodide',
          'Methyl isobutyl ketone',
          'Methyl methacrylate',
          'Methyl methanesulfonate',
          'Methyl paraoxon',
          'Methyl parathion',
          'Methyl salicylate',
          'Methyl tert-butyl ether',
          'Methylarsonic acid',
          'Methylene chloride',
          'Methylglyoxal',
          'Metochlor ESA',
          'Metolachlor',
          'Metribuzin',
          'Mevinphos',
          'Mirex',
          'Molinate',
          'Molybdenum',
          'Monocrotophos',
          'N,N-Diethyl-m-toluamide',
          'N-2-Ethylhexylbicycloheptenedicarboximide',
          'N-Methyl-N-nitrosoaniline',
          'N-Methylethanolamine',
          'N-Nitrosodi-n-butylamine',
          'N-Nitrosodi-n-propylamine',
          'N-Nitrosodiethylamine',
          'N-Nitrosodimethylamine',
          'N-Nitrosodiphenylamine',
          'N-Nitrosopiperidine',
          'N-Nitrosopyrrolidine',
          'Naphthalene',
          'Napropamide',
          'Naproxen',
          'Neodymium',
          'Nickel',
          'Niobium',
          'Nitramine',
          'Nitrate',
          'Nitrate + Nitrite',
          'Nitrite',
          'Nitrobenzene',
          'Nitrogen',
          'Nitrogen mustard (HN-1)',
          'Nitrogen mustard (HN-3)',
          'Nitrogen trichloride',
          'Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)',
          'Nitrophenol-d6',
          'Norflurazon',
          'Nutrient-nitrogen***retired***use TOTAL NITROGEN, MIXED FORMS with speciation AS N',
          'O-Dinitrobenzene',
          'O-Ethyl O-(p-nitrophenyl) phenylphosphonothioate',
          'O-Ethyl O-methyl S-propyl phosphorothioate',
          'Octachlorostyrene',
          'Organic Nitrogen',
          'Organic carbon',
          'Organic phosphorus',
          'Organics, semivolatile',
          'Organohalide Respiring Bacteria',
          'Organophosphate pesticides',
          'Ormetoprim',
          'Orthophosphate',
          'Oxamyl',
          'Oxolinic acid',
          'Oxychlordane',
          'Oxytetracycline',
          'Palladium',
          'Paraquat',
          'Parathion',
          'Particulate Organic Nitrogen and Particulate Nitrogen',
          'Pebulate',
          'Penoxsulam',
          'Pentachloroanisole',
          'Pentachlorobenzene',
          'Pentachlorodibenzo-p-dioxin',
          'Pentachlorodibenzofuran',
          'Pentachloroethane',
          'Pentachloronitrobenzene',
          'Pentachlorophenol',
          'Perchlorate',
          'Perfluorotetradecanoic acid',
          'Perthane',
          'Petroleum',
          'Phenacetin',
          'Phenanthrene',
          'Phenanthridine',
          'Phenol',
          'Phenolics',
          'Phenothiazine',
          'Pheopigments of Chlorophyll',
          'Phorate',
          'Phosmet',
          'Phosphate-phosphorus***retired***use Orthophosphate',
          'Phosphonate',
          'Phosphorus',
          'Phosphorus (white or yellow)',
          'Phosphorus, Particulate Organic',
          'Phosphorus, hydrolyzable',
          'Phosphorus, hydrolyzable plus orthophosphate',
          'Picloram',
          'Pinacolyl methylphosphonic acid',
          'Platinum',
          'Polar organic chemicals',
          'Polonium',
          'Polychlorinated biphenyls',
          'Polyethylene glycol',
          'Polyphosphate',
          'Potassium',
          'Praseodymium',
          'Procymidone',
          'Progesterone',
          'Prometon',
          'Prometryn',
          'Pronamide',
          'Propachlor',
          'Propanenitrile',
          'Propazine',
          'Propoxur',
          'Propranolol',
          'Pyrene',
          'Pyridine',
          'Quinoline',
          'Radioactive isotopes',
          'Radium',
          'Radium-226',
          'Radium-228',
          'Ranitidine',
          'Rhenium',
          'Rhodium',
          'Ronnel',
          'Roxithromycin',
          'Rubidium',
          'Ruthenium',
          'Ruthenium-106',
          'S-Ethyl dipropylthiocarbamate',
          'Safrole',
          'Samarium',
          'Saxitoxin',
          'Scandium',
          'Schradan',
          'Selenium',
          'Selenium-79',
          'Silica',
          'Silicate',
          'Silver',
          'Silvex',
          'Simazine',
          'Simetryn',
          'Sodium',
          'Sodium nitrite',
          'Soluble Reactive Phosphorus (SRP)',
          'Spinosad',
          'Staphylococcal enterotoxin b',
          'Stigmastan-3.beta.-ol',
          'Stigmasterol',
          'Strontium',
          'Strontium-90',
          'Styrene',
          'Sulfadimethoxine',
          'Sulfamerazine',
          'Sulfamethazine',
          'Sulfamethizole',
          'Sulfamethoxazole',
          'Sulfanilamide',
          'Sulfate',
          'Sulfathiazole',
          'Sulfide',
          'Sulfochlorpyridazine',
          'Sulfotep',
          'Surfactants',
          'T-2 Mycotoxins',
          'Tantalum',
          'Tebuthiuron',
          'Technitium-99',
          'Terbacil',
          'Terbium',
          'Terbufos',
          'Terbufoxon Sulfone',
          'Terbutryn',
          'Terphenyl-dl4',
          'Testosterone',
          'Tetrachloroethene***retired***use Tetrachloroethylene',
          'Tetrachlorvinphos',
          'Tetrahydrofuran',
          'Thallium',
          'Thiabendazole',
          'Thioacetamide',
          'Thiofanox',
          'Thioxanthone',
          'Thorium-232',
          'Thulium',
          'Tin',
          'Toluene',
          'Toluene-2,4-diisocyanate',
          'Total Coliform',
          'Total Kjeldahl nitrogen',
          'Total Kjeldahl nitrogen (Organic N & NH3)',
          'Total Nitrogen, mixed forms',
          'Total Nitrogen, mixed forms (NH3), (NH4), organic, (NO2) and (NO3)',
          'Total Particulate Nitrogen',
          'Total Particulate Organic Nitrogen***retired***use TOTAL NITROGEN, MIXED FORMS with speciation AS N and fraction SUSPENDED',
          'Total Particulate Phosphorus',
          'Total Phosphorus, mixed forms',
          'Total Volatile Hydrocarbons, C6-C10',
          'Total beta radioactivity',
          'Total xylenes',
          'Toxaphene',
          'Trans-1,2-dichloroethene-d2',
          'Transpermethrin',
          'Tri-o-cresyl phosphate',
          'Triacetonetriperoxide',
          'Triadimefon',
          'Tribromomethane',
          'Tributyl phosphate',
          'Trichloroacetic acid',
          'Trichloroethylene',
          'Triclocarban',
          'Triclopyr',
          'Triclosan',
          'Tricyclazole',
          'Triethyl citrate',
          'Trifluralin',
          'Trihalomethanes (four), total',
          'Trimethoprim',
          'Trinitrotoluene',
          'Triphenyl phosphate',
          'Tris(1,3-dichloro-2-propyl)phosphate',
          'Tris(2-butoxyethyl) phosphate',
          'Tris(2-chloroethyl) phosphate',
          'Tungsten',
          'Tylosin',
          'Uranium-232',
          'Uranium-238',
          'Urethane',
          'Vanadium',
          'Vernolate',
          'Vinyl acetate',
          'Vinyl chloride',
          'Volatile organic compounds',
          'Warfarin',
          'White mineral oil (petroleum)',
          'Ytterbium',
          'Yttrium',
          'Zinc',
          'Zirconium',
          '[2-(2-Methoxymethylethoxy)methylethoxy]propanol',
          'beta-Estradiol 3-benzoate',
          'beta-Propiolactone',
          'cis-1,2-Dichloroethylene',
          'cis-1,3-Dichloropropene',
          'cis-Chlordane',
          'cis-Nonachlor',
          'd3-Valsartan',
          'd4-Amlodipine (2-aminoethoxy-d4)',
          'd4-Desmethyldiltiazem',
          'd5-Betamethasone',
          'd5-Fluticasone propionate',
          'd7-Verapamil',
          'd8-Prednisone',
          'epi-Coprostanol',
          'm,p-Xylene',
          'm-Cresol',
          'm-Dinitrobenzene',
          'm-Nitroaniline',
          'm-Nitrophenol',
          'm-Nitrotoluene',
          'm-Xylene',
          'n-Butylbenzene',
          'n-Propylbenzene',
          "o,p'-DDD",
          "o,p'-DDE",
          "o,p'-DDT",
          "o,p'-Methoxychlor",
          'o-Chlorophenol',
          'o-Chlorotoluene',
          'o-Cresol',
          'o-Dichlorobenzene',
          'o-Nitroaniline',
          'o-Nitrophenol',
          'o-Nitrotoluene',
          'o-Xylene',
          "p,p'-DDD",
          "p,p'-DDE",
          "p,p'-DDT",
          'p-(1,1,3,3-Tetramethylbutyl)phenol',
          'p-Bromophenyl phenyl ether***retired***use BDE-003',
          'p-Chloroaniline',
          'p-Chloronitrobenzene',
          'p-Chlorophenyl methyl sulfone',
          'p-Chlorophenyl p-nitrophenyl ether',
          'p-Chlorophenyl phenyl ether',
          'p-Chlorotoluene',
          'p-Cresol',
          'p-Cumylphenol',
          'p-Cymene',
          'p-Dichlorobenzene',
          'p-Dinitrobenzene',
          'p-Nitroaniline',
          'p-Nitrophenol',
          'p-Nitrotoluene',
          'p-Octylphenol',
          'p-Xylene',
          'sec-Butylbenzene',
          'sec-Dichloropropane',
          'tert-Amyl methyl ether',
          'tert-Butanol',
          'tert-Butylbenzene',
          'trans-1,2-Dichloroethylene',
          'trans-1,3-Dichloropropene',
          'trans-1,4-Dichloro-2-butene',
          'trans-Chlordane',
          'trans-Crotonaldehyde',
          'trans-Nonachlor'
        ]
      }
    },
    required: ['CharacteristicName']
  },
  then: {
    properties: {
      ResultAnalyticalMethodID: {},
      ResultAnalyticalMethodContext: {}
    },
    required: ['ResultAnalyticalMethodID', 'ResultAnalyticalMethodContext']
  }
}
