name: build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.x
      -
        name: Create .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      -
        name: npm access
        run: |
          npm access ls-packages
      -
        name: Cache npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      -
        name: Install dependencies
        run: |
          npm install
          npm audit fix
      -
        name: Download and rebuild allowed values
        run: |
          npm run download
          npm run build
      -
        name: Check for file changes
        run: |
          git config --local user.name ${{ github.actor }}
          git config --local user.email github-actions@datastream.org
          git status --porcelain
          echo "change=$(git status --porcelain | wc -l)" >> $GITHUB_ENV
      -
        if: env.change != 0
        name: Commit & push changes
        run: |
          git add -A
          git commit -a -m 'ci: update allowed values'
          npm version patch
          git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:${GITHUB_REF#refs/*/} --follow-tags --force --tags
      -
        if: env.change != 0
        name: Publish
        run: |
          cp package.json dist/package.json
          cd dist
          npm publish
#      -
#        if: env.change != 0
#        name: Trigger @gordonfn/schema rebuild
#        run: |
#          curl -X POST https://api.github.com/repos/gordonfn/schema/dispatches \
#          -H 'Accept: application/vnd.github.everest-preview+json' \
#          -u ${{ secrets.GITHUB_TOKEN }} \
#          --data '{"event_type": "wqx", "client_payload": {}'