name: build

on:
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.x
      -
        name: Create .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      -
        name: Install dependencies
        run: |
          npm install
      -
        name: Download and rebuild allowed values
        run: |
          npm run download
          npm run build
      -
        name: Check for file changes
        run: |
          git config --local user.name ${{ github.actor }}
          git config --local user.email github-actions@datastream.org
          echo "change=$(git status --porcelain)" >> $GITHUB_ENV
      -
        if: env.change
        name: Bump version if changes
        run: |
          npm version patch
          echo "tag=$(npm view @gordonfn/normalize version)" >> $GITHUB_ENV
      -
        if: env.change
        name: Commit Changes
        run: |
          git add -A
          git commit -a -m 'ci: update allowed values'
          git tag ${{ env.tag }}
          git push "https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${REPOSITORY}.git" HEAD:${INPUT_BRANCH} --follow-tags --force --tags
      -
        if: env.change
        name: Publish
        run: |
          cd dist &&
          npm publish